export const audiencePages = [
  { slug: "pet-owner", name: "Pet owner", title: "Rawat Pet Lebih Mudah Bersama Slivadoc", intro: "Cari kebutuhan hewan, pilih layanan, dan simpan aktivitas perawatan dalam satu akun. Mulai dari profil pet agar informasi penting lebih mudah ditemukan saat dibutuhkan.", benefits: ["Bandingkan harga, stok, dan informasi produk sebelum membeli", "Temukan layanan grooming, klinik, vaksinasi, dan penitipan dari mitra aktif", "Simpan profil pet serta riwayat aktivitas untuk membantu perawatan rutin", "Terhubung dengan komunitas, adopsi, dan kegiatan pet"], steps: ["Lengkapi profil dan kebutuhan pet", "Pilih produk atau layanan sesuai lokasi dan ketersediaan", "Periksa rincian biaya lalu lanjutkan transaksi atau booking"], cta: "Buka Slivadoc", href: "/?view=discover" },
  { slug: "dokter-hewan", name: "Dokter hewan", title: "Slivadoc untuk Dokter Hewan & Praktik Veteriner", intro: "Satukan informasi pasien, konsultasi, jadwal, dan tindak lanjut dalam alur kerja veteriner. Profil profesional membantu pet owner memahami layanan serta bidang praktik yang ditawarkan.", benefits: ["Profil dokter dan informasi layanan lebih mudah ditemukan", "Konsultasi terhubung dengan identitas dan riwayat pet", "Pengelolaan jadwal serta aktivitas konsultasi", "Kolaborasi dengan klinik dan ekosistem pet care"], steps: ["Daftarkan profil profesional", "Lengkapi dokumen dan proses verifikasi", "Tampilkan layanan serta jadwal yang benar-benar tersedia"], cta: "Daftar sebagai mitra", href: "https://partners.slivadoc.com" },
  { slug: "klinik-hewan", name: "Pet clinic", title: "Aplikasi Klinik Hewan: Rekam Medis, Booking & Operasional", intro: "Bantu tim klinik mengelola perjalanan pasien dari pencarian layanan hingga kunjungan. Informasi cabang, tindakan, jadwal, dan transaksi menjadi lebih mudah ditelusuri.", benefits: ["Rekam medis dan riwayat kunjungan pet", "Booking, jadwal dokter, dan informasi layanan klinik", "Inventori serta transaksi operasional cabang", "Profil klinik dengan alamat dan layanan publik"], steps: ["Daftarkan bisnis dan cabang klinik", "Lengkapi verifikasi, alamat wilayah, serta layanan", "Ajak tim menggunakan operasional Slivadoc"], cta: "Daftarkan klinik", href: "https://partners.slivadoc.com" },
  { slug: "petshop", name: "Petshop", title: "Aplikasi POS Petshop Gratis & Katalog Marketplace", intro: "Kelola katalog, harga, dan stok petshop sambil menampilkan produk yang memenuhi persyaratan marketplace kepada pet owner. Informasi produk yang lengkap membantu pembeli menentukan pilihan.", benefits: ["POS dan transaksi petshop", "Inventori serta katalog produk terhubung", "Produk dapat memiliki halaman publik untuk pencarian", "Pengelolaan pelanggan dan operasional cabang"], steps: ["Daftarkan bisnis petshop dan verifikasi dokumen", "Lengkapi foto, komposisi, harga, stok, serta kebijakan produk", "Aktifkan produk yang memenuhi persyaratan marketplace"], cta: "Daftarkan petshop", href: "https://partners.slivadoc.com" },
  { slug: "grooming", name: "Usaha grooming", title: "Aplikasi Grooming Hewan: Jadwal, Layanan & Booking", intro: "Jelaskan paket grooming, hewan yang dilayani, durasi, dan persiapan kunjungan agar pet owner bisa memilih layanan dengan informasi yang cukup.", benefits: ["Daftar paket dengan harga dan durasi", "Booking layanan terhubung dengan pet owner", "Informasi persiapan dan kebutuhan pet", "Profil cabang untuk membantu pencarian lokal"], steps: ["Daftarkan bisnis dan lokasi grooming", "Tulis detail paket, persiapan, serta ketentuan pembatalan", "Tampilkan layanan aktif dan kelola booking"], cta: "Daftarkan usaha grooming", href: "https://partners.slivadoc.com" },
  { slug: "pet-hotel", name: "Pet hotel & daycare", title: "Slivadoc untuk Pet Hotel, Boarding & Daycare", intro: "Bantu pemilik hewan menilai pilihan penitipan dari fasilitas, persyaratan pet, harga, dan ketersediaan. Informasi yang jelas membantu tim menyiapkan setiap kedatangan.", benefits: ["Informasi fasilitas dan layanan penitipan", "Harga dan ketentuan layanan terlihat sebelum booking", "Persyaratan pet serta persiapan kunjungan", "Profil usaha terhubung dengan ekosistem pet owner"], steps: ["Daftarkan lokasi dan fasilitas", "Lengkapi persyaratan, paket, serta ketentuan penitipan", "Kelola ketersediaan dan konfirmasi booking"], cta: "Daftarkan pet hotel", href: "https://partners.slivadoc.com" },
] as const;
export const audienceBySlug = new Map(audiencePages.map((p) => [p.slug as string, p]));
