import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import JsonLd from "../../components/seo/JsonLd";
import { Breadcrumbs, PublicPage } from "../../components/seo/PublicSite";
import { cityBySlug, cityPages, servicePages } from "../../lib/seo-content";
import { absoluteUrl, breadcrumbSchema, pageMetadata } from "../../lib/seo-config";

export function generateStaticParams(){return cityPages.map(({slug})=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const city=cityBySlug.get(slug);if(!city)return pageMetadata({title:"Kota tidak ditemukan",description:"Area layanan Slivadoc tidak ditemukan.",path:`/kota/${slug}`,noIndex:true});return pageMetadata({title:`Dokter Hewan, Petshop & Pet Clinic di ${city.name}`,description:city.description,path:`/kota/${city.slug}`,keywords:[`dokter hewan ${city.name}`,`petshop ${city.name}`,`pet clinic ${city.name}`,`grooming ${city.name}`]});}

export default async function CityDetailPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const city=cityBySlug.get(slug);if(!city)notFound();const schema=[{"@context":"https://schema.org","@type":"WebPage",name:`Layanan pet care di ${city.name}`,description:city.description,url:absoluteUrl(`/kota/${city.slug}`),about:{"@type":"City",name:city.name,containedInPlace:{"@type":"AdministrativeArea",name:city.province}}},{"@context":"https://schema.org","@type":"ItemList",name:`Kategori layanan hewan di ${city.name}`,itemListElement:servicePages.map((service,index)=>({"@type":"ListItem",position:index+1,name:`${service.name} di ${city.name}`,url:absoluteUrl(`/layanan/${service.slug}`)}))},breadcrumbSchema([{name:"Beranda",path:"/"},{name:"Kota",path:"/kota"},{name:city.name,path:`/kota/${city.slug}`}])];return <PublicPage><JsonLd data={schema}/><section className="seo-hero"><Breadcrumbs items={[{label:"Beranda",href:"/"},{label:"Kota",href:"/kota"},{label:city.name}]}/><div className="seo-hero-grid"><div><span className="seo-eyebrow">{city.province}</span><h1>Layanan pet care dan dokter hewan di {city.name}</h1><p>{city.intro}</p><div className="seo-hero-actions"><Link className="seo-primary" href="/?view=discover">Cari layanan di aplikasi</Link><Link className="seo-secondary" href="/layanan">Pilih kategori layanan</Link></div><div className="seo-tag-list">{city.nearbyAreas.map((area)=><span key={area}>{area}</span>)}</div></div><aside className="seo-hero-panel"><strong>Tips pencarian di {city.name}</strong><ul><li>Aktifkan lokasi untuk mengurutkan berdasarkan jarak</li><li>Periksa jenis hewan dan layanan yang didukung</li><li>Konfirmasi jadwal serta ketersediaan sebelum berangkat</li><li>Untuk kondisi darurat, hubungi fasilitas secara langsung</li></ul></aside></div></section><section className="seo-main-section"><div className="seo-section-heading"><h2>Kategori layanan di sekitar {city.name}</h2><p>Pilih kategori terlebih dahulu. Hasil aktual, harga, jam layanan, dan ketersediaan mengikuti data mitra yang aktif di Slivadoc.</p></div><div className="seo-card-grid">{servicePages.map((service)=><Link className="seo-card" key={service.slug} href={`/layanan/${service.slug}`}><small>{city.name}</small><h2>{service.name}</h2><p>{service.description}</p><span>Lihat kategori →</span></Link>)}</div></section><section className="seo-related"><div className="seo-main-section"><div className="seo-info-box"><h2>Area belum menampilkan hasil?</h2><p>Jangkauan layanan bergantung pada mitra yang aktif dan lokasi pengguna. Gunakan pencarian Slivadoc untuk melihat hasil terkini atau jelajahi area sekitar {city.nearbyAreas.slice(0,3).join(", ")}.</p><div className="seo-hero-actions"><Link className="seo-primary" href="/?view=discover">Buka pencarian Slivadoc</Link><Link className="seo-secondary" href="/mitra">Daftarkan bisnis pet</Link></div></div></div></section></PublicPage>}
