"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import type { Pet } from "../../data/mock";
import {
  checkInPetship,
  checkoutPetship,
  createFundraiser,
  createFundraiserDonation,
  getFundraisers,
  getMyFundraisers,
  getPetshipPlaces,
  getPetshipPresences,
  heartbeatPetship,
  simulateFundraiserDonationPaid,
  type Fundraiser,
  type MyFundraiser,
  type PetshipPlace,
  type PetshipPresence,
} from "../../lib/platform-api";
import type { LocationResult } from "../../lib/petowner-api";
import { Icon } from "../Icon";

const money = new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 });
const integer = new Intl.NumberFormat("id-ID");

export function PetshipView({ pet, authenticated, location, notify, onLogin }: { pet: Pet; authenticated: boolean; location: LocationResult | null; notify: (message: string) => void; onLogin: () => void }) {
  const [places,setPlaces]=useState<PetshipPlace[]>([]);const[selected,setSelected]=useState<PetshipPlace|null>(null);const[pawrents,setPawrents]=useState<PetshipPresence[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[checkedIn,setCheckedIn]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{const response=await getPetshipPlaces(location?{latitude:location.latitude,longitude:location.longitude}:undefined);setPlaces(response.data);setSelected(current=>current??response.data[0]??null)}catch(error){notify(error instanceof Error?error.message:"Lokasi Petship belum dapat dimuat")}finally{setLoading(false)}},[location,notify]);
  useEffect(()=>{queueMicrotask(()=>void load())},[load]);
  useEffect(()=>{let cancelled=false;if(!selected){queueMicrotask(()=>{if(!cancelled)setPawrents([])});return()=>{cancelled=true}}void getPetshipPresences(selected.id).then(response=>{if(!cancelled)setPawrents(response.data)}).catch(()=>{if(!cancelled)setPawrents([])});return()=>{cancelled=true}},[selected]);
  useEffect(()=>{if(!checkedIn)return;const timer=window.setInterval(()=>void heartbeatPetship().catch(()=>setCheckedIn(false)),60_000);return()=>window.clearInterval(timer)},[checkedIn]);
  async function checkIn(){if(!authenticated){onLogin();return}if(!selected||!pet.id)return notify("Pilih pet dan lokasi terlebih dahulu");setBusy(true);try{const response=await checkInPetship({pet_id:pet.id,place_id:selected.id,visibility:"nearby",message:`${pet.name} sedang di sini dan siap berkenalan.`});setCheckedIn(true);notify(response.message);await load();setPawrents((await getPetshipPresences(selected.id)).data)}catch(error){notify(error instanceof Error?error.message:"Check-in belum dapat disimpan")}finally{setBusy(false)}}
  async function checkOut(){setBusy(true);try{const response=await checkoutPetship();setCheckedIn(false);notify(response.message);await load()}catch(error){notify(error instanceof Error?error.message:"Check-out belum dapat diproses")}finally{setBusy(false)}}
  return <div className="petship-page"><section className="petship-hero"><div><span className="world-kicker">LIVE · PRIVACY-FIRST</span><h2>Temukan teman anabul di sekitarmu</h2><p>Check-in pada tempat yang kamu kunjungi. Pawrents lain hanya melihat nama tempat dan profil pet—bukan koordinat personal.</p><div><button className="primary-button" disabled={busy||!selected} onClick={()=>void(checkedIn?checkOut():checkIn())}>{checkedIn?"Check-out Petship":`Check-in ${pet.name}`}</button><button className="secondary-button" onClick={()=>void load()}>↻ Update live</button></div></div><span className="petship-radar">🐾<i/><b/></span></section><div className="petship-layout"><section className="panel"><div className="panel-heading"><div><span className="section-eyebrow">TEMPAT DI SEKITARMU</span><h3>{places.length} lokasi aktif</h3></div></div>{loading?<div className="empty-state compact">Mencari lokasi Petship…</div>:<div className="petship-places">{places.map(place=><button className={selected?.id===place.id?"active":""} key={place.id} onClick={()=>setSelected(place)}><span>{place.category==="mall"?"🏬":place.category==="park"?"🌳":"☕"}</span><div><b>{place.name}</b><small>{place.city}{typeof place.distance_km==="number"?` · ${place.distance_km.toFixed(1)} km`:""}</small></div><em>{place.active_petowners} online</em></button>)}</div>}</section><section className="panel"><div className="panel-heading"><div><span className="section-eyebrow">PAWRENTS LIVE</span><h3>{selected?.name??"Pilih lokasi"}</h3></div><em className="live-place-count">{pawrents.length} aktif</em></div><div className="petship-pawrents">{pawrents.length?pawrents.map(item=><article key={item.id}><span>{item.species==="cat"?"🐈":"🐕"}</span><div><b>{item.pet_name}</b><small>{item.breed} · bersama {item.owner_first_name}</small><p>{item.message||"Sedang menikmati waktu bersama."}</p></div><i/></article>):<div className="empty-state compact">Belum ada pawrents aktif di lokasi ini. Jadilah yang pertama check-in.</div>}</div></section></div></div>;
}

export function FundraisingView({pet,authenticated,notify,onLogin}:{pet:Pet;authenticated:boolean;notify:(message:string)=>void;onLogin:()=>void}){
  const[items,setItems]=useState<Fundraiser[]>([]);const[mine,setMine]=useState<MyFundraiser[]>([]);const[active,setActive]=useState<Fundraiser|null>(null);const[createOpen,setCreateOpen]=useState(false);const[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);try{const [publicData,myData]=await Promise.all([getFundraisers(),authenticated?getMyFundraisers():Promise.resolve({data:[],count:0})]);setItems(publicData.data);setMine(myData.data)}catch(error){notify(error instanceof Error?error.message:"Penggalangan dana belum dapat dimuat")}finally{setLoading(false)}},[authenticated,notify]);useEffect(()=>{queueMicrotask(()=>void load())},[load]);
  return <div className="fundraising-page"><section className="fundraising-hero"><span>♥</span><div><small>SLIVADOC ANIMAL FUND</small><h2>Bersama, perawatan jadi mungkin</h2><p>Campaign diverifikasi tim operasional. Dana, jumlah donatur, dan progres diperbarui dari transaksi yang sudah dibayar.</p></div><button className="primary-button" onClick={()=>authenticated?setCreateOpen(true):onLogin()}>＋ Galang dana</button></section>{mine.length>0&&<section className="panel my-fundraisers"><div className="panel-heading"><div><span className="section-eyebrow">PENGAJUAN SAYA</span><h3>Status verifikasi campaign</h3></div></div><div>{mine.map(item=><article key={item.id}><span className={`fund-status ${item.status}`}>{item.status}</span><b>{item.title}</b><small>{money.format(item.raised_amount)} dari {money.format(item.goal_amount)}</small></article>)}</div></section>}<div className="fundraiser-grid">{items.map(item=><article className="fundraiser-card" key={item.id}><div className="fundraiser-cover">🐾<span>{item.city}</span></div><div><small>TERVERIFIKASI SLIVADOC · {item.donor_count} DONATUR</small><h3>{item.title}</h3><p>{item.story}</p><div className="fundraiser-progress"><i><b style={{width:`${Math.min(100,item.progress_percent)}%`}}/></i><span><strong>{money.format(item.raised_amount)}</strong><em>dari {money.format(item.goal_amount)}</em></span></div><button className="primary-button full" onClick={()=>authenticated?setActive(item):onLogin()}>Donasi sekarang</button></div></article>)}</div>{loading&&<div className="empty-state compact">Memuat campaign terverifikasi…</div>}{!loading&&!items.length&&<div className="empty-state"><span>♥</span><h3>Belum ada campaign aktif</h3><p>Campaign baru akan tampil setelah verifikasi Slivadoc.</p></div>}{active&&<DonationModal item={active} close={()=>setActive(null)} notify={notify} paid={load}/>} {createOpen&&<CreateFundraiserModal pet={pet} close={()=>setCreateOpen(false)} notify={notify} created={load}/>}</div>;
}

function DonationModal({item,close,notify,paid}:{item:Fundraiser;close:()=>void;notify:(message:string)=>void;paid:()=>Promise<void>}){const[amount,setAmount]=useState("100000");const[busy,setBusy]=useState(false);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const values=Object.fromEntries(new FormData(event.currentTarget));try{const donation=await createFundraiserDonation(item.id,{amount:Number(amount),message:String(values.message||""),anonymous:values.anonymous==="on"});if(donation.mode==="simulation")await simulateFundraiserDonationPaid(donation.id);await paid();notify("Terima kasih, donasi berhasil disalurkan");close()}catch(error){notify(error instanceof Error?error.message:"Donasi belum dapat diproses")}finally{setBusy(false)}}return <div className="modal-overlay" onMouseDown={close}><section className="modal donation-modal" onMouseDown={event=>event.stopPropagation()}><button className="modal-close" onClick={close}><Icon name="close"/></button><span className="section-eyebrow">DONASI TRANSPARAN</span><h2>{item.title}</h2><p>{money.format(item.raised_amount)} sudah terkumpul untuk {item.beneficiary_name}.</p><form className="world-form" onSubmit={submit}><label><span>Nominal donasi</span><input inputMode="numeric" value={integer.format(Number(amount||0))} onChange={event=>setAmount(event.target.value.replace(/\D/g,""))} required/><input type="hidden" name="amount" value={amount}/></label><label><span>Pesan dukungan</span><textarea name="message" placeholder="Semoga lekas pulih…"/></label><label className="fund-check"><input name="anonymous" type="checkbox"/><span>Tampilkan sebagai donatur anonim</span></label><button className="primary-button full" disabled={busy||Number(amount)<10000}>{busy?"Memproses…":`Donasi ${money.format(Number(amount||0))}`}</button></form></section></div>}

function CreateFundraiserModal({pet,close,notify,created}:{pet:Pet;close:()=>void;notify:(message:string)=>void;created:()=>Promise<void>}){const[goal,setGoal]=useState("1000000");const[busy,setBusy]=useState(false);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const values=Object.fromEntries(new FormData(event.currentTarget));try{await createFundraiser({pet_id:pet.id||undefined,title:values.title,story:values.story,beneficiary_name:values.beneficiary_name,city:values.city,goal_amount:Number(goal),medical_document_urls:[],ends_at:values.ends_at?new Date(String(values.ends_at)).toISOString():undefined});await created();notify("Campaign dikirim untuk verifikasi Slivadoc");close()}catch(error){notify(error instanceof Error?error.message:"Campaign belum dapat dibuat")}finally{setBusy(false)}}return <div className="modal-overlay" onMouseDown={close}><section className="modal form-modal fundraiser-create-modal" onMouseDown={event=>event.stopPropagation()}><button className="modal-close" onClick={close}><Icon name="close"/></button><span className="section-eyebrow">AJUKAN PENGGALANGAN DANA</span><h2>Bantu hewan mendapatkan perawatan</h2><p className="muted-copy">Identitas, cerita, dan dokumen medis akan diperiksa sebelum campaign dipublikasikan.</p><form className="world-form" onSubmit={submit}><label><span>Judul campaign</span><input name="title" minLength={5} required/></label><label><span>Nama penerima</span><input name="beneficiary_name" defaultValue={pet.name||"Hewan rescue"} required/></label><label><span>Kota</span><input name="city" minLength={2} required/></label><label><span>Cerita dan kebutuhan medis</span><textarea name="story" minLength={30} required/></label><label><span>Target dana</span><input inputMode="numeric" value={integer.format(Number(goal||0))} onChange={event=>setGoal(event.target.value.replace(/\D/g,""))} required/><input type="hidden" name="goal_amount" value={goal}/></label><label><span>Batas campaign</span><input name="ends_at" type="date" required/></label><button className="primary-button full" disabled={busy||Number(goal)<100000}>{busy?"Mengirim…":"Kirim untuk verifikasi"}</button></form></section></div>}
