import Link from "next/link";
import JsonLd from "../components/seo/JsonLd";
import { Breadcrumbs, PublicPage } from "../components/seo/PublicSite";
import { getPublicPlaces } from "../lib/public-directory";
import { absoluteUrl, pageMetadata } from "../lib/seo-config";

export const metadata=pageMetadata({title:"Direktori Pet Clinic, Petshop & Layanan Hewan",description:"Jelajahi profil mitra Slivadoc, layanan, alamat, kota, dan informasi pet care yang tersedia dari sistem mitra aktif.",path:"/tempat",keywords:["direktori petshop","direktori pet clinic","layanan hewan terdekat","mitra Slivadoc"]});

export default async function PlacesPage(){const places=await getPublicPlaces();const schema={"@context":"https://schema.org","@type":"ItemList",name:"Direktori mitra Slivadoc",itemListElement:places.map((place,index)=>({"@type":"ListItem",position:index+1,name:`${place.name} — ${place.branchName}`,url:absoluteUrl(`/tempat/${place.slug}`)}))};return <PublicPage><JsonLd data={schema}/><section className="seo-hero"><Breadcrumbs items={[{label:"Beranda",href:"/"},{label:"Direktori tempat"}]}/><div className="seo-hero-grid"><div><span className="seo-eyebrow">Direktori mitra aktif</span><h1>Pet clinic, petshop, dan layanan hewan dalam satu direktori</h1><p>Profil tempat dibentuk dari data operasional mitra Slivadoc agar informasi layanan, lokasi, serta ketersediaannya dapat ditemukan secara konsisten.</p><div className="seo-hero-actions"><Link className="seo-primary" href="/?view=discover">Cari dengan lokasi</Link><Link className="seo-secondary" href="/mitra">Daftarkan bisnis pet</Link></div></div><aside className="seo-hero-panel"><strong>Data yang terhubung</strong><ul><li>Nama bisnis dan cabang aktif</li><li>Alamat, kota, dan koordinat bila tersedia</li><li>Kategori, durasi, serta harga layanan</li><li>Rating dan ulasan hanya saat memiliki data valid</li></ul></aside></div></section><section className="seo-main-section"><div className="seo-section-heading"><h2>Tempat yang tersedia</h2><p>Daftar diperbarui mengikuti layanan publik mitra. Profil yang tidak aktif tidak diterbitkan dalam direktori.</p></div>{places.length?<div className="seo-card-grid">{places.map((place)=><Link className="seo-card" key={place.slug} href={`/tempat/${place.slug}`}><small>{place.city||"Indonesia"}</small><h2>{place.name}</h2><p>{place.branchName} · {place.address}</p><span>{place.services.length} layanan tersedia →</span></Link>)}</div>:<div className="seo-empty"><h2>Data mitra sedang disinkronkan</h2><p>Buka pencarian Slivadoc untuk melihat layanan terkini di sekitar lokasi Anda.</p><div className="seo-hero-actions" style={{justifyContent:"center"}}><Link className="seo-primary" href="/?view=discover">Buka pencarian</Link></div></div>}</section></PublicPage>}
