import { LocalizedCopy } from "../components/LocalizedCopy";
import Link from "next/link";
import { Breadcrumbs, PublicPage } from "../components/seo/PublicSite";
import { pageMetadata } from "../lib/seo-config";
import { provinces, regionPath, regionSource } from "../lib/seo-regions";

export const metadata = pageMetadata({ title: "Cari Petshop & Layanan Hewan di Seluruh Wilayah Indonesia", description: "Telusuri provinsi, kabupaten/kota, kecamatan, dan desa di Indonesia. Temukan layanan mitra Slivadoc sesuai data lokasi dan ketersediaan.", path: "/wilayah" });
export default function RegionsPage() {
  const counts = regionSource.counts;
  return <PublicPage><section className="seo-hero"><Breadcrumbs items={[{ label: "Beranda", href: "/" }, { label: "Wilayah Indonesia" }]} /><span className="seo-eyebrow"><LocalizedCopy>{"Dari kota sampai desa"}</LocalizedCopy></span><h1><LocalizedCopy>{"Temukan pet care di wilayahmu"}</LocalizedCopy></h1><p><LocalizedCopy>{"Pilih provinsi, lalu lanjutkan ke kabupaten/kota, kecamatan, dan desa atau kelurahan. Layanan yang ditampilkan mengikuti lokasi cabang mitra yang aktif."}</LocalizedCopy></p></section><section className="seo-main-section"><div className="seo-section-heading"><h2><LocalizedCopy>{counts.provinces}</LocalizedCopy><LocalizedCopy>{" provinsi Indonesia"}</LocalizedCopy></h2><p><LocalizedCopy>{"Direktori wilayah memuat "}</LocalizedCopy><LocalizedCopy>{counts.regencies}</LocalizedCopy><LocalizedCopy>{" kabupaten/kota, "}</LocalizedCopy><LocalizedCopy>{counts.districts.toLocaleString("id-ID")}</LocalizedCopy><LocalizedCopy>{" kecamatan, dan "}</LocalizedCopy><LocalizedCopy>{counts.villages.toLocaleString("id-ID")}</LocalizedCopy><LocalizedCopy>{" desa/kelurahan. Cakupan data wilayah berbeda dengan ketersediaan mitra."}</LocalizedCopy></p></div><div className="seo-card-grid"><LocalizedCopy>{provinces.map((r) => <Link className="seo-card" href={regionPath(r)} key={r.code}><small><LocalizedCopy>{"Provinsi"}</LocalizedCopy></small><h2><LocalizedCopy>{r.name}</LocalizedCopy></h2><span><LocalizedCopy>{"Pilih kabupaten / kota →"}</LocalizedCopy></span></Link>)}</LocalizedCopy></div><p><LocalizedCopy>{"Referensi wilayah: "}</LocalizedCopy><a href={regionSource.source}><LocalizedCopy>{"data wilayah Kemendagri 2025 melalui cahyadsn/wilayah"}</LocalizedCopy></a><LocalizedCopy>{", snapshot "}</LocalizedCopy><LocalizedCopy>{regionSource.sourceRevision}</LocalizedCopy><LocalizedCopy>{"."}</LocalizedCopy></p></section></PublicPage>;
}
