import { LocalizedCopy } from "../components/LocalizedCopy";
import { LocalizedLink as Link } from "../components/LocalizedCopy";
import JsonLd from "../components/seo/JsonLd";
import { Breadcrumbs, PublicPage } from "../components/seo/PublicSite";
import { SEO, absoluteUrl, breadcrumbSchema, pageMetadata } from "../lib/seo-config";

export const metadata=pageMetadata({title:"Tentang Slivadoc",description:"Slivadoc adalah ekosistem pet care yang menghubungkan pet owner, dokter hewan, pet clinic, petshop, dan layanan hewan dalam satu platform.",path:"/tentang",keywords:["tentang Slivadoc","PT Sliva Technology Indonesia","platform pet care Indonesia"]});

export default function AboutPage(){const schema=[{"@context":"https://schema.org","@type":"AboutPage",name:"Tentang Slivadoc",url:absoluteUrl("/tentang"),about:{"@type":"Organization","@id":absoluteUrl("/#organization"),name:SEO.brand,legalName:SEO.legalName}},breadcrumbSchema([{name:"Beranda",path:"/"},{name:"Tentang",path:"/tentang"}])];return <PublicPage><JsonLd data={schema}/><section className="seo-hero"><Breadcrumbs items={[{label:"Beranda",href:"/"},{label:"Tentang Slivadoc"}]}/><div className="seo-hero-grid"><div><span className="seo-eyebrow"><LocalizedCopy>{"PT Sliva Technology Indonesia"}</LocalizedCopy></span><h1><LocalizedCopy>{"One Platform. Every Animal. One Connected Ecosystem."}</LocalizedCopy></h1><p><LocalizedCopy>{"Slivadoc dibangun untuk membuat dunia hewan lebih terhubung, terpercaya, dan mudah diakses—bagi pet owner, tenaga profesional, serta pelaku usaha."}</LocalizedCopy></p><div className="seo-hero-actions"><Link className="seo-primary" href="/?view=discover"><LocalizedCopy>{"Jelajahi Slivadoc"}</LocalizedCopy></Link><Link className="seo-secondary" href="/mitra"><LocalizedCopy>{"Kolaborasi sebagai mitra"}</LocalizedCopy></Link></div></div><aside className="seo-hero-panel"><strong><LocalizedCopy>{"Komitmen Slivadoc"}</LocalizedCopy></strong><ul><li><LocalizedCopy>{"Kesejahteraan hewan dan keputusan yang bertanggung jawab"}</LocalizedCopy></li><li><LocalizedCopy>{"Kemudahan akses ke layanan dan informasi"}</LocalizedCopy></li><li><LocalizedCopy>{"Keamanan data serta transparansi aktivitas"}</LocalizedCopy></li><li><LocalizedCopy>{"Pertumbuhan digital untuk mitra usaha"}</LocalizedCopy></li></ul></aside></div></section><section className="seo-main-section"><div className="seo-section-heading"><h2><LocalizedCopy>{"Ekosistem, bukan sekadar aplikasi"}</LocalizedCopy></h2><p><LocalizedCopy>{"Setiap sisi Slivadoc dirancang agar data dan aktivitas dapat saling terhubung tanpa menghilangkan peran tenaga profesional."}</LocalizedCopy></p></div><div className="seo-card-grid"><article className="seo-card"><small><LocalizedCopy>{"Pet owner"}</LocalizedCopy></small><h2><LocalizedCopy>{"Profil pet yang berkelanjutan"}</LocalizedCopy></h2><p><LocalizedCopy>{"Kelola kebutuhan, aktivitas, booking, pengingat, dan riwayat pet dalam satu pengalaman."}</LocalizedCopy></p></article><article className="seo-card"><small><LocalizedCopy>{"Profesional"}</LocalizedCopy></small><h2><LocalizedCopy>{"Akses layanan yang lebih jelas"}</LocalizedCopy></h2><p><LocalizedCopy>{"Dokter hewan dan penyedia layanan dapat ditemukan sesuai kebutuhan serta lokasi pet parent."}</LocalizedCopy></p></article><article className="seo-card"><small><LocalizedCopy>{"Mitra bisnis"}</LocalizedCopy></small><h2><LocalizedCopy>{"Operasional yang terhubung"}</LocalizedCopy></h2><p><LocalizedCopy>{"Pet clinic, petshop, grooming, pet hotel, dan bisnis hewan bertumbuh melalui sistem yang saling terintegrasi."}</LocalizedCopy></p></article></div></section></PublicPage>}
