import { Pressable, StyleSheet, Text, View } from "react-native";
import { useState } from "react";
import { colors, shadow } from "../theme";
import { Card, Pill, PrimaryButton, Screen, SoftButton, TopHeader } from "../components/ui";
import type { MobileActivity } from "../api";

export function ActivityScreen({ onAction, onBook, onOpenNotifications,activities,petNames }: { onAction: (message: string) => void; onBook: () => void; onOpenNotifications: () => void;activities:MobileActivity[];petNames:Record<string,string> }) {
  const [tab, setTab] = useState("Mendatang");
  const [now]=useState(()=>Date.now());
  const matches=(item:MobileActivity)=>tab==="Mendatang"?Boolean(item.starts_at&&new Date(item.starts_at).getTime()>now):tab==="Berlangsung"?["active","confirmed","processing","paid"].includes(item.status):!item.starts_at||new Date(item.starts_at).getTime()<=now||["completed","cancelled"].includes(item.status);
  const visible=activities.filter(matches);
  const counts={booking:activities.filter(item=>item.category==="booking").length,order:activities.filter(item=>item.category==="order").length,consult:activities.filter(item=>item.category==="consultation").length};
  return (
    <Screen>
      <TopHeader title="Aktivitas" subtitle="Booking, konsultasi & pesanan" onNotification={onOpenNotifications} />
      <Text style={styles.title}>Aktivitas pet-mu 🐾</Text><Text style={styles.subtitle}>Pantau semua booking, pesanan, dan konsultasi.</Text>
      <View style={styles.summaryRow}><Summary icon="📅" value={String(counts.booking)} label="Booking" color={colors.sky50} /><Summary icon="📦" value={String(counts.order)} label="Pesanan" color={colors.violet50} /><Summary icon="💬" value={String(counts.consult)} label="Konsultasi" color={colors.mint50} /></View>
      <View style={styles.tabs}>{["Mendatang", "Berlangsung", "Riwayat"].map((item) => <Pressable key={item} onPress={() => setTab(item)} style={[styles.tab, tab === item && styles.activeTab]}><Text style={[styles.tabText, tab === item && styles.activeTabText]}>{item}</Text></Pressable>)}</View>
      <View style={styles.list}>{visible.map(item=>{const date=new Date(item.starts_at||item.occurred_at);return <Card key={item.id} style={styles.bookingCard}><View style={styles.bookingDate}><Text style={styles.month}>{date.toLocaleDateString("id-ID",{month:"short"}).toUpperCase()}</Text><Text style={styles.day}>{String(date.getDate()).padStart(2,"0")}</Text><Text style={styles.time}>{date.toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit"})}</Text></View><View style={[styles.bookingIcon,item.category==="health"?styles.mint:item.category==="booking"?styles.violet:styles.blue]}><Text style={styles.bookingEmoji}>{item.category==="order"?"📦":item.category==="consultation"?"💬":item.category==="health"?"🩺":"📅"}</Text></View><View style={styles.bookingCopy}><Pill tone={item.status==="completed"?"mint":"yellow"}>{item.status.toUpperCase()}</Pill><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.cardNote}>{item.description}</Text>{item.pet_id&&<Text style={styles.petChip}>🐾 {petNames[item.pet_id]||"Pet"}</Text>}</View><View style={styles.bookingActions}><SoftButton label={item.action_label||"Detail"} onPress={()=>onAction(`${item.title}: ${item.description}`)} style={styles.flex}/>{item.metadata?.latitude&&item.metadata?.longitude?<PrimaryButton compact label="Arah" icon="navigate" onPress={()=>onAction(`Buka arah ke ${item.metadata.latitude}, ${item.metadata.longitude}`)} style={styles.flex}/>:null}</View></Card>})}{visible.length===0?<Card style={styles.deliveryCard}><Text style={styles.cardTitle}>Belum ada aktivitas</Text><Text style={styles.cardNote}>Data akan muncul setelah ada transaksi atau booking pada akun ini.</Text></Card>:null}<PrimaryButton label="Buat booking baru" icon="add" onPress={onBook}/></View>
    </Screen>
  );
}

function Summary({ icon, value, label, color }: { icon: string; value: string; label: string; color: string }) { return <View style={styles.summary}><View style={[styles.summaryIcon, { backgroundColor: color }]}><Text>{icon}</Text></View><Text style={styles.summaryValue}>{value}</Text><Text style={styles.summaryLabel}>{label}</Text></View>; }

const styles = StyleSheet.create({
  title: { marginTop: 8, color: colors.navy, fontSize: 22, lineHeight: 27, fontWeight: "900", letterSpacing: -.3 }, subtitle: { marginTop: 3, color: colors.muted, fontSize: 12, lineHeight: 17 },
  summaryRow: { flexDirection: "row", gap: 7, marginTop: 14 }, summary: { flex: 1, padding: 9, borderWidth: 1, borderColor: colors.line, borderRadius: 14, backgroundColor: colors.white, ...shadow }, summaryIcon: { width: 31, height: 31, borderRadius: 10, alignItems: "center", justifyContent: "center" }, summaryValue: { marginTop: 6, color: colors.navy, fontSize: 16, fontWeight: "900" }, summaryLabel: { marginTop: 1, color: colors.muted, fontSize: 9 },
  tabs: { height: 42, flexDirection: "row", gap: 3, marginTop: 14, marginBottom: 10, padding: 3, borderWidth: 1, borderColor: colors.line, borderRadius: 13, backgroundColor: colors.white }, tab: { flex: 1, borderRadius: 10, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 4 }, activeTab: { backgroundColor: colors.sky50 }, tabText: { color: colors.muted, fontSize: 10, fontWeight: "700" }, activeTabText: { color: colors.sky600 }, tabCount: { minWidth: 16, height: 16, borderRadius: 8, alignItems: "center", justifyContent: "center", backgroundColor: colors.sky100 },
  list: { gap: 9 }, bookingCard: { padding: 11, flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 9 }, bookingDate: { width: 45, height: 57, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: colors.sky50 }, month: { color: colors.sky600, fontSize: 9, fontWeight: "800" }, day: { color: colors.navy, fontSize: 21, lineHeight: 22, fontWeight: "900" }, time: { color: colors.muted, fontSize: 9 }, bookingIcon: { width: 40, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center" }, bookingEmoji: { fontSize: 23 }, mint: { backgroundColor: colors.mint50 }, violet: { backgroundColor: colors.violet50 }, blue: { backgroundColor: colors.sky50 }, bookingCopy: { flex: 1, minWidth: 150 }, cardTitle: { marginTop: 6, color: colors.navy, fontSize: 13, lineHeight: 17, fontWeight: "900" }, cardNote: { marginTop: 2, color: colors.muted, fontSize: 10, lineHeight: 15 }, petChip: { alignSelf: "flex-start", marginTop: 5, paddingHorizontal: 7, paddingVertical: 3, borderRadius: 8, overflow: "hidden", color: colors.text, backgroundColor: colors.canvas, fontSize: 9 }, bookingActions: { width: "100%", flexDirection: "row", gap: 6, paddingTop: 9, borderTopWidth: 1, borderTopColor: colors.line }, flex: { flex: 1 },
  deliveryCard: { padding: 15 }, deliveryTop: { flexDirection: "row", alignItems: "center", gap: 11 }, deliveryCopy: { flex: 1 }, progress: { flexDirection: "row", gap: 5, marginVertical: 15 }, progressDone: { flex: 1, height: 4, borderRadius: 2, backgroundColor: colors.sky500 }, progressActive: { flex: 1, height: 4, borderRadius: 2, backgroundColor: colors.sky400 }, courier: { flexDirection: "row", alignItems: "center", gap: 9, padding: 10, borderRadius: 12, backgroundColor: colors.sky50 }, courierAvatar: { width: 39, height: 39, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: colors.white }, courierCopy: { flex: 1 }, courierName: { color: colors.navy, fontSize: 13, fontWeight: "800" }, courierNote: { marginTop: 3, color: colors.muted, fontSize: 11 }, phone: { width: 34, height: 34, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: colors.white }, rowButtons: { flexDirection: "row", gap: 7, marginTop: 12 },
  historyList: { gap: 8 }, history: { minHeight: 72, flexDirection: "row", alignItems: "center", gap: 10, padding: 12, borderWidth: 1, borderColor: colors.line, borderRadius: 14, backgroundColor: colors.white }, historyIcon: { width: 40, height: 40, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#EFF6FA" }, historyCopy: { flex: 1 }, historyTitle: { color: colors.navy, fontSize: 13, fontWeight: "800" }, historyDate: { marginTop: 4, color: colors.muted, fontSize: 11 }, historyPrice: { color: colors.text, fontSize: 12, fontWeight: "800", textAlign: "right" }, historyStatus: { marginTop: 4, color: colors.mint, fontSize: 11, fontWeight: "700", textAlign: "right" },
});
