import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useState } from "react";
import { healthRecords, pets } from "../data";
import { colors, shadow } from "../theme";
import { Card, Pill, PrimaryButton, Screen, SectionTitle, SoftButton, TopHeader } from "../components/ui";

export function HealthScreen({ onAction, onBook, onOpenNotifications }: { onAction: (message: string) => void; onBook: () => void; onOpenNotifications: () => void }) {
  const [tab, setTab] = useState("Ringkasan");
  const pet = pets[0];
  return <Screen>
    <TopHeader title="Pusat Kesehatan" subtitle="Digital health record" onNotification={onOpenNotifications} />
    <Card style={styles.healthHero}><View style={styles.heroTop}><View style={styles.avatar}><Text style={styles.avatarEmoji}>{pet.icon}</Text></View><View style={styles.heroCopy}><Text style={styles.kicker}>PROFIL KESEHATAN</Text><Text style={styles.petName}>{pet.name}</Text><Text style={styles.petMeta}>{pet.breed} • {pet.weight}</Text></View><View style={styles.score}><Text style={styles.scoreValue}>{pet.score}</Text><Text style={styles.scoreLabel}>Excellent</Text></View></View><View style={styles.heroMeta}><View><Text style={styles.metaLabel}>Alergi</Text><Text style={styles.metaValue}>Protein ayam</Text></View><View><Text style={styles.metaLabel}>Dokter utama</Text><Text style={styles.metaValue}>drh. Amanda</Text></View><View><Text style={styles.metaLabel}>Update</Text><Text style={styles.metaValue}>12 Agu 2026</Text></View></View></Card>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.tabs}>{["Ringkasan", "Rekam Medis", "Vaksin", "Obat", "Dokumen"].map((item) => <Pressable key={item} onPress={() => setTab(item)} style={[styles.tab, tab === item && styles.activeTab]}><Text style={[styles.tabText, tab === item && styles.activeTabText]}>{item}</Text>{item === "Obat" ? <View style={styles.alertDot} /> : null}</Pressable>)}</ScrollView>

    {tab === "Ringkasan" ? <>
      <SectionTitle eyebrow="PREVENTIVE CARE" title="Proteksi Milo" action="Atur" onAction={onBook} />
      <Card style={styles.prevention}><View style={styles.progressCircle}><Text style={styles.progressValue}>4/5</Text><Text style={styles.progressLabel}>Lengkap</Text></View><View style={styles.checklist}><Check done title="Vaksin rabies" note="Aktif s.d. Sep 2026" /><Check done title="Obat cacing" note="18 Juli 2026" /><Check done title="Flea & tick" note="Proteksi aktif" /><Check title="Vaksin DHPPi" note="Jatuh tempo 4 Sep" /></View></Card>
      <SectionTitle eyebrow="BODY CONDITION" title="Tren berat badan" />
      <Card style={styles.weightCard}><View style={styles.weightHead}><View><Text style={styles.weightValue}>28.4 kg</Text><Text style={styles.weightNote}>Rentang ideal 27–32 kg</Text></View><Pill tone="mint">IDEAL</Pill></View><View style={styles.chart}><View style={styles.chartGrid} /><View style={styles.lineOne} /><View style={styles.lineTwo} /><View style={styles.point} /></View><View style={styles.months}>{["Mar","Apr","Mei","Jun","Jul","Agu"].map((month) => <Text key={month}>{month}</Text>)}</View></Card>
      <SectionTitle eyebrow="HARI INI" title="Obat aktif" action="Tambah" onAction={() => onAction("Tambah obat baru")} />
      <Card style={styles.medicine}><View style={styles.medicineIcon}><Text>💊</Text></View><View style={styles.medicineCopy}><Text style={styles.medicineTime}>SETIAP HARI • 19.00</Text><Text style={styles.medicineName}>Omega Skin & Coat</Text><Text style={styles.medicineNote}>1 tablet setelah makan • Sisa 18</Text></View><Pressable style={styles.checkButton} onPress={() => onAction("Obat ditandai sudah diberikan")}><Ionicons name="checkmark" size={16} color={colors.white} /></Pressable></Card>
    </> : null}

    {tab === "Rekam Medis" ? <View style={styles.records}>{healthRecords.map((record) => <Pressable key={record.id} onPress={() => onAction(`Membuka ${record.title}`)} style={styles.record}><View style={styles.recordIcon}><Text>{record.icon}</Text></View><View style={styles.recordCopy}><Text style={styles.recordDate}>{record.date}</Text><Text style={styles.recordTitle}>{record.title}</Text><Text style={styles.recordNote}>{record.note}</Text></View><Ionicons name="chevron-forward" size={17} color="#A2AFBC" /></Pressable>)}</View> : null}
    {tab === "Vaksin" ? <View style={styles.vaccines}>{["Rabies","DHPPi","Bordetella","Leptospirosis"].map((name,index) => <Card key={name} style={[styles.vaccine, index === 1 && styles.vaccineDue]}><View style={[styles.vaccineIcon,index === 1 ? styles.yellowBg : styles.mintBg]}><Text>{index === 1 ? "⏳" : "💉"}</Text></View><View style={styles.vaccineCopy}><Text style={[styles.vaccineStatus,index === 1 && styles.yellowText]}>{index === 1 ? "JATUH TEMPO 4 SEP" : "TERLINDUNGI"}</Text><Text style={styles.vaccineName}>{name}</Text><Text style={styles.vaccineNote}>{index === 1 ? "Perlu diperbarui" : "Dosis lengkap"}</Text></View><SoftButton label={index === 1 ? "Booking" : "Sertifikat"} onPress={() => index === 1 ? onBook() : onAction("Sertifikat vaksin dibuka")} /></Card>)}</View> : null}
    {tab === "Obat" ? <View style={styles.obatPage}><SectionTitle eyebrow="JADWAL HARI INI" title="1 pengingat aktif" /><Card style={styles.obatCard}><Text style={styles.obatTime}>19.00</Text><View style={styles.medicineIcon}><Text>💊</Text></View><View style={styles.medicineCopy}><Text style={styles.medicineName}>Omega Skin & Coat</Text><Text style={styles.medicineNote}>1 tablet • Setelah makan</Text></View></Card><PrimaryButton label="Tambah pengingat obat" icon="add" onPress={() => onAction("Form pengingat obat dibuka")} /></View> : null}
    {tab === "Dokumen" ? <View style={styles.documents}>{["Sertifikat vaksin","Hasil lab CBC","Resep Omega Tabs","Pet insurance policy","Microchip certificate"].map((name,index) => <Pressable key={name} onPress={() => onAction(`${name} dibuka`)} style={styles.document}><View style={styles.docIcon}><Text>{index === 3 ? "🛡️" : "📄"}</Text></View><View style={styles.docCopy}><Text style={styles.docName}>{name}</Text><Text style={styles.docMeta}>PDF • {(index + 1)}.2 MB</Text></View><Ionicons name="download-outline" size={18} color={colors.sky600} /></Pressable>)}</View> : null}
  </Screen>;
}

function Check({ done, title, note }: { done?: boolean; title: string; note: string }) { return <View style={styles.checkRow}><View style={[styles.check, done && styles.checkDone]}>{done ? <Ionicons name="checkmark" size={12} color={colors.white} /> : <Text style={styles.exclamation}>!</Text>}</View><View><Text style={styles.checkTitle}>{title}</Text><Text style={styles.checkNote}>{note}</Text></View></View>; }

const styles = StyleSheet.create({
  healthHero: { marginTop: 10, padding: 16, overflow: "hidden", backgroundColor: colors.sky600 }, heroTop: { flexDirection: "row", alignItems: "center" }, avatar: { width: 65, height: 65, borderRadius: 19, borderWidth: 1, borderColor: "rgba(255,255,255,.35)", alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,255,255,.17)" }, avatarEmoji: { fontSize: 39 }, heroCopy: { flex: 1, marginLeft: 11 }, kicker: { color: "rgba(255,255,255,.65)", fontSize: 7, fontWeight: "800", letterSpacing: .8 }, petName: { marginTop: 4, color: colors.white, fontSize: 20, fontWeight: "900" }, petMeta: { marginTop: 2, color: "rgba(255,255,255,.72)", fontSize: 8 }, score: { width: 62, height: 62, borderRadius: 31, borderWidth: 6, borderColor: colors.white, alignItems: "center", justifyContent: "center" }, scoreValue: { color: colors.white, fontSize: 17, fontWeight: "900" }, scoreLabel: { color: "rgba(255,255,255,.75)", fontSize: 6 }, heroMeta: { flexDirection: "row", marginTop: 14, paddingTop: 12, borderTopWidth: 1, borderTopColor: "rgba(255,255,255,.2)" }, metaLabel: { color: "rgba(255,255,255,.6)", fontSize: 6 }, metaValue: { marginTop: 3, color: colors.white, fontSize: 8, fontWeight: "700" },
  tabs: { gap: 6, paddingVertical: 15, paddingRight: 16 }, tab: { position: "relative", minHeight: 35, paddingHorizontal: 13, borderRadius: 10, borderWidth: 1, borderColor: colors.line, alignItems: "center", justifyContent: "center", backgroundColor: colors.white }, activeTab: { borderColor: colors.sky500, backgroundColor: colors.sky50 }, tabText: { color: colors.muted, fontSize: 8, fontWeight: "700" }, activeTabText: { color: colors.sky600 }, alertDot: { position: "absolute", right: 6, top: 5, width: 5, height: 5, borderRadius: 3, backgroundColor: colors.red },
  prevention: { padding: 15, flexDirection: "row", alignItems: "center", gap: 18 }, progressCircle: { width: 93, height: 93, borderRadius: 47, borderWidth: 10, borderColor: colors.sky500, alignItems: "center", justifyContent: "center" }, progressValue: { color: colors.navy, fontSize: 18, fontWeight: "900" }, progressLabel: { color: colors.muted, fontSize: 7 }, checklist: { flex: 1, gap: 10 }, checkRow: { flexDirection: "row", alignItems: "center", gap: 8 }, check: { width: 21, height: 21, borderRadius: 7, alignItems: "center", justifyContent: "center", backgroundColor: colors.yellow50 }, checkDone: { backgroundColor: colors.mint }, exclamation: { color: colors.yellow, fontSize: 9, fontWeight: "900" }, checkTitle: { color: colors.text, fontSize: 8, fontWeight: "800" }, checkNote: { marginTop: 2, color: colors.muted, fontSize: 6 },
  weightCard: { padding: 15 }, weightHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, weightValue: { color: colors.navy, fontSize: 18, fontWeight: "900" }, weightNote: { marginTop: 3, color: colors.muted, fontSize: 7 }, chart: { position: "relative", height: 100, marginTop: 10, overflow: "hidden", borderBottomWidth: 1, borderBottomColor: colors.line }, chartGrid: { position: "absolute", inset: 0, borderTopWidth: 1, borderTopColor: colors.line, borderStyle: "dashed" }, lineOne: { position: "absolute", left: -15, top: 62, width: 220, height: 4, borderRadius: 2, backgroundColor: colors.sky400, transform: [{ rotate: "-8deg" }] }, lineTwo: { position: "absolute", right: -15, top: 45, width: 200, height: 4, borderRadius: 2, backgroundColor: colors.sky400, transform: [{ rotate: "4deg" }] }, point: { position: "absolute", right: 8, top: 47, width: 12, height: 12, borderRadius: 6, borderWidth: 3, borderColor: colors.sky500, backgroundColor: colors.white }, months: { flexDirection: "row", justifyContent: "space-between", marginTop: 7 },
  medicine: { padding: 13, flexDirection: "row", alignItems: "center", gap: 10 }, medicineIcon: { width: 42, height: 42, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: colors.sky50 }, medicineCopy: { flex: 1 }, medicineTime: { color: colors.sky600, fontSize: 7, fontWeight: "800" }, medicineName: { marginTop: 3, color: colors.navy, fontSize: 10, fontWeight: "900" }, medicineNote: { marginTop: 3, color: colors.muted, fontSize: 7 }, checkButton: { width: 34, height: 34, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: colors.mint },
  records: { gap: 9, marginTop: 5 }, record: { minHeight: 79, flexDirection: "row", alignItems: "center", gap: 10, padding: 12, borderWidth: 1, borderColor: colors.line, borderRadius: 14, backgroundColor: colors.white, ...shadow }, recordIcon: { width: 43, height: 43, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#EFF6FA" }, recordCopy: { flex: 1 }, recordDate: { color: colors.sky600, fontSize: 7, fontWeight: "800" }, recordTitle: { marginTop: 4, color: colors.navy, fontSize: 10, fontWeight: "900" }, recordNote: { marginTop: 3, color: colors.muted, fontSize: 7 },
  vaccines: { gap: 9 }, vaccine: { padding: 13, flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 10 }, vaccineDue: { borderColor: "#F1D99A" }, vaccineIcon: { width: 42, height: 42, borderRadius: 12, alignItems: "center", justifyContent: "center" }, mintBg: { backgroundColor: colors.mint50 }, yellowBg: { backgroundColor: colors.yellow50 }, vaccineCopy: { flex: 1 }, vaccineStatus: { color: colors.mint, fontSize: 6, fontWeight: "900" }, yellowText: { color: colors.yellow }, vaccineName: { marginTop: 3, color: colors.navy, fontSize: 11, fontWeight: "900" }, vaccineNote: { marginTop: 3, color: colors.muted, fontSize: 7 },
  obatPage: { gap: 11 }, obatCard: { padding: 13, flexDirection: "row", alignItems: "center", gap: 10 }, obatTime: { color: colors.sky600, fontSize: 11, fontWeight: "900" },
  documents: { gap: 8 }, document: { minHeight: 65, flexDirection: "row", alignItems: "center", gap: 10, padding: 11, borderWidth: 1, borderColor: colors.line, borderRadius: 13, backgroundColor: colors.white }, docIcon: { width: 40, height: 40, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: "#EFF6FA" }, docCopy: { flex: 1 }, docName: { color: colors.navy, fontSize: 9, fontWeight: "800" }, docMeta: { marginTop: 3, color: colors.muted, fontSize: 7 },
});
