import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useState } from "react";
import type { PetView } from "../data";
import type { MobileMedicalRecord } from "../api";
import { colors, shadow } from "../theme";
import { Card, Screen, SectionTitle, TopHeader } from "../components/ui";

export function HealthScreen({ onAction, onBook, onOpenNotifications,pet,records,loading }: { onAction: (message: string) => void; onBook: () => void; onOpenNotifications: () => void;pet?:PetView;records:MobileMedicalRecord[];loading:boolean }) {
  const [tab, setTab] = useState("Ringkasan");
  const petView=pet??{id:"",name:"Pet",breed:"Login untuk melihat profil",age:"—",weight:"—",icon:"🐾",score:0,allergies:""};
  const latest=records[0];
  return <Screen>
    <TopHeader title="Pusat Kesehatan" subtitle="Digital health record" onNotification={onOpenNotifications} />
    <Card style={styles.healthHero}><View style={styles.heroGlow}/><View style={styles.heroTop}><View style={styles.avatar}><Text style={styles.avatarEmoji}>{petView.icon}</Text></View><View style={styles.heroCopy}><Text style={styles.kicker}>HEALTH PROFILE ✦</Text><Text style={styles.petName}>{petView.name}</Text><Text style={styles.petMeta}>{petView.breed} • {petView.weight}</Text></View><View style={styles.score}><Text style={styles.scoreValue}>{petView.score}</Text><Text style={styles.scoreLabel}>Health</Text></View></View><View style={styles.heroMeta}><View style={styles.metaBlock}><Text style={styles.metaLabel}>Alergi</Text><Text numberOfLines={1} style={styles.metaValue}>{petView.allergies||"Belum dicatat"}</Text></View><View style={styles.metaBlock}><Text style={styles.metaLabel}>Dokter terbaru</Text><Text numberOfLines={1} style={styles.metaValue}>{latest?.doctor_name||"Belum ada"}</Text></View><View style={styles.metaBlock}><Text style={styles.metaLabel}>Update</Text><Text numberOfLines={1} style={styles.metaValue}>{latest?new Date(latest.occurred_at).toLocaleDateString("id-ID"):"Belum ada"}</Text></View></View></Card>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.tabs}>{["Ringkasan", "Rekam Medis"].map((item) => <Pressable key={item} onPress={() => setTab(item)} style={[styles.tab, tab === item && styles.activeTab]}><Text style={[styles.tabText, tab === item && styles.activeTabText]}>{item}</Text></Pressable>)}</ScrollView>

    {tab === "Ringkasan" ? <>
      <SectionTitle eyebrow="RINGKASAN KESEHATAN" title={`Data medis ${petView.name}`} action="Booking" onAction={onBook} />
      <Card style={styles.prevention}><View style={styles.progressCircle}><Text style={styles.progressValue}>{records.length}</Text><Text style={styles.progressLabel}>Record</Text></View><View style={styles.checklist}><View style={styles.checkRow}><View style={[styles.check,records.length>0&&styles.checkDone]}>{records.length>0?<Ionicons name="checkmark" size={12} color={colors.white}/>:<Text style={styles.exclamation}>!</Text>}</View><View><Text style={styles.checkTitle}>{records.length?"Rekam medis tersinkron":"Belum ada rekam medis"}</Text><Text style={styles.checkNote}>{latest?.title||"Buat booking pemeriksaan untuk memulai record"}</Text></View></View><View style={styles.checkRow}><View style={[styles.check,petView.score>0&&styles.checkDone]}>{petView.score>0?<Ionicons name="checkmark" size={12} color={colors.white}/>:<Text style={styles.exclamation}>!</Text>}</View><View><Text style={styles.checkTitle}>Health score {petView.score}/100</Text><Text style={styles.checkNote}>Dihitung dari data pet pada server</Text></View></View></View></Card>
      {latest&&<><SectionTitle eyebrow="RECORD TERBARU" title={latest.title}/><Card style={styles.medicine}><View style={styles.medicineIcon}><Text>🩺</Text></View><View style={styles.medicineCopy}><Text style={styles.medicineTime}>{new Date(latest.occurred_at).toLocaleString("id-ID")}</Text><Text style={styles.medicineName}>{latest.diagnosis||latest.complaint||latest.title}</Text><Text style={styles.medicineNote}>{latest.doctor_name||"Dokter belum dicatat"}</Text></View><Pressable style={styles.checkButton} onPress={()=>setTab("Rekam Medis")}><Ionicons name="arrow-forward" size={16} color={colors.white}/></Pressable></Card></>}
    </> : null}

    {tab === "Rekam Medis" ? <View style={styles.records}>{loading?<Text style={styles.recordNote}>Memuat rekam medis…</Text>:records.length?records.map((record) => <Pressable key={record.id} onPress={() => onAction(`${record.title}: ${record.diagnosis||record.clinical_notes||"Tidak ada keterangan tambahan"}`)} style={styles.record}><View style={styles.recordIcon}><Text>{record.record_type.toLowerCase().includes("lab")?"🧪":record.record_type.toLowerCase().includes("vaks")?"💉":"🩺"}</Text></View><View style={styles.recordCopy}><Text style={styles.recordDate}>{new Date(record.occurred_at).toLocaleString("id-ID")}</Text><Text style={styles.recordTitle}>{record.title}</Text><Text style={styles.recordNote}>{record.diagnosis||record.clinical_notes||record.complaint||"Tidak ada keterangan tambahan"}</Text></View><Ionicons name="chevron-forward" size={17} color="#A2AFBC" /></Pressable>):<Text style={styles.recordNote}>Belum ada rekam medis untuk {petView.name}.</Text>}</View> : null}
  </Screen>;
}

const styles = StyleSheet.create({
  healthHero: { position: "relative", marginTop: 8, padding: 14, overflow: "hidden", borderWidth: 0, backgroundColor: colors.sky600 }, heroGlow: { position: "absolute", right: -45, top: -65, width: 160, height: 160, borderRadius: 80, backgroundColor: "rgba(255,255,255,.12)" }, heroTop: { flexDirection: "row", alignItems: "center" }, avatar: { width: 54, height: 54, borderRadius: 18, borderWidth: 1, borderColor: "rgba(255,255,255,.4)", alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,255,255,.2)" }, avatarEmoji: { fontSize: 32 }, heroCopy: { minWidth: 0, flex: 1, marginLeft: 10 }, kicker: { color: "rgba(255,255,255,.7)", fontSize: 9, fontWeight: "800", letterSpacing: .8 }, petName: { marginTop: 3, color: colors.white, fontSize: 19, fontWeight: "900" }, petMeta: { marginTop: 2, color: "rgba(255,255,255,.78)", fontSize: 10 }, score: { width: 52, height: 52, borderRadius: 26, borderWidth: 5, borderColor: colors.white, alignItems: "center", justifyContent: "center" }, scoreValue: { color: colors.white, fontSize: 17, fontWeight: "900" }, scoreLabel: { color: "rgba(255,255,255,.78)", fontSize: 8 }, heroMeta: { flexDirection: "row", gap: 8, marginTop: 12, paddingTop: 10, borderTopWidth: 1, borderTopColor: "rgba(255,255,255,.2)" }, metaBlock: { minWidth: 0, flex: 1 }, metaLabel: { color: "rgba(255,255,255,.65)", fontSize: 8 }, metaValue: { marginTop: 2, color: colors.white, fontSize: 10, fontWeight: "700" },
  tabs: { gap: 6, paddingVertical: 12, paddingRight: 14 }, tab: { position: "relative", minHeight: 33, paddingHorizontal: 12, borderRadius: 10, borderWidth: 1, borderColor: colors.line, alignItems: "center", justifyContent: "center", backgroundColor: colors.white }, activeTab: { borderColor: colors.sky500, backgroundColor: colors.sky50 }, tabText: { color: colors.muted, fontSize: 10, fontWeight: "700" }, activeTabText: { color: colors.sky600 }, alertDot: { position: "absolute", right: 6, top: 5, width: 5, height: 5, borderRadius: 3, backgroundColor: colors.red },
  prevention: { padding: 13, flexDirection: "row", alignItems: "center", gap: 13 }, progressCircle: { width: 76, height: 76, borderRadius: 38, borderWidth: 8, borderColor: colors.sky500, alignItems: "center", justifyContent: "center" }, progressValue: { color: colors.navy, fontSize: 18, fontWeight: "900" }, progressLabel: { color: colors.muted, fontSize: 9 }, checklist: { minWidth: 0, flex: 1, gap: 9 }, checkRow: { minWidth: 0, flexDirection: "row", alignItems: "center", gap: 7 }, check: { width: 19, height: 19, borderRadius: 7, alignItems: "center", justifyContent: "center", backgroundColor: colors.yellow50 }, checkDone: { backgroundColor: colors.mint }, exclamation: { color: colors.yellow, fontSize: 11, fontWeight: "900" }, checkTitle: { color: colors.text, fontSize: 11, fontWeight: "800" }, checkNote: { marginTop: 1, color: colors.muted, fontSize: 9 },
  weightCard: { padding: 15 }, weightHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, weightValue: { color: colors.navy, fontSize: 22, fontWeight: "900" }, weightNote: { marginTop: 3, color: colors.muted, fontSize: 11 }, chart: { position: "relative", height: 100, marginTop: 10, overflow: "hidden", borderBottomWidth: 1, borderBottomColor: colors.line }, chartGrid: { position: "absolute", inset: 0, borderTopWidth: 1, borderTopColor: colors.line, borderStyle: "dashed" }, lineOne: { position: "absolute", left: -15, top: 62, width: 220, height: 4, borderRadius: 2, backgroundColor: colors.sky400, transform: [{ rotate: "-8deg" }] }, lineTwo: { position: "absolute", right: -15, top: 45, width: 200, height: 4, borderRadius: 2, backgroundColor: colors.sky400, transform: [{ rotate: "4deg" }] }, point: { position: "absolute", right: 8, top: 47, width: 12, height: 12, borderRadius: 6, borderWidth: 3, borderColor: colors.sky500, backgroundColor: colors.white }, months: { flexDirection: "row", justifyContent: "space-between", marginTop: 7 },
  medicine: { padding: 11, flexDirection: "row", alignItems: "center", gap: 9 }, medicineIcon: { width: 38, height: 38, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: colors.sky50 }, medicineCopy: { flex: 1 }, medicineTime: { color: colors.sky600, fontSize: 9, fontWeight: "800" }, medicineName: { marginTop: 2, color: colors.navy, fontSize: 12, fontWeight: "900" }, medicineNote: { marginTop: 2, color: colors.muted, fontSize: 9 }, checkButton: { width: 32, height: 32, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: colors.mint },
  records: { gap: 8, marginTop: 3 }, record: { minHeight: 70, flexDirection: "row", alignItems: "center", gap: 9, padding: 10, borderWidth: 1, borderColor: colors.line, borderRadius: 14, backgroundColor: colors.white, ...shadow }, recordIcon: { width: 39, height: 39, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: colors.sky50 }, recordCopy: { flex: 1 }, recordDate: { color: colors.sky600, fontSize: 9, fontWeight: "800" }, recordTitle: { marginTop: 3, color: colors.navy, fontSize: 12, fontWeight: "900" }, recordNote: { marginTop: 2, color: colors.muted, fontSize: 10, lineHeight: 15 },
  vaccines: { gap: 9 }, vaccine: { padding: 13, flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 10 }, vaccineDue: { borderColor: "#F1D99A" }, vaccineIcon: { width: 42, height: 42, borderRadius: 12, alignItems: "center", justifyContent: "center" }, mintBg: { backgroundColor: colors.mint50 }, yellowBg: { backgroundColor: colors.yellow50 }, vaccineCopy: { flex: 1 }, vaccineStatus: { color: colors.mint, fontSize: 10, fontWeight: "900" }, yellowText: { color: colors.yellow }, vaccineName: { marginTop: 3, color: colors.navy, fontSize: 15, fontWeight: "900" }, vaccineNote: { marginTop: 3, color: colors.muted, fontSize: 11 },
  obatPage: { gap: 11 }, obatCard: { padding: 13, flexDirection: "row", alignItems: "center", gap: 10 }, obatTime: { color: colors.sky600, fontSize: 15, fontWeight: "900" },
  documents: { gap: 8 }, document: { minHeight: 65, flexDirection: "row", alignItems: "center", gap: 10, padding: 11, borderWidth: 1, borderColor: colors.line, borderRadius: 13, backgroundColor: colors.white }, docIcon: { width: 40, height: 40, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: "#EFF6FA" }, docCopy: { flex: 1 }, docName: { color: colors.navy, fontSize: 13, fontWeight: "800" }, docMeta: { marginTop: 3, color: colors.muted, fontSize: 11 },
});
