import { Pressable, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { colors, shadow } from "../theme";
import { Card, Pill, Screen, SectionTitle, SoftButton, TopHeader } from "../components/ui";
import type { MobileBootstrap, MobileOwner } from "../api";

export function ProfileScreen({ onAction, onOpenNotifications,owner,petCount,activityCount,points,rewardFormula,onLogin,onLogout }: { onAction: (message: string) => void; onOpenNotifications: () => void;owner?:MobileOwner;petCount:number;activityCount:number;points:number;rewardFormula?:MobileBootstrap["points"]["formula"];onLogin:()=>void;onLogout:()=>void }) {
  if(!owner)return <Screen><TopHeader title="Akun" subtitle="Pet Parent Slivadoc" onNotification={onOpenNotifications}/><Card style={styles.guestCard}><View style={styles.guestRow}><View style={styles.guestAvatar}><Ionicons name="person-outline" size={25} color={colors.sky600}/></View><View style={styles.guestCopy}><Text style={styles.name}>Yuk, masuk dulu! 👋</Text><Text style={styles.meta}>Simpan profil, kesehatan, dan aktivitas pet dalam satu akun.</Text></View></View><SoftButton label="Masuk sebagai Pet Owner" icon="log-in-outline" onPress={onLogin}/></Card></Screen>;
  const initials=owner.full_name.split(" ").map(item=>item[0]).slice(0,2).join("").toUpperCase();
  return <Screen>
    <TopHeader title="Akun & Keluarga" subtitle="Profil pet parent" onNotification={onOpenNotifications} />
    <Card style={styles.profileCard}>
      <LinearGradient colors={[colors.sky500, "#68CCF7", colors.violet]} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={styles.cover}><Text style={styles.coverText}>PET PARENT CLUB ✦</Text></LinearGradient>
      <View style={styles.profileRow}><View style={styles.avatar}><Text style={styles.avatarText}>{initials}</Text></View><View style={styles.profileCopy}><Text style={styles.name}>{owner.full_name}</Text><Text style={styles.meta}>{owner.email} · sejak {new Date(owner.member_since).toLocaleDateString("id-ID",{month:"long",year:"numeric"})}</Text><Pill tone="mint">✓ AKUN AKTIF</Pill></View><Pressable onPress={() => onAction("Edit profil tersedia melalui data akun Slivadoc")} style={styles.edit}><Ionicons name="create-outline" size={16} color={colors.sky600} /></Pressable></View>
      <View style={styles.stats}><Stat value={String(petCount)} label="Hewan" /><Stat value={String(activityCount)} label="Aktivitas" /><Stat value={points.toLocaleString("id-ID")} label="Points" /><Stat value={points>0?"Member":"Regular"} label="Status" /></View>
    </Card>

    <SectionTitle eyebrow="SLIVA POINT" title="Saldo dan aturan klaim" />
    <LinearGradient colors={["#158FD5", "#4AB5EA", "#776DE1"]} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={styles.memberCard}>
      <View style={styles.memberTop}><View style={styles.shield}><Text style={{color:colors.white}}>✦</Text></View><View style={styles.memberCopy}><Text style={styles.memberName}>{points.toLocaleString("id-ID")} Sliva Points</Text><Text style={styles.memberNote}>{points?"Tersedia untuk klaim sesuai syarat":"Belum ada transaksi lunas"}</Text></View><Pill tone="mint">AKTIF</Pill></View>
      <View style={styles.benefits}>
        {(rewardFormula?.payment_methods ?? []).map(method => <Benefit key={method.method} text={method.mode==="fixed"?`${method.label}: ${method.fixed_points.toLocaleString("id-ID")} poin/transaksi`:`${method.label}: ${method.points_per_unit.toLocaleString("id-ID")} poin per Rp${method.divisor.toLocaleString("id-ID")}`} />)}
        <Benefit text={`Nilai poin Rp${(rewardFormula?.point_value_rupiah ?? 0).toLocaleString("id-ID")} · hold ${rewardFormula?.settlement_hold_days ?? 0} hari`} />
        <Benefit text="Refund otomatis membatalkan poin terkait" />
      </View>
    </LinearGradient>

    <SectionTitle eyebrow="PREFERENSI" title="Pengaturan akun" />
    <Card style={styles.settings}>
      <Setting icon="notifications-outline" title="Notifikasi" note="Kategori kesehatan, booking, order, dan keamanan" onPress={onOpenNotifications}/>
      <Setting icon="people-outline" title="Keluarga & akses" note="Kelola akses setiap pet" onPress={() => onAction("Akses keluarga dibuka")} />
      <Setting icon="shield-checkmark-outline" title="Privasi & keamanan" note="PIN, biometrik, sesi aktif" onPress={() => onAction("Keamanan akun dibuka")} />
      <Setting icon="mail-outline" title="Email login" note={owner.email} onPress={() => onAction(owner.email)} />
      <Setting icon="call-outline" title="Nomor telepon" note={owner.phone||"Belum diisi"} onPress={() => onAction(owner.phone||"Nomor belum diisi")} last />
    </Card>

    <View style={styles.footer}><Pressable onPress={() => onAction("Pusat bantuan dibuka")}><Text style={styles.footerLink}>Pusat Bantuan</Text></Pressable><Pressable onPress={() => onAction("Syarat dan privasi dibuka")}><Text style={styles.footerLink}>Syarat & Privasi</Text></Pressable><Pressable onPress={onLogout}><Text style={styles.logout}>Keluar</Text></Pressable><Text style={styles.version}>Slivadoc Pet Owner Mobile</Text></View>
  </Screen>;
}

function Stat({ value, label }: { value: string; label: string }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
function Benefit({ text }: { text: string }) { return <View style={styles.benefit}><View style={styles.benefitCheck}><Ionicons name="checkmark" size={10} color={colors.sky600} /></View><Text style={styles.benefitText}>{text}</Text></View>; }
function Setting({ icon, title, note, onPress, right, last }: { icon: keyof typeof Ionicons.glyphMap; title: string; note: string; onPress?: () => void; right?: React.ReactNode; last?: boolean }) { return <Pressable disabled={!onPress} onPress={onPress} style={[styles.setting, last && styles.noBorder]}><View style={styles.settingIcon}><Ionicons name={icon} size={19} color={colors.sky600} /></View><View style={styles.settingCopy}><Text style={styles.settingTitle}>{title}</Text><Text style={styles.settingNote}>{note}</Text></View>{right ?? <Ionicons name="chevron-forward" size={17} color="#A3AFBC" />}</Pressable>; }

const styles = StyleSheet.create({
  guestCard: { marginTop: 10, padding: 14 }, guestRow: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 12 }, guestAvatar: { width: 50, height: 50, alignItems: "center", justifyContent: "center", borderRadius: 17, backgroundColor: colors.sky50 }, guestCopy: { minWidth: 0, flex: 1 },
  profileCard: { marginTop: 8, overflow: "hidden" }, cover: { height: 68, padding: 13 }, coverText: { color: "rgba(255,255,255,.8)", fontSize: 9, fontWeight: "900", letterSpacing: 1 }, profileRow: { flexDirection: "row", alignItems: "center", marginTop: -28, paddingHorizontal: 13, paddingBottom: 12 }, avatar: { position: "relative", width: 64, height: 64, borderRadius: 21, borderWidth: 4, borderColor: colors.white, alignItems: "center", justifyContent: "center", backgroundColor: colors.sky100 }, avatarText: { color: colors.sky600, fontSize: 20, fontWeight: "900" }, camera: { position: "absolute", right: -4, bottom: -4, width: 24, height: 24, borderRadius: 8, borderWidth: 3, borderColor: colors.white, alignItems: "center", justifyContent: "center", backgroundColor: colors.sky500 }, profileCopy: { minWidth: 0, flex: 1, marginLeft: 9, paddingTop: 26, alignItems: "flex-start" }, name: { color: colors.navy, fontSize: 15, lineHeight: 20, fontWeight: "900" }, meta: { marginTop: 2, marginBottom: 5, color: colors.muted, fontSize: 9, lineHeight: 14 }, edit: { marginTop: 26, width: 32, height: 32, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: colors.sky50 }, stats: { flexDirection: "row", borderTopWidth: 1, borderTopColor: colors.line }, stat: { flex: 1, paddingVertical: 9, borderRightWidth: 1, borderRightColor: colors.line, alignItems: "center" }, statValue: { color: colors.navy, fontSize: 12, fontWeight: "900" }, statLabel: { marginTop: 2, color: colors.muted, fontSize: 8 },
  memberCard: { padding: 14, borderRadius: 18, ...shadow }, memberTop: { flexDirection: "row", alignItems: "center", gap: 8 }, shield: { width: 36, height: 36, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,255,255,.18)" }, memberCopy: { flex: 1 }, memberName: { color: colors.white, fontSize: 13, fontWeight: "900" }, memberNote: { marginTop: 2, color: "rgba(255,255,255,.75)", fontSize: 9 }, price: { marginTop: 12, color: colors.white, fontSize: 20, fontWeight: "900" }, pricePeriod: { fontSize: 10, fontWeight: "500", color: "rgba(255,255,255,.7)" }, benefits: { gap: 6, marginTop: 10 }, benefit: { flexDirection: "row", alignItems: "center", gap: 6 }, benefitCheck: { width: 17, height: 17, borderRadius: 6, alignItems: "center", justifyContent: "center", backgroundColor: colors.white }, benefitText: { flex: 1, color: "rgba(255,255,255,.9)", fontSize: 10, lineHeight: 14 }, memberButton: { minHeight: 36, flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 12, paddingHorizontal: 11, borderRadius: 11, backgroundColor: "rgba(255,255,255,.14)" }, memberButtonText: { color: colors.white, fontSize: 11, fontWeight: "800" },
  walletSection: { padding: 13 }, wallet: { flexDirection: "row", alignItems: "center", gap: 9, padding: 12, borderRadius: 13, backgroundColor: colors.sky500 }, walletIcon: { width: 37, height: 37, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,255,255,.15)" }, walletCopy: { flex: 1 }, walletLabel: { color: "rgba(255,255,255,.7)", fontSize: 11 }, walletValue: { marginTop: 3, color: colors.white, fontSize: 18, fontWeight: "900" }, payment: { minHeight: 58, flexDirection: "row", alignItems: "center", gap: 9, borderBottomWidth: 1, borderBottomColor: colors.line }, paymentLogo: { width: 38, height: 28, borderRadius: 8, borderWidth: 1, borderColor: colors.line, alignItems: "center", justifyContent: "center" }, paymentLogoText: { color: "#405D99", fontSize: 11, fontWeight: "900" }, paymentCopy: { flex: 1 }, paymentName: { color: colors.navy, fontSize: 13, fontWeight: "800" }, paymentNote: { marginTop: 3, color: colors.muted, fontSize: 11 },
  settings: { paddingHorizontal: 11 }, setting: { minHeight: 57, flexDirection: "row", alignItems: "center", gap: 9, borderBottomWidth: 1, borderBottomColor: colors.line }, noBorder: { borderBottomWidth: 0 }, settingIcon: { width: 35, height: 35, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: colors.sky50 }, settingCopy: { minWidth: 0, flex: 1 }, settingTitle: { color: colors.navy, fontSize: 12, fontWeight: "800" }, settingNote: { marginTop: 2, color: colors.muted, fontSize: 9 },
  footer: { flexDirection: "row", flexWrap: "wrap", gap: 13, marginTop: 16, paddingHorizontal: 3 }, footerLink: { color: colors.muted, fontSize: 10 }, logout: { color: colors.red, fontSize: 10 }, version: { width: "100%", color: "#A0ACB9", fontSize: 9 },
});
