import { LocalizedCopy } from "../components/LocalizedCopy";
import { LocalizedLink as Link } from "../components/LocalizedCopy";
import JsonLd from "../components/seo/JsonLd";
import { Breadcrumbs, PublicPage } from "../components/seo/PublicSite";
import { getPublicPlaces } from "../lib/public-directory";
import { absoluteUrl, pageMetadata } from "../lib/seo-config";

export const metadata=pageMetadata({title:"Direktori Pet Clinic, Petshop & Layanan Hewan",description:"Jelajahi profil mitra Slivadoc, layanan, alamat, kota, dan informasi pet care yang tersedia dari sistem mitra aktif.",path:"/places",keywords:["direktori petshop","direktori pet clinic","layanan hewan terdekat","mitra Slivadoc"]});

export default async function PlacesPage(){const places=await getPublicPlaces();const schema={"@context":"https://schema.org","@type":"ItemList",name:"Direktori mitra Slivadoc",itemListElement:places.map((place,index)=>({"@type":"ListItem",position:index+1,name:`${place.name} — ${place.branchName}`,url:absoluteUrl(`/places/${place.slug}`)}))};return <PublicPage><JsonLd data={schema}/><section className="seo-hero"><Breadcrumbs items={[{label:"Beranda",href:"/"},{label:"Direktori tempat"}]}/><div className="seo-hero-grid"><div><span className="seo-eyebrow"><LocalizedCopy>{"Direktori mitra aktif"}</LocalizedCopy></span><h1><LocalizedCopy>{"Pet clinic, petshop, dan layanan hewan dalam satu direktori"}</LocalizedCopy></h1><p><LocalizedCopy>{"Profil tempat dibentuk dari data operasional mitra Slivadoc agar informasi layanan, lokasi, serta ketersediaannya dapat ditemukan secara konsisten."}</LocalizedCopy></p><div className="seo-hero-actions"><Link className="seo-primary" href="/?view=discover"><LocalizedCopy>{"Cari dengan lokasi"}</LocalizedCopy></Link><Link className="seo-secondary" href="/partners"><LocalizedCopy>{"Daftarkan bisnis pet"}</LocalizedCopy></Link></div></div><aside className="seo-hero-panel"><strong><LocalizedCopy>{"Data yang terhubung"}</LocalizedCopy></strong><ul><li><LocalizedCopy>{"Nama bisnis dan cabang aktif"}</LocalizedCopy></li><li><LocalizedCopy>{"Alamat, kota, dan koordinat bila tersedia"}</LocalizedCopy></li><li><LocalizedCopy>{"Kategori, durasi, serta harga layanan"}</LocalizedCopy></li><li><LocalizedCopy>{"Rating dan ulasan hanya saat memiliki data valid"}</LocalizedCopy></li></ul></aside></div></section><section className="seo-main-section"><div className="seo-section-heading"><h2><LocalizedCopy>{"Tempat yang tersedia"}</LocalizedCopy></h2><p><LocalizedCopy>{"Daftar diperbarui mengikuti layanan publik mitra. Profil yang tidak aktif tidak diterbitkan dalam direktori."}</LocalizedCopy></p></div><LocalizedCopy>{places.length?<div className="seo-card-grid"><LocalizedCopy>{places.map((place)=><Link className="seo-card" key={place.slug} href={`/places/${place.slug}`}><small><LocalizedCopy>{place.city||"Indonesia"}</LocalizedCopy></small><h2><LocalizedCopy>{place.name}</LocalizedCopy></h2><p><LocalizedCopy>{place.branchName}</LocalizedCopy><LocalizedCopy>{" · "}</LocalizedCopy><LocalizedCopy>{place.address}</LocalizedCopy></p><span><LocalizedCopy>{place.services.length}</LocalizedCopy><LocalizedCopy>{" layanan tersedia →"}</LocalizedCopy></span></Link>)}</LocalizedCopy></div>:<div className="seo-empty"><h2><LocalizedCopy>{"Data mitra sedang disinkronkan"}</LocalizedCopy></h2><p><LocalizedCopy>{"Buka pencarian Slivadoc untuk melihat layanan terkini di sekitar lokasi Anda."}</LocalizedCopy></p><div className="seo-hero-actions" style={{justifyContent:"center"}}><Link className="seo-primary" href="/?view=discover"><LocalizedCopy>{"Buka pencarian"}</LocalizedCopy></Link></div></div>}</LocalizedCopy></section></PublicPage>}
