import Link from "next/link";
import JsonLd from "../components/seo/JsonLd";
import { Breadcrumbs, PublicPage } from "../components/seo/PublicSite";
import { cityPages } from "../lib/seo-content";
import { absoluteUrl, pageMetadata } from "../lib/seo-config";

export const metadata = pageMetadata({ title: "Cari Layanan Pet Care Berdasarkan Kota", description: "Jelajahi dokter hewan, pet clinic, petshop, grooming, pet hotel, dan kebutuhan anabul berdasarkan kota melalui Slivadoc.", path: "/kota", keywords: ["dokter hewan terdekat", "petshop terdekat", "pet clinic terdekat", "pet care Indonesia"] });

export default function CitiesPage(){const schema={"@context":"https://schema.org","@type":"ItemList",name:"Area layanan Slivadoc",itemListElement:cityPages.map((item,index)=>({"@type":"ListItem",position:index+1,name:item.name,url:absoluteUrl(`/kota/${item.slug}`)}))};return <PublicPage><JsonLd data={schema}/><section className="seo-hero"><Breadcrumbs items={[{label:"Beranda",href:"/"},{label:"Kota"}]}/><div className="seo-hero-grid"><div><span className="seo-eyebrow">Local pet care discovery</span><h1>Temukan layanan hewan berdasarkan kota dan area</h1><p>Mulai dari kota terdekat, lalu gunakan lokasi dan kategori di aplikasi Slivadoc untuk mempersempit pencarian layanan yang paling relevan.</p><div className="seo-hero-actions"><Link className="seo-primary" href="/?view=discover">Gunakan lokasi saya</Link><Link className="seo-secondary" href="/layanan">Lihat semua layanan</Link></div></div><aside className="seo-hero-panel"><strong>Pencarian lokal yang berguna</strong><ul><li>Halaman kota sebagai hub, bukan halaman duplikat</li><li>Area populer untuk memperjelas cakupan pencarian</li><li>Filter jarak dan kategori tersedia di aplikasi</li><li>Detail akhir mengikuti data mitra yang aktif</li></ul></aside></div></section><section className="seo-main-section"><div className="seo-section-heading"><h2>Area yang dapat dijelajahi</h2><p>Cakupan akan terus berkembang seiring hadirnya mitra pet clinic, petshop, grooming, pet hotel, dan tenaga profesional baru.</p></div><div className="seo-card-grid">{cityPages.map((item)=><Link className="seo-card" key={item.slug} href={`/kota/${item.slug}`}><small>{item.province}</small><h2>{item.name}</h2><p>{item.description}</p><span>Jelajahi area →</span></Link>)}</div></section></PublicPage>}
