import { LocalizedCopy } from "../components/LocalizedCopy";
import Link from "next/link";
import JsonLd from "../components/seo/JsonLd";
import { Breadcrumbs, PublicPage } from "../components/seo/PublicSite";
import { cityPages } from "../lib/seo-content";
import { absoluteUrl, pageMetadata } from "../lib/seo-config";

export const metadata = pageMetadata({ title: "Cari Layanan Pet Care Berdasarkan Kota", description: "Jelajahi dokter hewan, pet clinic, petshop, grooming, pet hotel, dan kebutuhan anabul berdasarkan kota melalui Slivadoc.", path: "/kota", keywords: ["dokter hewan terdekat", "petshop terdekat", "pet clinic terdekat", "pet care Indonesia"] });

export default function CitiesPage(){const schema={"@context":"https://schema.org","@type":"ItemList",name:"Area layanan Slivadoc",itemListElement:cityPages.map((item,index)=>({"@type":"ListItem",position:index+1,name:item.name,url:absoluteUrl(`/kota/${item.slug}`)}))};return <PublicPage><JsonLd data={schema}/><section className="seo-hero"><Breadcrumbs items={[{label:"Beranda",href:"/"},{label:"Kota"}]}/><div className="seo-hero-grid"><div><span className="seo-eyebrow"><LocalizedCopy>{"Local pet care discovery"}</LocalizedCopy></span><h1><LocalizedCopy>{"Temukan layanan hewan berdasarkan kota dan area"}</LocalizedCopy></h1><p><LocalizedCopy>{"Mulai dari kota terdekat, lalu gunakan lokasi dan kategori di aplikasi Slivadoc untuk mempersempit pencarian layanan yang paling relevan."}</LocalizedCopy></p><div className="seo-hero-actions"><Link className="seo-primary" href="/?view=discover"><LocalizedCopy>{"Gunakan lokasi saya"}</LocalizedCopy></Link><Link className="seo-secondary" href="/layanan"><LocalizedCopy>{"Lihat semua layanan"}</LocalizedCopy></Link></div></div><aside className="seo-hero-panel"><strong><LocalizedCopy>{"Pencarian lokal yang berguna"}</LocalizedCopy></strong><ul><li><LocalizedCopy>{"Halaman kota sebagai hub, bukan halaman duplikat"}</LocalizedCopy></li><li><LocalizedCopy>{"Area populer untuk memperjelas cakupan pencarian"}</LocalizedCopy></li><li><LocalizedCopy>{"Filter jarak dan kategori tersedia di aplikasi"}</LocalizedCopy></li><li><LocalizedCopy>{"Detail akhir mengikuti data mitra yang aktif"}</LocalizedCopy></li></ul></aside></div></section><section className="seo-main-section"><div className="seo-section-heading"><h2><LocalizedCopy>{"Area yang dapat dijelajahi"}</LocalizedCopy></h2><p><LocalizedCopy>{"Cakupan akan terus berkembang seiring hadirnya mitra pet clinic, petshop, grooming, pet hotel, dan tenaga profesional baru."}</LocalizedCopy></p></div><div className="seo-card-grid"><LocalizedCopy>{cityPages.map((item)=><Link className="seo-card" key={item.slug} href={`/kota/${item.slug}`}><small><LocalizedCopy>{item.province}</LocalizedCopy></small><h2><LocalizedCopy>{item.name}</LocalizedCopy></h2><p><LocalizedCopy>{item.description}</LocalizedCopy></p><span><LocalizedCopy>{"Jelajahi area →"}</LocalizedCopy></span></Link>)}</LocalizedCopy></div></section></PublicPage>}
