import { LocalizedCopy } from "../components/LocalizedCopy";
import { LocalizedLink as Link } from "../components/LocalizedCopy";
import JsonLd from "../components/seo/JsonLd";
import { Breadcrumbs, PublicPage } from "../components/seo/PublicSite";
import { guidePages } from "../lib/seo-content";
import { absoluteUrl, pageMetadata } from "../lib/seo-config";

export const metadata = pageMetadata({ title: "Panduan Pet Parent & Perawatan Anabul", description: "Baca panduan Slivadoc tentang kesehatan, vaksin, nutrisi, grooming, pet hotel, dan adopsi hewan yang bertanggung jawab.", path: "/guides", keywords: ["panduan anabul", "kesehatan kucing", "kesehatan anjing", "perawatan hewan"] });

export default function GuidesPage() {
  const schema = { "@context": "https://schema.org", "@type": "CollectionPage", name: "Panduan Pet Parent Slivadoc", url: absoluteUrl("/guides"), hasPart: guidePages.map((item) => ({ "@type": "Article", headline: item.title, url: absoluteUrl(`/guides/${item.slug}`) })) };
  return <PublicPage><JsonLd data={schema}/><section className="seo-hero"><Breadcrumbs items={[{ label: "Beranda", href: "/" }, { label: "Panduan" }]}/><div className="seo-hero-grid"><div><span className="seo-eyebrow"><LocalizedCopy>{"Pusat edukasi anabul"}</LocalizedCopy></span><h1><LocalizedCopy>{"Panduan yang membantu pet parent mengambil langkah berikutnya"}</LocalizedCopy></h1><p><LocalizedCopy>{"Pelajari dasar kesehatan, pencegahan, nutrisi, perawatan, penitipan, dan adopsi. Konten edukasi tidak menggantikan diagnosis atau pemeriksaan dokter hewan."}</LocalizedCopy></p></div><aside className="seo-hero-panel"><strong><LocalizedCopy>{"Prinsip konten Slivadoc"}</LocalizedCopy></strong><ul><li><LocalizedCopy>{"Bahasa yang mudah dipahami pet parent"}</LocalizedCopy></li><li><LocalizedCopy>{"Membedakan edukasi dan diagnosis medis"}</LocalizedCopy></li><li><LocalizedCopy>{"Mengutamakan keselamatan dan rujukan profesional"}</LocalizedCopy></li><li><LocalizedCopy>{"Tanggal pembaruan terlihat pada setiap panduan"}</LocalizedCopy></li></ul></aside></div></section><section className="seo-main-section"><div className="seo-card-grid"><LocalizedCopy>{guidePages.map((item)=><Link className="seo-card" key={item.slug} href={`/guides/${item.slug}`}><small><LocalizedCopy>{item.category}</LocalizedCopy><LocalizedCopy>{" · "}</LocalizedCopy><LocalizedCopy>{item.readMinutes}</LocalizedCopy><LocalizedCopy>{" menit"}</LocalizedCopy></small><h2><LocalizedCopy>{item.title}</LocalizedCopy></h2><p><LocalizedCopy>{item.description}</LocalizedCopy></p><span><LocalizedCopy>{"Baca panduan →"}</LocalizedCopy></span></Link>)}</LocalizedCopy></div></section></PublicPage>;
}
