// Curated copy shared by the web and native apps.
export const englishCopy: Record<string, string> = {
  "Beranda": "Home",
  "Belanja": "Shop",
  "Komunitas": "Community",
  "Aktivitas": "Activity",
  "Layanan": "Services",
  "Kesehatan": "Health",
  "Akun": "Account",
  "Lainnya": "More",
  "Sliva World": "Sliva World",
  "Kembali": "Back",
  "Tutup": "Close",
  "Batal": "Cancel",
  "Lanjutkan": "Continue",
  "Konfirmasi": "Confirm",
  "Selesai": "Done",
  "Semua": "All",
  "Detail": "Details",
  "Lihat detail": "View details",
  "Jelajahi": "Explore",
  "Baru": "New",
  "Aktif": "Active",
  "Memproses…": "Processing…",
  "Menyimpan…": "Saving…",
  "Mencari yang paling cocok…": "Finding the best match…",
  "Data terbaru sudah dimuat": "Latest data loaded",
  "Sebagian data berhasil diperbarui": "Some data was updated",
  "Data belum dapat diperbarui": "Data could not be updated",
  "Buka notifikasi": "Open notifications",
  "Buka halaman terkait": "Open related page",
  "Kembali ke halaman sebelumnya": "Go back to the previous page",
  "Tutup panel": "Close panel",
  "Fitur lainnya": "More features",
  "Belum ada": "Not available yet",
  "Belum diisi": "Not provided",
  "Tidak": "No",
  "Ya": "Yes",
  "Masuk": "Sign in",
  "Daftar": "Register",
  "Masuk ke Slivadoc": "Sign in to Slivadoc",
  "Senang melihatmu kembali": "Great to see you again",
  "Mulai perjalanan pet parent": "Start your pet parent journey",
  "Nama lengkap": "Full name",
  "Email": "Email",
  "Password": "Password",
  "WhatsApp": "WhatsApp",
  "Kode OTP": "OTP code",
  "Minimal 8 karakter": "At least 8 characters",
  "Nama sesuai identitas": "Name as shown on your ID",
  "Gunakan kombinasi huruf, angka, dan simbol.": "Use a combination of letters, numbers, and symbols.",
  "Harus diawali angka 0, tanpa spasi atau simbol.": "Must start with 0, without spaces or symbols.",
  "Saya menyetujui": "I agree to the",
  "Syarat dan Ketentuan": "Terms and Conditions",
  "Kebijakan Privasi": "Privacy Policy",
  "Daftar & kirim OTP": "Register & send OTP",
  "Verifikasi email kamu": "Verify your email",
  "Masukkan 6 digit OTP yang dikirim ke": "Enter the 6-digit OTP sent to",
  "Kirim ulang OTP": "Resend OTP",
  "Verifikasi & aktifkan akun": "Verify & activate account",
  "Login berhasil": "Signed in successfully",
  "Login gagal": "Sign-in failed",
  "Registrasi gagal": "Registration failed",
  "OTP tidak valid": "Invalid OTP",
  "OTP belum terkirim": "OTP has not been sent",
  "Login diperlukan untuk fitur akun": "Sign in to use account features",
  "Menyiapkan Slivadoc": "Preparing Slivadoc",
  "Menyinkronkan profil pet, marketplace, dan aktivitas Anda.": "Syncing your pet profile, marketplace, and activity.",
  "UPDATE TERBARU": "LATEST UPDATES",
  "Notifikasi": "Notifications",
  "Belum ada update": "No updates yet",
  "Tandai dibaca": "Mark as read",
  "Sudah dibaca": "Read",
  "belum dibaca": "unread",
  "Kembali ke semua update": "Back to all updates",
  "Detail notifikasi": "Notification details",
  "Notifikasi pada kategori ini akan muncul di sini.": "Notifications in this category will appear here.",
  "Update ini tersimpan di pusat notifikasi akunmu dan dapat dibuka lagi kapan saja.": "This update is saved in your notification center and can be reopened anytime.",
  "Notifikasi belum dapat dibuka": "Notifications could not be opened",
  "Menandai dibaca…": "Marking as read…",
  "Booking": "Booking",
  "BOOKING LAYANAN": "SERVICE BOOKING",
  "Layanan yang dipilih": "Selected service",
  "Pilih hewan": "Choose a pet",
  "Pilih tanggal": "Choose a date",
  "Pilih waktu": "Choose a time",
  "Catatan khusus": "Special notes",
  "Ceritakan keluhan atau hal penting...": "Describe any symptoms or important details…",
  "Konfirmasi booking": "Confirm booking",
  "Lanjut bayar": "Continue to payment",
  "Tersedia untuk booking": "Available to book",
  "TERSEDIA UNTUK BOOKING": "AVAILABLE TO BOOK",
  "Total pembayaran": "Total payment",
  "Booking atau pembayaran belum dapat dibuat": "The booking or payment could not be created",
  "Pembayaran berhasil, booking sudah dikonfirmasi": "Payment successful, booking confirmed",
  "Hai, Pet Parent!": "Hi, Pet Parent!",
  "Semua kebutuhan pet jadi lebih gampang.": "Everything your pet needs, made easier.",
  "Cari apa saja di Slivadoc": "Search anything on Slivadoc",
  "Cari dokter, layanan, produk…": "Search vets, services, products…",
  "Cari fitur, dokter, layanan, produk, tempat, event, dan academy dalam satu pencarian.": "Find features, vets, services, products, places, events, and academy in one search.",
  "Lagi cari apa hari ini?": "What are you looking for today?",
  "PENCARIAN POPULER": "POPULAR SEARCHES",
  "HASIL DITEMUKAN": "RESULTS FOUND",
  "Pencarian belum tersambung": "Search is not connected yet",
  "Coba lagi sebentar atau gunakan fitur populer.": "Try again shortly or use a popular feature.",
  "Belum ada yang cocok": "No matches yet",
  "Coba kata kunci atau kategori lain.": "Try another keyword or category.",
  "DAILY PET MOMENT": "DAILY PET MOMENT",
  "IDE HARI INI": "TODAY'S IDEA",
  "10 menit quality time": "10 minutes of quality time",
  "Bikin hari mereka lebih happy.": "Make their day a little happier.",
  "Mulai dari momen kecil untuk": "Start with a small moment for",
  "yang lebih sehat dan ceria.": "a healthier, happier life.",
  "Layanan cepat": "Quick services",
  "Semua yang pet-mu butuhkan, sekali tap": "Everything your pet needs, in one tap",
  "6 pilihan": "6 options",
  "Atur jadwal klinik": "Schedule a clinic visit",
  "Tanya Dokter": "Ask a Vet",
  "Konsultasi kesehatan hewan": "Pet health consultation",
  "Home Care": "Home Care",
  "Ke rumah": "At home",
  "Darurat": "Emergency",
  "24 jam": "24 hours",
  "Pet Hotel": "Pet Hotel",
  "Terpercaya": "Trusted",
  "Eksplorasi": "Explore",
  "HEALTH SNAPSHOT": "HEALTH SNAPSHOT",
  "Pantau kesehatan tanpa ribet": "Effortless health monitoring",
  "PET AKTIF": "ACTIVE PET",
  "Dibagikan": "Shared",
  "Pilih profil hewan": "Choose a pet profile",
  "Ganti": "Change",
  "Login untuk melihat profil": "Sign in to view the profile",
  "Belum ada rekam medis": "No medical records yet",
  "Berat badan": "Weight",
  "Health score": "Health score",
  "Insight untuk": "Insights for",
  "Belum ada aktivitas kesehatan terjadwal.": "No scheduled health activities yet.",
  "CARE PLAN": "CARE PLAN",
  "Perawatan terdekat": "Upcoming care",
  "Biar jadwal nggak kelewat": "Stay on top of every schedule",
  "Jadwal masih santai": "No upcoming schedule",
  "Booking perawatan pertama dan kami bantu ingatkan.": "Book the first care session and we'll help remind you.",
  "Lihat semua aktivitas": "View all activity",
  "REKOMENDASI": "RECOMMENDED",
  "Pilihan untuk pet kamu": "Picks for your pet",
  "Favorit pet parent di sekitarmu": "Favorites from nearby pet parents",
  "SLIVA MARKET": "SLIVA MARKET",
  "Belanja kebutuhan pet": "Shop pet essentials",
  "Cari produk atau toko": "Search products or stores",
  "Cari makanan, vitamin, atau toko": "Search food, vitamins, or stores",
  "BELANJA AMAN": "SHOP SAFELY",
  "Satu keranjang,": "One cart,",
  "banyak toko pet.": "many pet stores.",
  "Produk petshop dan klinik terhubung langsung dengan stok asli.": "Pet store and clinic products are connected to live stock.",
  "TOKO TERHUBUNG": "CONNECTED STORES",
  "Belanja dari petshop favorit": "Shop from favorite pet stores",
  "Semua toko": "All stores",
  "Lihat semuanya": "View all",
  "Toko resmi": "Official store",
  "PILIHAN BUAT PET-MU": "PICKS FOR YOUR PET",
  "Rekomendasi": "Recommended",
  "Terlaris": "Best sellers",
  "Rating": "Rating",
  "Harga termurah": "Lowest price",
  "Stok habis": "Out of stock",
  "terjual": "sold",
  "Keranjang": "Add to cart",
  "+ Keranjang": "+ Cart",
  "Tambah": "Add",
  "produk ditemukan": "products found",
  "toko": "stores",
  "Produk belum ditemukan": "No products found",
  "Coba kata kunci, kategori, atau toko lain.": "Try another keyword, category, or store.",
  "Reset pencarian": "Reset search",
  "Mengambil stok terbaru…": "Loading latest stock…",
  "DETAIL PRODUK": "PRODUCT DETAILS",
  "Tentang produk": "About this product",
  "Stok": "Stock",
  "Terverifikasi": "Verified",
  "Pembelian valid": "Verified purchase",
  "Ulasan & komentar": "Reviews & comments",
  "Ulasan jujur membantu pet parent lain memilih.": "Honest reviews help other pet parents choose.",
  "Belum ada ulasan": "No reviews yet",
  "Jadi reviewer pertama": "Be the first reviewer",
  "Bagaimana produknya?": "How was the product?",
  "Hanya pembeli terverifikasi yang dapat menulis ulasan.": "Only verified buyers can write a review.",
  "Ceritakan kualitas, kemasan, dan pengalaman pet-mu…": "Share the quality, packaging, and your pet's experience…",
  "Kirim ulasan": "Submit review",
  "Beli sekarang": "Buy now",
  "Keranjang masih kosong": "Your cart is empty",
  "Tambahkan produk favorit pet-mu dulu, ya.": "Add your pet's favorite products first.",
  "Mulai belanja": "Start shopping",
  "CHECKOUT AMAN": "SECURE CHECKOUT",
  "Harga dan stok dikonfirmasi ulang oleh Slivadoc saat checkout.": "Slivadoc reconfirms price and stock at checkout.",
  "Provinsi": "Province",
  "Pilih provinsi": "Select province",
  "Cari provinsi": "Search provinces",
  "Kabupaten / Kota": "Regency / City",
  "Pilih kabupaten atau kota": "Select regency or city",
  "Cari kabupaten atau kota": "Search regencies or cities",
  "Kecamatan": "District",
  "Pilih kecamatan": "Select district",
  "Cari kecamatan": "Search districts",
  "Kelurahan / Desa": "Urban Village / Village",
  "Pilih kelurahan atau desa": "Select urban village or village",
  "Cari kelurahan atau desa": "Search urban villages or villages",
  "Cari nama atau kode wilayah": "Search by region name or code",
  "Tutup pilihan wilayah": "Close region picker",
  "PILIH WILAYAH": "SELECT REGION",
  "Memuat daftar wilayah…": "Loading regions…",
  "Mohon tunggu sebentar.": "Please wait a moment.",
  "Daftar wilayah belum dapat dimuat": "The region list could not be loaded",
  "Wilayah belum dapat dimuat": "Regions could not be loaded",
  "Coba muat ulang wilayah": "Retry loading regions",
  "Coba lagi": "Try again",
  "Wilayah tidak ditemukan": "No regions found",
  "Belum ada pilihan wilayah": "No regions available yet",
  "Coba gunakan nama atau kode wilayah lain.": "Try another region name or code.",
  "Daftar wilayah akan muncul di sini.": "Available regions will appear here.",
  "Kode": "Code",
  "Nama jalan, nomor rumah, RT/RW, dan patokan": "Street name, house number, RT/RW, and landmark",
  "Tujuan pengiriman": "Shipping destination",
  "WAJIB": "REQUIRED",
  "Kode pos *": "Postal code *",
  "5 digit kode pos": "5-digit postal code",
  "Origin otomatis mengikuti cabang petshop atau petclinic pengirim. Lengkapi tujuan untuk menghitung ongkir.": "The dispatch origin is automatically set to the sending pet store or clinic branch. Complete the destination to calculate shipping.",
  "Menghitung ongkir otomatis…": "Calculating shipping automatically…",
  "Rute dihitung dari setiap origin pengirim.": "Routes are calculated from each dispatch origin.",
  "Ongkir belum dapat dihitung": "Shipping could not be calculated",
  "Coba hitung ulang ongkir": "Retry shipping calculation",
  "Isi data penerima, alamat, seluruh wilayah tujuan, dan kode pos. Ongkir akan dihitung otomatis.": "Enter the recipient details, address, all destination regions, and postal code. Shipping will be calculated automatically.",
  "Ongkir terbaru sudah dihitung otomatis.": "The latest shipping cost was calculated automatically.",
  "DIKIRIM OTOMATIS DARI": "AUTOMATICALLY SHIPPED FROM",
  "Menghitung ongkir…": "Calculating shipping…",
  "Lengkapi alamat tujuan": "Complete destination address",
  "Ongkir belum siap": "Shipping not ready",
  "Lengkapi seluruh alamat tujuan pengiriman terlebih dahulu": "Complete the full delivery address first",
  "Salah satu origin pengiriman belum memiliki layanan yang tersedia": "No shipping service is available for one of the dispatch origins",
  "Lengkapi tujuan dan tunggu ongkir selesai dihitung": "Complete the destination and wait for shipping to be calculated",
  "Voucher Slivadoc": "Slivadoc voucher",
  "Tukar Sliva Points": "Redeem Sliva Points",
  "Pakai": "Apply",
  "Subtotal": "Subtotal",
  "Biaya platform": "Platform fee",
  "Diskon voucher": "Voucher discount",
  "Bayar pesanan": "Pay for order",
  "Menyiapkan pembayaran…": "Preparing payment…",
  "Pembayaran berhasil, pesanan sedang disiapkan toko": "Payment successful, the store is preparing your order",
  "Hapus dari favorit": "Remove from favorites",
  "Tambah ke favorit": "Add to favorites",
  "Tambah jumlah": "Increase quantity",
  "Kurangi jumlah": "Decrease quantity",
  "Jelajahi Layanan": "Explore Services",
  "Layanan pet care terverifikasi": "Verified pet care services",
  "Mau manjain pet-mu dengan apa? ✨": "How would you like to pamper your pet? ✨",
  "Temukan layanan terverifikasi di dekatmu.": "Find verified services near you.",
  "Cari klinik atau layanan": "Search clinics or services",
  "Belum ditemukan": "Nothing found",
  "Coba gunakan kategori atau kata kunci lain.": "Try another category or keyword.",
  "Estimasi harga": "Estimated price",
  "Pet friendly": "Pet friendly",
  "✓ Terverifikasi": "✓ Verified",
  "PUSAT AKTIVITAS": "ACTIVITY CENTER",
  "Semua perjalanan pet-mu": "Your pet's complete journey",
  "Pantau transaksi dan ulangi aktivitas dalam sekali tap.": "Track transactions and repeat activities in one tap.",
  "Mau melakukan apa?": "What would you like to do?",
  "AKTIVITAS BARU": "NEW ACTIVITY",
  "Buat baru": "Create new",
  "Booking layanan": "Book a service",
  "Pilih layanan dari seluruh klinik dan petshop": "Choose from all clinics and pet stores",
  "Belanja produk": "Shop products",
  "Cari kebutuhan pet dari marketplace Slivadoc": "Find pet essentials in Slivadoc Marketplace",
  "Konsultasi dokter": "Vet consultation",
  "Pilih dokter dan paket konsultasi yang sesuai": "Choose the right vet and consultation plan",
  "Mendatang": "Upcoming",
  "Sedang berlangsung": "Ongoing",
  "Riwayat": "History",
  "Mengambil aktivitas terbaru…": "Loading latest activity…",
  "Belum ada aktivitas": "No activity yet",
  "Filter ini masih kosong. Mulai aktivitas baru dan progresnya akan tampil otomatis di sini.": "This filter is empty. Start a new activity and its progress will appear here automatically.",
  "Booking lagi": "Book again",
  "Beli lagi": "Buy again",
  "Batalkan booking": "Cancel booking",
  "Pembatalan": "Cancellation",
  "Lengkapi dokumen": "Complete documents",
  "Kirim ulang dokumen": "Resubmit documents",
  "Pilih foto": "Choose photo",
  "Informasi layanan jemput": "Pickup service information",
  "Jemput": "Pickup",
  "Tujuan": "Destination",
  "Driver": "Driver",
  "Konsultasi ulang": "Consult again",
  "Informasi booking": "Booking information",
  "Informasi konsultasi": "Consultation information",
  "Produk dalam pesanan": "Products in this order",
  "Status pembayaran": "Payment status",
  "Dibuat": "Created",
  "Jadwal": "Schedule",
  "Pet": "Pet",
  "Klinik / petshop": "Clinic / pet store",
  "Lokasi": "Location",
  "Catatan": "Notes",
  "Dokter hewan": "Veterinarian",
  "Paket & mode": "Plan & mode",
  "Keluhan": "Concern",
  "Diagnosis": "Diagnosis",
  "Catatan dokter": "Vet notes",
  "Durasi": "Duration",
  "Menunggu pembayaran": "Awaiting payment",
  "Menunggu konfirmasi": "Awaiting confirmation",
  "Terkonfirmasi": "Confirmed",
  "Terjadwal": "Scheduled",
  "Berjalan": "In progress",
  "Diproses": "Processing",
  "Dikirim": "Shipped",
  "Dibatalkan": "Cancelled",
  "Tidak hadir": "No show",
  "Belum dijadwalkan": "Not scheduled",
  "Belum ada diagnosis": "No diagnosis yet",
  "Belum ada catatan dokter": "No vet notes yet",
  "Tidak ada catatan tambahan": "No additional notes",
  "Perlu tindakan": "Needs action",
  "Bayar": "Pay",
  "Bayar sekarang": "Pay now",
  "Membuka pembayaran…": "Opening payment…",
  "Pembayaran belum dapat dibuka": "Payment could not be opened",
  "Tiket QR": "QR ticket",
  "Lihat di Aktivitas": "View in Activity",
  "Dokumen perlu dilengkapi": "Document needs more information",
  "Aktivitas belum tersedia. Coba lagi sebentar.": "Activity is not available yet. Try again shortly.",
  "Tunjukkan QR ini ke petugas saat check-in.": "Show this QR code to staff at check-in.",
  "Petunjuk arah": "Directions",
  "Kelas": "Class",
  "Reservasi": "Reservation",
  "Donasi": "Donation",
  "KELAS": "CLASS",
  "EVENT": "EVENT",
  "RESERVASI": "RESERVATION",
  "DOKUMEN": "DOCUMENT",
  "DONASI": "DONATION",
  "PET HOTEL": "PET HOTEL",
  "Sudah check-in": "Checked in",
  "Belum check-in": "Not checked in yet",
  "Terbit": "Issued",
  "Diverifikasi": "Verified",
  "Perlu revisi": "Needs revision",
  "Diajukan": "Submitted",
  "Draf": "Draft",
  "Ditolak": "Rejected",
  "Dikembalikan": "Returned",
  "Lunas": "Paid",
  "Gagal": "Failed",
  "Kedaluwarsa": "Expired",
  "Dana dikembalikan": "Refunded",
  "Informasi kelas": "Class information",
  "Informasi event": "Event information",
  "Informasi reservasi": "Reservation information",
  "Informasi dokumen": "Document information",
  "Informasi donasi": "Donation information",
  "Informasi pet hotel": "Pet hotel information",
  "Program": "Program",
  "Trainer": "Trainer",
  "Sesi berikutnya": "Next session",
  "Progres": "Progress",
  "Peserta": "Participant",
  "Waktu": "Time",
  "Tiket": "Tickets",
  "Check-in": "Check-in",
  "Check-out": "Check-out",
  "Tempat": "Place",
  "Tamu": "Guests",
  "DP": "Deposit",
  "Sisa dibayar di lokasi": "Balance paid on site",
  "Rute": "Route",
  "Keberangkatan": "Departure",
  "Persyaratan kurang": "Missing requirements",
  "Buka dokumen terbit": "Open issued document",
  "Campaign": "Campaign",
  "Penerima": "Beneficiary",
  "Pesan": "Message",
  "Anonim": "Anonymous",
  "Dibayar": "Paid on",
  "Kamar": "Room",
  "Klinik": "Clinic",
  "Pusat Kesehatan": "Health Center",
  "Digital health record": "Digital health record",
  "HEALTH PROFILE ✦": "HEALTH PROFILE ✦",
  "Alergi": "Allergies",
  "Dokter terbaru": "Latest vet",
  "Update": "Updated",
  "RINGKASAN KESEHATAN": "HEALTH SUMMARY",
  "Ringkasan": "Summary",
  "Rekam Medis": "Medical Records",
  "RECORD TERBARU": "LATEST RECORD",
  "Memuat rekam medis…": "Loading medical records…",
  "Dokter belum dicatat": "Vet not recorded",
  "Tidak ada keterangan tambahan": "No additional information",
  "Rekam medis tersinkron": "Medical records synced",
  "Dihitung dari data pet pada server": "Calculated from pet data on the server",
  "Buat booking pemeriksaan untuk memulai record": "Book an examination to start a record",
  "SLIVADOC COMMUNITY": "SLIVADOC COMMUNITY",
  "Pet Parent Indonesia": "Indonesian Pet Parents",
  "Komunitas pet parent aktif": "An active pet parent community",
  "Untuk Kamu": "For You",
  "Mengikuti": "Following",
  "Grup": "Groups",
  "Posting baru": "New post",
  "Memuat posting terbaru…": "Loading latest posts…",
  "Belum ada posting pada filter ini.": "No posts in this filter yet.",
  "Apa yang ingin kamu bagikan tentang hewanmu?": "What would you like to share about your pet?",
  "Tambah foto": "Add photo",
  "Ganti foto": "Change photo",
  "Upload aman": "Secure upload",
  "Terbitkan posting": "Publish post",
  "Mengunggah & menerbitkan...": "Uploading & publishing…",
  "Komentar": "Comments",
  "Tulis komentar...": "Write a comment…",
  "Masuk untuk membuat posting dan komentar": "Sign in to create posts and comments",
  "Buat grup": "Create group",
  "Temukan grup": "Discover groups",
  "Chat saya": "My chats",
  "Buat grup sendiri atau temukan komunitas yang cocok.": "Create your own group or discover the right community.",
  "Cari nama atau topik grup": "Search group names or topics",
  "Grup belum ditemukan": "No groups found",
  "Coba kata pencarian lain atau buat grup baru.": "Try another search or create a new group.",
  "Gabung": "Join",
  "Perlu persetujuan": "Approval required",
  "Publik": "Public",
  "Kamu admin": "You're an admin",
  "Akses grup": "Group access",
  "Buat grup kamu": "Create your group",
  "KOMUNITAS BARU": "NEW COMMUNITY",
  "Nama grup": "Group name",
  "Deskripsi": "Description",
  "Kota (opsional)": "City (optional)",
  "Topik dan tujuan grup ini…": "This group's topic and purpose…",
  "Membuat grup…": "Creating group…",
  "Obrolan grup": "Group chat",
  "Chat grup khusus member": "Members-only group chat",
  "Chat grup tidak menyediakan telepon atau video call.": "Group chat does not support voice or video calls.",
  "Mulai percakapan": "Start the conversation",
  "Sapa member grup dengan pesan pertama yang ramah.": "Welcome the group with a friendly first message.",
  "Percakapan tersimpan aman di Slivadoc. Jangan bagikan data kontak pribadi.": "Chats are stored securely on Slivadoc. Do not share private contact details.",
  "Mode lihat saja — tambahkan pet untuk membalas": "View-only mode — add a pet to reply",
  "PETHUB CREATOR": "PETHUB CREATOR",
  "PetHub": "PetHub",
  "Cerita nyata dari pet parent": "Real stories from pet parents",
  "Feed": "Feed",
  "Reels": "Reels",
  "Story kamu": "Your story",
  "Buat story": "Create story",
  "Buat posting": "Create post",
  "Reel baru": "New reel",
  "Story baru": "New story",
  "Feed masih sepi": "The feed is quiet",
  "Jadi pet parent pertama yang berbagi momen di sini.": "Be the first pet parent to share a moment here.",
  "Belum ada reels": "No reels yet",
  "Pilih foto atau video": "Choose a photo or video",
  "Upload video": "Upload video",
  "Tulis caption yang seru…": "Write a fun caption…",
  "Tambah caption (opsional)…": "Add a caption (optional)…",
  "Media akan disimpan aman di akun Slivadoc": "Media will be stored securely in your Slivadoc account",
  "Terbitkan": "Publish",
  "Mengunggah media…": "Uploading media…",
  "Belum ada komentar. Mulai obrolan yang baik.": "No comments yet. Start a friendly conversation.",
  "Tambahkan komentar…": "Add a comment…",
  "Login untuk berkomentar": "Sign in to comment",
  "Tambah pet untuk berkomentar": "Add a pet to comment",
  "Seluruh dunia pet dalam satu aplikasi": "The entire pet world in one app",
  "Satu layar untuk dunia pet.": "One screen for the pet world.",
  "Pilihan untukmu": "Picked for you",
  "Academy": "Academy",
  "Adopsi": "Adoption",
  "Event": "Events",
  "PetSpot": "PetSpot",
  "PAW Dating": "PAW Dating",
  "Dokumen": "Documents",
  "Konsultasi": "Consultation",
  "Trainer terverifikasi, kurikulum terukur, dan progres digital.": "Verified trainers, structured curricula, and digital progress.",
  "Festival, workshop, meet-up, dan fun race pilihan.": "Curated festivals, workshops, meet-ups, and fun races.",
  "Cafe, mall, taman, dan playground yang pet friendly.": "Pet-friendly cafés, malls, parks, and playgrounds.",
  "Dokter sedekat layar kamu.": "A vet as close as your screen.",
  "Chat, voice, video call, bundling, dan medical record.": "Chat, voice, video calls, bundles, and medical records.",
  "Rumah baru. Awal baru.": "A new home. A new beginning.",
  "Screening, health check, meet & greet, dan pendampingan.": "Screening, health checks, meet & greets, and guidance.",
  "Urus dokumen tanpa bingung.": "Handle documents without the hassle.",
  "Akte, surat sehat, karantina, pesawat, dan kapal.": "Certificates, health letters, quarantine, flights, and ships.",
  "Belajar dan bertumbuh bersama.": "Learn and grow together.",
  "Isi kalender pet-mu.": "Fill your pet's calendar.",
  "Di sekitar kamu": "Near you",
  "VIRTUAL VET": "VIRTUAL VET",
  "Mulai konsultasi": "Start consultation",
  "Tonton live": "Watch live",
  "Ambil tiket": "Get tickets",
  "Buka petunjuk arah": "Open directions",
  "Ajukan dokumen": "Request document",
  "Memuat informasi terbaru…": "Loading the latest information…",
  "Belum ada data pada kategori ini.": "No data in this category yet.",
  "Nama calon adopter": "Prospective adopter's name",
  "Nomor untuk verifikasi": "Verification phone number",
  "Alamat tempat tinggal": "Home address",
  "Tipe hunian": "Housing type",
  "Pengalaman merawat pet (opsional)": "Pet care experience (optional)",
  "Memiliki pet lain?": "Do you have other pets?",
  "Ceritakan alasan dan kesiapanmu": "Tell us your reason and readiness",
  "Kirim pengajuan screening": "Submit screening request",
  "Kota asal": "Origin city",
  "Kota / negara tujuan": "Destination city / country",
  "Jadwal keberangkatan": "Departure schedule",
  "Transportasi": "Transport",
  "Pesawat": "Airplane",
  "Kapal": "Ship",
  "Dokumen yang perlu disiapkan": "Documents to prepare",
  "Akun & Keluarga": "Account & Family",
  "Profil pet parent": "Pet parent profile",
  "Yuk, masuk dulu!": "Let's sign in!",
  "Simpan profil, kesehatan, dan aktivitas pet dalam satu akun.": "Keep your pet's profile, health, and activity in one account.",
  "Masuk sebagai Pet Owner": "Sign in as Pet Owner",
  "Pengaturan akun": "Account settings",
  "PREFERENSI": "PREFERENCES",
  "Bahasa aplikasi": "App language",
  "Pilih bahasa yang nyaman untuk seluruh aplikasi": "Choose your preferred language for the entire app",
  "PILIH BAHASA": "CHOOSE LANGUAGE",
  "Bahasa berhasil diubah": "Language updated",
  "Bahasa Indonesia": "Indonesian",
  "Bahasa Inggris": "English",
  "Bahasa Mandarin": "Chinese",
  "Buka daftar, status baca, dan detail update": "Open the list, read status, and update details",
  "Keluarga & akses": "Family & access",
  "Undang anggota dan atur izin setiap pet": "Invite members and manage each pet's permissions",
  "Privasi & keamanan": "Privacy & security",
  "Verifikasi, privasi data, dan sesi perangkat": "Verification, data privacy, and device sessions",
  "Email login": "Login email",
  "Nomor telepon": "Phone number",
  "Belum verifikasi": "Not verified",
  "BANTUAN": "HELP",
  "Ada yang bisa kami bantu?": "How can we help?",
  "Chat Customer Support": "Chat Customer Support",
  "Hubungi tim Slivadoc langsung dari aplikasi.": "Contact the Slivadoc team directly from the app.",
  "Keluar dari akun": "Sign out",
  "Akhiri sesi hanya di perangkat ini.": "End the session on this device only.",
  "Keluar dari akun?": "Sign out?",
  "Tetap masuk": "Stay signed in",
  "Ya, keluar": "Yes, sign out",
  "KONFIRMASI KELUAR": "CONFIRM SIGN OUT",
  "Rawat bareng, tetap terkontrol": "Care together, stay in control",
  "Pilih pet, undang orang terpercaya, lalu tentukan data yang boleh mereka akses.": "Choose a pet, invite someone you trust, then choose what they can access.",
  "Akses berlaku untuk": "Access applies to",
  "Tambahkan pet lebih dulu": "Add a pet first",
  "Belum ada anggota": "No members yet",
  "Atur akses baru": "Set up new access",
  "Nama anggota keluarga": "Family member's name",
  "Peran": "Role",
  "Izin akses": "Access permissions",
  "Profil pet": "Pet profile",
  "Identitas dan data dasar": "Identity and basic information",
  "Data kesehatan": "Health data",
  "Rekam medis dan kondisi": "Medical records and conditions",
  "Jadwal dan perawatan": "Schedules and care",
  "Kirim undangan": "Send invitation",
  "Memuat akses keluarga…": "Loading family access…",
  "Status verifikasi": "Verification status",
  "Akunmu terlindungi ✨": "Your account is protected ✨",
  "Tinggal sedikit lagi": "Almost there",
  "Kontak login dan pemulihan akun sudah terverifikasi.": "Your login and recovery contacts are verified.",
  "Verifikasi kontak yang belum aktif agar pemulihan akun lebih aman.": "Verify inactive contacts for safer account recovery.",
  "Data di perangkat ini": "Data on this device",
  "Samarkan data sensitif": "Mask sensitive data",
  "Sembunyikan sebagian email dan nomor di halaman ini.": "Hide parts of your email and phone number on this page.",
  "Pantau akun": "Monitor account",
  "Perangkat saat ini": "Current device",
  "Sesi ini · aktif sekarang": "This session · active now",
  "Data dan profil pet kamu tetap aman.": "Your data and pet profiles remain safe.",
  "Sliva Points": "Sliva Points",
  "Saldo dan aturan klaim": "Balance and redemption rules",
  "Tersedia untuk klaim sesuai syarat": "Available to redeem under the terms",
  "Belum ada transaksi lunas": "No completed transactions yet",
  "Refund otomatis membatalkan poin terkait": "Refunds automatically reverse related points",
  "Mode lihat saja": "View-only mode",
  "Tambahkan profil pet untuk bertransaksi dan ikut berinteraksi.": "Add a pet profile to transact and interact.",
  "Tambah pet": "Add pet",
  "AI Assistant": "AI Assistant",
  "SlivaCare Assistant": "SlivaCare Assistant",
  "Customer Support": "Customer Support",
  "PUSAT BANTUAN": "HELP CENTER",
  "Masalah akun": "Account issue",
  "Booking & pembayaran": "Bookings & payments",
  "Konsultasi gejala": "Symptom consultation",
  "Tanya seputar hewan...": "Ask about pets…",
  "Tulis kendalamu...": "Describe your issue…",
  "Pesan ke care team...": "Message the care team…",
  "Kirim pesan": "Send message",
  "Menghubungkan...": "Connecting…",
  "Realtime • terhubung": "Realtime • connected",
  "Metode pembayaran": "Payment method",
  "Memuat metode pembayaran…": "Loading payment methods…",
  "Metode pembayaran belum tersedia": "Payment methods are not available yet",
  "Pembayaran QRIS sementara belum tersedia. Coba lagi.": "QRIS payment is temporarily unavailable. Please try again.",
  "Tunggu hingga pembayaran QRIS tersedia.": "Please wait until QRIS payment is available.",
  "Bayar dengan aplikasi pilihan Anda": "Pay with your preferred payment app",
  "Sesi Anda berakhir. Silakan login kembali.": "Your session has expired. Please sign in again.",
  "Scan QR untuk membayar": "Scan the QR code to pay",
  "Pembayaran berhasil": "Payment successful",
  "Transaksi sudah tercatat dan layanan sedang diproses.": "The transaction is recorded and the service is being processed.",
  "Pembayaran gagal atau kedaluwarsa": "Payment failed or expired",
  "Pembayaran sudah direfund": "Payment has been refunded",
  "· berlaku 15 menit": "· valid for 15 minutes",
  "● LIVE": "● LIVE",
  "✓ AKUN AKTIF": "✓ ACTIVE ACCOUNT",
  "✦ LEVEL": "✦ LEVEL",
  "a.n.": "Account holder",
  "akan tampil di sini.": "will appear here.",
  "Akses keluarga selalu diatur terpisah untuk setiap pet.": "Family access is managed separately for each pet.",
  "AKTIF": "ACTIVE",
  "aktivitas": "activities",
  "AKTIVITAS KEAMANAN": "SECURITY ACTIVITY",
  "AKUN & KELUARGA": "ACCOUNT & FAMILY",
  "Alamat lengkap": "Full address",
  "Aplikasi Slivadoc Mobile": "Slivadoc Mobile App",
  "Bagikan posting": "Share post",
  "Buat": "Create",
  "Buat aktivitas baru": "Create new activity",
  "Buka komentar": "Open comments",
  "Buka riwayat update dan lihat detail aktivitas.": "Open update history and view activity details.",
  "CABUT AKSES": "REVOKE ACCESS",
  "Cari di seluruh Slivadoc": "Search all of Slivadoc",
  "catatan": "notes",
  "Ceritakan kendalanya secara detail. Tim support akan membantu akun, booking, pembayaran, dan penggunaan aplikasi.": "Describe the issue in detail. Support can help with your account, bookings, payments, and app usage.",
  "Chat customer support": "Chat with customer support",
  "Chat santai bersama pet parent. Tanpa telepon dan video call.": "Chat with fellow pet parents. No voice or video calls.",
  "Contoh: Corgi Jakarta": "Example: Jakarta Corgi",
  "Contoh: Denpasar": "Example: Denpasar",
  "Contoh: Jakarta": "Example: Jakarta",
  "Contoh: PETHEMAT": "Example: PETSAVE",
  "DATA AKUNMU": "YOUR ACCOUNT DATA",
  "Data kontak hanya dipakai untuk verifikasi privat dan tidak ditampilkan pada posting publik.": "Contact details are used only for private verification and are never shown in public posts.",
  "Data permohonan": "Application details",
  "DETAIL": "DETAILS",
  "ditemukan": "found",
  "Diterima": "Received",
  "Edit profil": "Edit profile",
  "Hapus pencarian": "Clear search",
  "Health": "Health",
  "Hewan": "Pets",
  "IDENTITAS LOGIN": "LOGIN IDENTITY",
  "Info grup": "Group info",
  "item": "items",
  "Kamu bisa masuk kembali kapan saja.": "You can sign in again anytime.",
  "Kategori": "Category",
  "Keluar akan menghapus token login aman hanya dari perangkat ini. Data akun dan profil pet tetap tersimpan.": "Signing out removes the secure login token only from this device. Your account and pet profiles stay saved.",
  "Keluar dari perangkat ini": "Sign out of this device",
  "Kembali ke beranda": "Back to home",
  "komentar": "comments",
  "Komentar produk": "Product reviews",
  "Komunitas seru": "Fun communities",
  "KONTROL PRIVASI": "PRIVACY CONTROLS",
  "layanan": "services",
  "Lihat": "View",
  "Masuk ke akun": "Sign in",
  "Masuk untuk melihat aktivitas": "Sign in to view activity",
  "Masuk untuk melihat grup kamu, bergabung, membuat grup, dan mengirim pesan.": "Sign in to view, join, and create groups or send messages.",
  "Mau ke mana?": "Where would you like to go?",
  "member · chat saja": "members · chat only",
  "Memproses permintaan…": "Processing request…",
  "Memuat momen terbaru…": "Loading the latest moments…",
  "MULAI DARI SINI ✨": "START HERE ✨",
  "ORANG TERPERCAYA": "TRUSTED PEOPLE",
  "Penerima hanya mendapat izin yang kamu aktifkan untuk pet ini.": "Recipients only get the permissions you enable for this pet.",
  "Pengalaman sebelumnya": "Previous experience",
  "PENGATURAN AKUN": "ACCOUNT SETTINGS",
  "Pertanyaan di luar topik hewan otomatis ditolak. Jawaban bukan pengganti diagnosis dokter.": "Non-pet questions are automatically declined. Answers do not replace a vet's diagnosis.",
  "PET": "PET",
  "PET PARENT CLUB ✦": "PET PARENT CLUB ✦",
  "Pet Parent Slivadoc": "Slivadoc Pet Parent",
  "Pilih": "Choose",
  "PILIH PET": "CHOOSE A PET",
  "Points": "Points",
  "Preview foto posting": "Post photo preview",
  "Preview media": "Media preview",
  "Record": "Records",
  "Saya mengerti": "I understand",
  "Screening adopter": "Adopter screening",
  "SEMUA FITUR SLIVADOC": "ALL SLIVADOC FEATURES",
  "Semua jadwal pet dalam satu tempat": "Every pet schedule in one place",
  "SESI AKTIF": "ACTIVE SESSION",
  "Sesi Slivadoc di perangkat ini akan diakhiri. Data dan profil pet kamu tetap aman.": "The Slivadoc session on this device will end. Your data and pet profiles remain safe.",
  "Simpan posting": "Save post",
  "Sistem memblokir pairing tidak aman, data kedaluwarsa, dan indikasi kekerabatan. Pemeriksaan pra-breeding tetap wajib.": "The system blocks unsafe matches, expired data, and possible relatives. Pre-breeding checks remain mandatory.",
  "SLIVA POINT": "SLIVA POINT",
  "Status": "Status",
  "suka": "likes",
  "Sukai posting": "Like post",
  "Tambah profil pet": "Add pet profile",
  "Tampilkan update aktivitas akun yang penting.": "Show important account activity updates.",
  "terverifikasi": "verified",
  "Tinjau notifikasi keamanan": "Review security notifications",
  "TOP PICK": "TOP PICK",
  "Total": "Total",
  "Tutup detail": "Close details",
  "Tutup pembayaran": "Close payment",
  "Tutup pilihan aktivitas": "Close activity choices",
  "UNDANG ANGGOTA": "INVITE A MEMBER",
  "Undangan pertama untuk": "The first invitation for",
  "update": "updates",
  "Voucher": "Voucher",
  "Welfare check aktif": "Active welfare check",
  "Booking, belanja, dan konsultasi tersimpan aman di akunmu.": "Your bookings, purchases, and consultations are stored securely in your account.",
  "Login diperlukan untuk menghubungi tim Slivadoc": "Sign in to contact the Slivadoc team",
  "Lamaran saya": "My applications",
  "Tarik lamaran": "Withdraw application",
  "Listing adopsi saya": "My adoption listings",
  "Sedang ditinjau": "Under review",
  "Kunjungan rumah": "Home visit",
  "Disetujui": "Approved",
  "Belum berhasil": "Not successful",
  "Adopsi selesai": "Adoption completed",
  "Ditarik": "Withdrawn",
  "Mulai tinjau": "Start review",
  "Jadwalkan kunjungan": "Schedule visit",
  "Tandai selesai": "Mark completed",
  "Permintaan bergabung": "Join requests",
  "Setujui": "Approve",
  "Tolak": "Decline",
  "Tim Slivadoc": "Slivadoc Team",
  "Pesan belum terkirim": "Message could not be sent",
  "Jawaban memakai dataset pet lokal Slivadoc": "The answer uses Slivadoc's local pet dataset",
  "Aktivitas belum dapat dimuat": "Activity could not be loaded",
  "Produk belum dapat dimuat": "Products could not be loaded",
  "Produk pada pesanan lama sudah tidak tersedia": "A product from the previous order is no longer available",
  "Produk pada pesanan lama sedang tidak tersedia": "A product from the previous order is currently unavailable",
  "Ringkasan belum dapat dihitung": "The summary could not be calculated",
  "Checkout belum dapat diproses": "Checkout could not be processed",
  "Ceritakan pengalamanmu minimal 10 karakter": "Share your experience in at least 10 characters",
  "Ulasan belum dapat disimpan": "The review could not be saved",
  "Paket konsultasi sebelumnya sudah tidak tersedia": "The previous consultation plan is no longer available",
  "Lengkapi nama, nomor kontak, alamat, dan alasan adopsi": "Complete your name, contact number, address, and adoption reason",
  "Tambahkan atau pilih pet sebelum mengajukan dokumen": "Add or choose a pet before requesting a document",
  "Lengkapi kota asal, tujuan, dan jadwal keberangkatan": "Complete the origin, destination, and departure schedule",
  "Format jadwal belum valid. Gunakan YYYY-MM-DD HH:mm": "Invalid schedule format. Use YYYY-MM-DD HH:mm",
  "Ketertarikan terkirim; kontak tetap privat sampai disetujui": "Interest sent; contact details stay private until approved",
  "Pendaftaran academy berhasil tersinkron": "Academy registration synced successfully",
  "Tiket event gratis berhasil dibuat": "Free event ticket created",
  "Konsultasi gratis berhasil dibuat": "Free consultation created",
  "Screening adopsi berhasil diajukan": "Adoption screening submitted",
  "Permohonan dokumen gratis berhasil dibuat": "Free document request created",
  "Petunjuk arah dibuka": "Directions opened",
  "Live PetHub dibuka": "PetHub Live opened",
  "Pembayaran berhasil dan transaksi sudah tercatat": "Payment successful and the transaction is recorded",
  "PetHub belum dapat dimuat": "PetHub could not be loaded",
  "Izinkan akses galeri untuk memilih foto atau video": "Allow gallery access to choose a photo or video",
  "Durasi video maksimal 60 detik": "Videos can be up to 60 seconds",
  "Tambahkan caption minimal 3 karakter": "Add a caption with at least 3 characters",
  "Story tayang selama 24 jam": "Your story will be available for 24 hours",
  "Posting berhasil diterbitkan": "Post published",
  "Media belum dapat diterbitkan": "Media could not be published",
  "Like belum tersimpan": "Like could not be saved",
  "Komentar belum dapat dimuat": "Comments could not be loaded",
  "Komentar belum terkirim": "Comment could not be sent",
  "Izin galeri dibutuhkan untuk memilih foto": "Gallery access is required to choose a photo",
  "Posting gagal": "Post could not be published",
  "Akses keluarga belum dapat dimuat": "Family access could not be loaded",
  "Lengkapi nama, email, dan minimal satu izin akses": "Complete the name, email, and at least one permission",
  "Undangan belum dapat dikirim": "The invitation could not be sent",
  "Akses anggota berhasil dicabut": "Member access revoked",
  "Akses belum dapat dicabut": "Access could not be revoked",
  "Grup belum dapat dimuat": "Groups could not be loaded",
  "Belum dapat bergabung": "Could not join yet",
  "Grup belum dapat dibuat": "The group could not be created",
  "Chat belum dapat dimuat": "Chat could not be loaded",
  "baru saja": "just now",
  "PEMBAYARAN ·": "PAYMENT ·",
  "Belum ada rekam medis untuk": "No medical records for",
  "Jakarta": "Jakarta",
  "LEGAL · SLIVADOC": "LEGAL · SLIVADOC",
  "Logo Slivadoc": "Slivadoc logo",
  "Kode QRIS pembayaran": "Payment QRIS code",
  "REELS": "REELS",
  "SLIVADOC · PET OWNER": "SLIVADOC · PET OWNER",
  "Slivadoc Community": "Slivadoc Community",
  "Slivadoc Pet Owner Mobile": "Slivadoc Pet Owner Mobile",
  "Story ·": "Story ·",
  "● Menunggu konfirmasi pembayaran…": "● Waiting for payment confirmation…",
  "♡ Kirim ketertarikan": "♡ Send interest",
  "AI khusus topik hewan": "AI for pet topics only",
  "Aksi belum dapat diproses": "The action could not be processed",
  "Akun, transaksi, dan bantuan penggunaan": "Account, transactions, and app support",
  "Bagikan story": "Share story",
  "Belum ada chat grup": "No group messages yet",
  "Belum ada pet": "No pet yet",
  "Belum dicatat": "Not recorded yet",
  "Booking, transaksi, dan jadwal pet": "Pet bookings, transactions, and schedules",
  "Buat Booking": "Create Booking",
  "Buat care plan pertama": "Create the first care plan",
  "Buat profil PAW Dating pet terlebih dahulu": "Create your pet's PAW Dating profile first",
  "Care Team": "Care Team",
  "Caregiver": "Caregiver",
  "Cerita dan diskusi pet parent": "Pet parent stories and discussions",
  "Co-parent": "Co-parent",
  "DETAIL UPDATE": "UPDATE DETAILS",
  "Dokter": "Vet",
  "Edit profil tersedia melalui data akun Slivadoc": "Profile editing is available through your Slivadoc account data",
  "Event dan aktivitas di kotamu": "Events and activities in your city",
  "Favorit belum dapat diperbarui": "Favorites could not be updated",
  "Gratis": "Free",
  "Health check": "Health check",
  "Health clearance": "Health clearance",
  "Hewan saya sesak dan sangat lemas": "My pet is short of breath and very weak",
  "HUMAN TEAM": "HUMAN TEAM",
  "Jadwal / status": "Schedule / status",
  "Jadwalkan layanan untuk pet": "Schedule a service for your pet",
  "Kelas dan trainer terverifikasi": "Verified classes and trainers",
  "Kesehatan Pet": "Pet Health",
  "Komunitas belum dapat dimuat": "Community could not be loaded",
  "Kondisi prima": "In great shape",
  "KONSULTASI UNTUK": "CONSULTATION FOR",
  "Lengkapi datanya": "Complete the details",
  "Lihat health score dan rekam medis": "View health score and medical records",
  "Live streaming, story, komentar, channel, dan pet thread.": "Live streams, stories, comments, channels, and pet threads.",
  "Login untuk pilih pet": "Sign in to choose a pet",
  "Lokasi / partner": "Location / partner",
  "Lokasi belum tersedia": "Location is not available yet",
  "Lost & Found": "Lost & Found",
  "Media wajib dipilih": "Please choose media",
  "Menghubungkan hotline darurat 24/7": "Connecting to the 24/7 emergency hotline",
  "Menunggu dokter": "Waiting for vet",
  "Momen dari PetHub Slivadoc": "A moment from Slivadoc PetHub",
  "Mulai profil pet": "Create pet profile",
  "Online": "Online",
  "OTP dikirim ke email. Masukkan kode untuk mengaktifkan akun.": "OTP sent by email. Enter the code to activate your account.",
  "Pemilik": "Owner",
  "Pet Academy": "Pet Academy",
  "PET DOCUMENTS": "PET DOCUMENTS",
  "Pet Event": "Pet Events",
  "PET EVENT DI KOTAMU": "PET EVENTS IN YOUR CITY",
  "PET FRIENDLY DISCOVERY": "PET-FRIENDLY DISCOVERY",
  "Pet hotel": "Pet hotel",
  "pet ini": "this pet",
  "pet kamu": "your pet",
  "Pet kamu": "Your pet",
  "PET ONLY": "PETS ONLY",
  "pet parent": "pet parent",
  "Pet Parent": "Pet Parent",
  "Pet Partner Slivadoc": "Slivadoc Pet Partner",
  "Pet saya muntah, apa yang harus diperhatikan?": "My pet is vomiting. What should I watch for?",
  "PET TRAINING & ACADEMY": "PET TRAINING & ACADEMY",
  "PETHUB LIVE & THREAD": "PETHUB LIVE & THREAD",
  "Pilih dokter & paket": "Choose a vet & plan",
  "Pilih layanan pengganti dari semua partner Slivadoc": "Choose a replacement service from all Slivadoc partners",
  "Pilih video maksimal 60 detik": "Choose a video up to 60 seconds",
  "Produk": "Products",
  "Produk pilihan dari partner Slivadoc untuk kebutuhan harian pet-mu.": "Selected products from Slivadoc partners for your pet's daily needs.",
  "Profil & jarak": "Profile & distance",
  "Realtime belum dikonfigurasi": "Realtime is not configured",
  "Rekam medis belum tersedia": "Medical records are not available yet",
  "RESPONSIBLE ADOPTION": "RESPONSIBLE ADOPTION",
  "Rumah milik": "Owned home",
  "Rumah sewa": "Rented home",
  "Saya butuh bantuan terkait akun saya": "I need help with my account",
  "Saya butuh bantuan terkait booking atau pembayaran": "I need help with a booking or payment",
  "semua layanan": "all services",
  "Sesi berhasil diakhiri": "Session ended successfully",
  "Siap diunggah": "Ready to upload",
  "SlivaCare belum dapat menjawab": "SlivaCare could not answer yet",
  "SlivaCare Team": "SlivaCare Team",
  "Slivadoc membantu pet parent mengelola profil pet, booking, transaksi, komunitas, Petship, dan layanan mitra. Data wajib benar; penggunaan yang membahayakan hewan, menipu, atau melanggar privasi dapat dimoderasi. Informasi kesehatan tidak menggantikan pemeriksaan dokter hewan. Detail biaya dan pembatalan ditampilkan sebelum konfirmasi.": "Slivadoc helps pet parents manage pet profiles, bookings, transactions, communities, Petship, and partner services. Information must be accurate; harmful, fraudulent, or privacy-violating use may be moderated. Health information does not replace a veterinary examination. Fees and cancellation details are shown before confirmation.",
  "Slivadoc memproses identitas akun, profil pet, catatan layanan, preferensi, dan data perangkat untuk autentikasi, personalisasi, transaksi, keamanan, serta dukungan. Petship hanya membagikan lokasi tempat, bukan koordinat personal. Akses data dibatasi berdasarkan peran dan aktivitas penting dicatat untuk audit.": "Slivadoc processes account identity, pet profiles, service records, preferences, and device data for authentication, personalization, transactions, security, and support. Petship shares place locations, not personal coordinates. Data access is role-based and important activity is logged for audit.",
  "SLIVADOC VERIFIED": "SLIVADOC VERIFIED",
  "Tambahkan profil pet terlebih dahulu. Akunmu sedang dalam mode lihat saja.": "Add a pet profile first. Your account is currently view-only.",
  "Tanpa izin aktif": "No active permissions",
  "Tempat seru yang pet friendly": "Fun pet-friendly places",
  "Temukan keluarga baru yang tepat": "Find the right new family",
  "Terdekat dari kamu": "Nearest to you",
  "Tetap terpantau": "Stay on track",
  "Vaksin": "Vaccines",
  "Vaksin diproses": "Vaccine in progress",
  "Vaksin lengkap": "Vaccinations complete",
  "Verified eligible": "Verified eligible",
  "Verified matches": "Verified matches",
  "Viewer": "Viewer",
  "Ya, cabut akses": "Yes, revoke access",
  "Invoice": "Invoices",
  "Tagihan klinik & toko": "Clinic & store bills",
  "Tagihan klinik dan toko yang tertaut ke akunmu": "Clinic and store bills linked to your account",
  "Memuat invoice…": "Loading invoices…",
  "Invoice belum dapat dimuat": "Invoices could not be loaded",
  "Detail invoice belum dapat dimuat": "Invoice details could not be loaded",
  "Belum ada invoice": "No invoices yet",
  "Belum ada invoice tertaut. Tautkan kode pet owner di klinik agar invoice muncul di sini.": "No linked invoices yet. Link your pet owner code at the clinic so invoices appear here.",
  "Muat ulang": "Reload",
  "Memuat ulang invoice…": "Reloading invoices…",
  "Memuat rincian…": "Loading details…",
  "Belum lunas": "Unpaid",
  "Dikembalikan sebagian": "Partially refunded",
  "Diskon": "Discount",
  "Pajak": "Tax",
  "Sudah dibayar": "Paid",
  "Sisa tagihan": "Outstanding",
  "Kembali ke akun": "Back to account",
  "Muat lebih banyak": "Load more",
  "Memuat…": "Loading…",
  "Batalkan pesanan": "Cancel order",
  "Membatalkan…": "Cancelling…",
  "Ajukan retur": "Request return",
  "Kirim permintaan retur": "Send return request",
  "Mengirim…": "Sending…",
  "Retur diajukan": "Return requested",
  "Ceritakan alasan retur (minimal 10 karakter)": "Tell us why you want to return it (at least 10 characters)",
  "Alasan retur wajib diisi 10–1000 karakter.": "The return reason must be 10–1000 characters.",
  "Yuk, cek kebutuhan pet-mu hari ini.": "Let's check what your pet needs today.",
  "Masuk / Daftar": "Sign in / Register",
  "Sinkronkan profil pet, aktivitas, dan membership Slivadoc.": "Sync your pet profiles, activity, and Slivadoc membership.",
  "Tambahkan profil pet agar bisa booking, belanja, dan berinteraksi.": "Add a pet profile to book, shop, and interact.",
  "Pindai kode QR dengan aplikasi pembayaran pilihan Anda.": "Scan the QR code with your preferred payment app.",
  "Hewan Saya": "My Pets",
  "Favorit Saya": "My Favorites",
  "Pusat Bantuan": "Help Center",
  "Semua fitur Slivadoc": "All Slivadoc features",
  "Akun & perawatan": "Account & care",
  "Semua fitur komunitas dan gaya hidup pet, langsung sekali tap.": "All pet community and lifestyle features, just one tap away.",
  "Selamat datang di Slivadoc": "Welcome to Slivadoc",
  "Semua kebutuhan pet tersinkron dalam satu tempat.": "Everything your pet needs, synced in one place.",
  "Unduh ringkasan": "Download summary",
  "Kartu member kamu": "Your membership card",
  "Satu identitas untuk setiap momen perawatan": "One identity for every care moment",
  "Nomor member": "Member number",
  "Member sejak": "Member since",
  "Level member": "Membership tier",
  "Sliva Point": "Sliva Points"
};
