import { englishPolish } from "./english-polish.ts";
import { englishSpecies } from "./english-species.ts";
export const englishExtra: Record<string, string> = {
  ...englishSpecies,
  ...englishPolish,
  "Senin": "Monday",
  "Selasa": "Tuesday",
  "Rabu": "Wednesday",
  "Kamis": "Thursday",
  "Jumat": "Friday",
  "Sabtu": "Saturday",
  "Minggu": "Sunday",
  "Ringkasan tempat": "Venue overview",
  "Bagian toko": "Store sections",
  "Detail tempat": "Venue details",
  "Informasi kunjungan": "Visit information",
  "Belum ada produk pada pilihan ini": "No products match this selection yet",
  "Pilih kategori lain atau lihat layanan partner yang tersedia.": "Choose another category or explore the partner's available services.",
  "Kategori produk belum tersedia": "No product categories yet",
  "Kategori akan tampil setelah partner menerbitkan produk.": "Categories will appear when the partner publishes products.",
  "Hubungi partner untuk informasi layanan dan ketersediaan terbaru.": "Contact the partner for the latest service information and availability.",
  "PETCLINIC": "PET CLINIC",
  "PETSHOP": "PET SHOP",
  "PETCLINIC & PETSHOP": "PET CLINIC & PET SHOP",
  "RENCANAKAN KUNJUNGAN": "PLAN YOUR VISIT",
  "KENALI PARTNER": "MEET THE PARTNER",
  "Partner Slivadoc": "Slivadoc partner",
  "Fasilitas pet": "Pet amenities",
  "Pilihan reservasi": "Booking options",
  "Reservasi tempat": "Book a visit",
  "Website tempat": "Visit website",
  "Tanya partner": "Ask the partner",
  "Konfirmasi jam operasional kepada pengelola sebelum berkunjung.": "Confirm opening hours with the venue before your visit.",
  "Konfirmasi aturan pet dan ketersediaan tempat sebelum berkunjung.": "Confirm pet rules and availability before your visit.",
  "Kembali ke PetSpot": "Back to PetSpot",
  "Tulis komentar": "Write a comment",
  "Saya menyetujui Syarat dan Ketentuan": "I agree to the Terms and Conditions",
  "Saya menyetujui Kebijakan Privasi": "I agree to the Privacy Policy",
  "Tempat tujuan": "Destination",
  "Ke mana bersama pet-mu?": "Where to with your pet?",
  "Belum ada event yang cocok": "No matching events yet",
  "Event mendatang": "Upcoming events",
  "Kategori event": "Event categories",
  "Hapus pencarian event": "Clear event search",
  "Cari event atau kota…": "Search events or cities\u2026",
  "Cari event atau kota": "Search events or cities",
  "Temukan agenda dan pengalaman baru di kotamu.": "Discover events and new experiences in your city.",
  "Momen seru, bareng pet-mu.": "Great moments, with your pet.",
  "Putar animasi brand": "Play brand animation",
  "Jeda animasi brand": "Pause brand animation",
  "Brand pet": "Pet brands",
  "Kenali brand favoritmu.": "Meet your favorite brands.",
  "DUNIA BRAND PET": "THE WORLD OF PET BRANDS",
  "AKUN & PERAWATAN": "ACCOUNT & CARE",
  "Akun & perawatan": "Account & care",
  "Yuk, bikin hari pet-mu makin sehat dan happy.": "Let's make your pet's day healthier and happier.",
  "Terdekat": "Nearby",
  "1 catatan": "1 record",
  "Tambah profil hewan": "Add pet profile",
  "Anggota keluarga baru": "New family member",
  "Nama pet": "Pet name",
  "Nama spesies": "Species name",
  "Nama ilmiah": "Scientific name",
  "Simpan profil hewan": "Save pet profile",
  "Berat badan (kg)": "Weight (kg)",
  "Belum diketahui": "Unknown",
  "Profil hewan berhasil disimpan": "Pet profile saved successfully",
  "Pet dalam keluargamu": "Pets in your family",
  "Belum ada profil pet. Tambahkan pet untuk mulai menggunakan layanan.": "No pet profile yet. Add a pet to start using services.",
  "Berat harus berupa angka nol atau lebih dalam kg.": "Weight must be a number of zero or more in kg.",
  "Tanggal lahir harus valid dan tidak boleh di masa depan.": "Date of birth must be valid and cannot be in the future.",
  "Katalog spesies belum tersedia. Coba lagi.": "The species catalogue is not available yet. Try again.",
  "Katalog spesies belum dapat dimuat. Coba lagi.": "Unable to load the species catalogue. Try again.",
  "Pet sudah tersimpan. Muat ulang profil untuk melanjutkan.": "Your pet has been saved. Refresh the profile to continue.",
  "Muat ulang profil": "Refresh profile",
  "Cari pilihan": "Search options",
  "Pilihan tidak ditemukan.": "No matching options found.",
  "Ras (opsional)": "Breed (optional)",
  "Nama ilmiah (opsional)": "Scientific name (optional)",
  "Tanggal lahir (opsional)": "Date of birth (optional)",
  "Berat badan (kg, opsional)": "Weight (kg, optional)",
  "Nama pet *": "Pet name *",
  "Jenis hewan *": "Species *",
  "Nama spesies *": "Species name *",
  "Memuat dokter…": "Loading vets…",
  "Dokter belum dapat dimuat.": "Unable to load vets.",
  "Belum ada dokter yang tersedia.": "No vets are available yet.",
  "Informasi belum dapat dimuat": "Unable to load information",
  "Periksa koneksi internet lalu coba lagi.": "Check your internet connection and try again.",
  "Belum ada program pada kategori ini": "No programs in this category yet",
  "Pilih kategori lain atau kembali lagi untuk melihat program terbaru.": "Choose another category or come back for new programs.",
  "Belum ada event mendatang": "No upcoming events yet",
  "Event yang tersedia akan muncul di sini. Cek kembali untuk kegiatan bersama pet-mu.": "Available events will appear here. Check back for activities with your pet.",
  "Muat ulang": "Refresh",
  "Tutup komentar": "Close comments",
  "Trainer sesuai jenis pet": "Trainers for your pet's species",
  "Pilih spesialis yang paling cocok sebelum menentukan kelas.": "Choose the right specialist before selecting a class.",
  "Kebutuhan pet, lengkap.": "Everything your pet needs.",
  "Mulai pet passport adopsi": "Create an adoption pet passport",
  "Mulai pet passport": "Create a pet passport",
  "Foto buku vaksin · wajib": "Vaccination record photo · required",
  "Foto buku vaksin": "Vaccination record photo",
  "Tanggal lahir / menetas (opsional)": "Birth / hatch date (optional)",
  "Belum ada slot dalam 14 hari. Pilih paket chat atau trainer lain.": "No slots are available in the next 14 days. Choose a chat package or another trainer.",
  "Belum ada slot untuk 14 hari ke depan. Pilih paket chat atau trainer lain.": "No slots are available in the next 14 days. Choose a chat package or another trainer.",
  "Belum ada slot dokter untuk 14 hari ke depan. Pilih paket chat atau dokter lain.": "No veterinarian slots are available in the next 14 days. Choose a chat package or another veterinarian.",
  "Semua kebutuhan anabul, lebih mudah ditemukan": "Find everything your pet needs more easily",
  "Temukan teman anabul di sekitarmu": "Find nearby pet friends",
  "Pet yang akan sekolah": "Pet attending the class",
  "Sudah": "Yes",
  "Pengajuan + biaya tetap. Tanpa lelang.": "Application + fixed fee. No bidding.",
  "Belajar bersama. Bertumbuh bersama.": "Learn together. Grow together.",
  "Semua kebutuhan anabul": "Everything your pet needs",
  "Pilih file": "Choose file",
  "Belum ada file dipilih": "No file selected",
  "Pilih file untuk melanjutkan.": "Choose a file to continue.",
  "Kolom ini wajib diisi.": "This field is required.",
  "Masukkan format data yang valid.": "Enter a valid value.",
  "Pilih tanggal/jam yang valid sesuai batas jadwal.": "Choose a valid date/time within the schedule limits.",
  "Pilih salah satu opsi untuk melanjutkan.": "Choose an option to continue.",
  "Cari pilihan…": "Search options…",
  "Pilihan tidak ditemukan. Coba kata lain.": "No options found. Try another search.",
  "Makanan kucing": "Cat food",
  "Makanan anjing": "Dog food",
  "Makanan hewan": "Pet food",
  "Kandang hewan": "Pet cages",
  "Aksesoris hewan": "Pet accessories",
  "Grooming Kucing": "Cat Grooming",
  "Grooming Anjing": "Dog Grooming",
  "Klinik hewan": "Veterinary clinic",
  "Dokter hewan": "Veterinarian",
  "Vaksin hewan": "Pet vaccination",
  "Mau manjain pet-mu dengan apa? ✨": "How would you like to treat your pet? ✨",
  "Cari di seluruh Slivadoc": "Search all of Slivadoc",
  "Kalender Slivadoc": "Slivadoc Calendar",
  "Pilih tanggal": "Choose a date",
  "Pilih jam": "Choose a time",
  "Pilih tahun": "Choose a year",
  "Bulan": "Month",
  "Tahun": "Year",
  "Jam": "Hour",
  "Menit": "Minute",
  "Bulan sebelumnya": "Previous month",
  "Bulan berikutnya": "Next month",
  "Kosongkan": "Clear",
  "Tutup galeri": "Close gallery",
  "Buka daftar chat": "Open chats",
  "Kota": "City",
  "Memuat percakapan…": "Loading conversation…",
  "ulasan": "reviews",
  "Jenis kelamin": "Sex",
  "sesi": "sessions",
  "Toko": "Shop",
  "Dokter Hewan": "Veterinarian",
  "Sterilisasi": "Spaying / neutering",
  "Jantan": "Male",
  "Betina": "Female",
  "Kirim": "Send",
  "Gambar sebelumnya": "Previous image",
  "Gambar berikutnya": "Next image",
  "Membalas": "Replying",
  "Foto sebelumnya": "Previous photo",
  "Foto berikutnya": "Next photo",
  "Chat toko": "Store chat",
  "produk": "products",
  "Memuat lamaran…": "Loading applications…",
  "konsultasi": "consultations",
  "Rating tertinggi": "Highest rated",
  "poin": "points",
  "Bisa dibatalkan hingga": "Can be cancelled up to",
  "Hemat": "Save",
  "jam sebelum jadwal": "hours before the scheduled time",
  "Nama penerima": "Recipient name",
  "Bagikan": "Share",
  "Memuat komentar…": "Loading comments…",
  "Tutup chat": "Close chat",
  "Valid sampai": "Valid until",
  "Tentang": "About",
  "Foto belum tersedia": "No photos available",
  "Spesialisasi": "Specialty",
  "tahun": "years",
  "Mulai": "Start",
  "Sudah vaksin": "Vaccinated",
  "Mulai segera": "Start now",
  "Pilih jadwal": "Choose a schedule",
  "menit": "minutes",
  "tamu": "guests",
  "terdaftar": "registered",
  "· otomatis": "· automatic",
  "Satu dunia untuk setiap langkah kecilnya.": "One world for every little step.",
  "Menyiapkan ruang pet-mu": "Preparing your pet's space",
  "Ditambahkan ke keranjang": "Added to cart",
  "Navigasi utama": "Main navigation",
  "Menyinkronkan pesan dan status toko terbaru.": "Syncing the latest messages and store status.",
  "Lihat profil": "View profile",
  "Profil": "Profile",
  "Tanggal lahir": "Date of birth",
  "Warna": "Color",
  "CATATAN KHUSUS": "SPECIAL NOTES",
  "Role akses": "Access role",
  "Radius notifikasi": "Notification radius",
  "Paling direkomendasikan": "Recommended",
  "Jarak terdekat": "Nearest",
  "Harga terendah": "Lowest price",
  "Urutkan berdasarkan": "Sort by",
  "hasil": "results",
  "PENGINGAT PERAWATAN": "CARE REMINDER",
  "Jenis perawatan": "Care type",
  "Pengulangan": "Repeat",
  "Target respons": "Response target",
  "Pengiriman": "Delivery",
  "Pembayaran": "Payment",
  "Privasi & data": "Privacy & data",
  "(opsional)": "(optional)",
  "ALAMAT PENGIRIMAN": "DELIVERY ADDRESSES",
  "Memuat alamat tersimpan…": "Loading saved addresses…",
  "DATA AKUN": "ACCOUNT DETAILS",
  "Edit profil pet parent": "Edit pet parent profile",
  "Tutup detail layanan": "Close service details",
  "Tidak jadi": "Cancel",
  "DOKUMEN TRANSAKSI": "TRANSACTION DOCUMENTS",
  "Tutup invoice": "Close invoice",
  "Untuk siapa booking ini?": "Who is this booking for?",
  "Menyinkronkan jadwal cabang…": "Syncing branch schedules…",
  "Sisa": "Remaining",
  "Periksa sekali lagi": "Review once more",
  "Catatan:": "Note:",
  "Alamat pengiriman": "Delivery address",
  "Jenis hewan": "Animal type",
  "Balas": "Reply",
  "Visibilitas": "Visibility",
  "dari 5": "out of 5",
  "Kunjungi toko": "Visit store",
  "TANYAKAN PRODUK INI": "ASK ABOUT THIS PRODUCT",
  "Mulai obrolan dengan toko": "Start a store conversation",
  "Buka pilihan chat": "Open chat options",
  "Tulis pesan ke toko…": "Write a message to the store…",
  "Pesan untuk toko": "Message to the store",
  "Menyiapkan etalase toko…": "Loading store listings…",
  "Etalase belum dapat dibuka": "Store listings are unavailable",
  "LAYANAN PARTNER": "PARTNER SERVICES",
  "Belum ada ulasan toko": "No store reviews yet",
  "Urutkan": "Sort",
  "Reset filter": "Reset filters",
  "Spesies": "Species",
  "Anjing": "Dog",
  "Kucing": "Cat",
  "Jarak": "Distance",
  "SUKA": "LIKE",
  "LEWATI": "PASS",
  "Lihat detail pet & owner": "View pet & owner details",
  "Bandingkan dengan": "Compare with",
  "Jarak maksimum": "Maximum distance",
  "Klinik / rumah sakit": "Clinic / hospital",
  "Nama dokter": "Veterinarian name",
  "PEMBAYARAN · QRIS": "PAYMENT · QRIS",
  "Belum ada lamaran masuk.": "No applications received yet.",
  "Catatan untuk pelamar (opsional)": "Note for the applicant (optional)",
  "Lihat paket": "View packages",
  "Pilih cara konsultasi": "Choose a consultation method",
  "hari": "days",
  "Rumah baru. Cerita bahagia berikutnya.": "A new home. The next happy chapter.",
  "Sudah steril": "Spayed / neutered",
  "PILIHAN": "OPTIONS",
  "HARI KERJA": "BUSINESS DAYS",
  "Slot jadwal ·": "Schedule slot ·",
  "Total paket": "Package total",
  "Kota domisili": "City of residence",
  "Karakter (pisahkan koma)": "Traits (separated by commas)",
  "Status vaksin": "Vaccination status",
  "Belum dikonfirmasi": "Unconfirmed",
  "Pengajuan terkirim": "Application submitted",
  "BIAYA ADOPSI TETAP": "FIXED ADOPTION FEE",
  "← Kembali ke pet passport": "← Back to pet passport",
  "Waktu story": "Story duration",
  "Hubungi tempat": "Contact venue",
  "Jam operasional": "Opening hours",
  "Pesan minimal": "Book at least",
  "Maksimal": "Maximum",
  "tamu per reservasi.": "guests per reservation.",
  "dari": "from",
  "PET TRAINER TERVERIFIKASI": "VERIFIED PET TRAINER",
  "Lihat jenis pet berikutnya": "View more pet types",
  "Lihat pet trainer berikutnya": "View more pet trainers",
  "foto": "photos",
  "minggu ·": "weeks ·",
  "slot tersisa": "slots remaining",
  "pet parent terdaftar": "registered pet parents",
  "Radius pencarian": "Search radius",
  "kursi": "seats",
  "Pet yang akan mengikuti kelas": "Pet attending the class",
  "Mulai ikut kelas": "Enroll in class",
  "tahun pengalaman": "years of experience",
  "Jumlah tiket": "Number of tickets",
  "Komentar PetHub": "PetHub comments",
  "Ongkir Lion Parcel": "Lion Parcel shipping",
  "Lihat produk": "View products",
  "Tutup profil trainer": "Close trainer profile",
  "Menyatukan kesehatan, care, aktivitas, dan marketplace pet-mu dalam satu pengalaman yang hangat.": "Bringing your pet's health, care, activity, and shopping together in one welcoming experience.",
  "Menyiapkan pengalaman terbaik…": "Preparing your experience…",
  "Katalog dan jadwal dimuat saat dibutuhkan.": "Catalogues and schedules load when needed.",
  "Buka chat SlivaCare": "Open SlivaCare chat",
  "Transaksi sudah tercatat dan pesanan sedang diproses.": "Your transaction is recorded and your order is being processed.",
  "AKUN PET FAMILY": "PET FAMILY ACCOUNT",
  "Profil pet, rekam medis, booking, komunitas, dan benefit tersinkron aman dalam satu akun.": "Pet profiles, medical records, bookings, community, and benefits are securely synced in one account.",
  "Nomor HP harus diawali 0 dan berisi 9–16 digit": "Phone number must start with 0 and contain 9–16 digits",
  "Wajib berisi huruf, angka, dan simbol": "Must contain letters, numbers, and symbols",
  "Berlaku sejak 26 Agustus 2026": "Effective August 26, 2026",
  "Pet Parent • Akun aktif": "Pet Parent • Active account",
  "Lokasi kamu": "Your location",
  "Cari dokter, layanan, produk...": "Search vets, services, products...",
  "Memuat hasil…": "Loading results…",
  "Ketik minimal 2 karakter untuk mulai mencari.": "Enter at least 2 characters to search.",
  "Tidak ada hasil yang cocok.": "No matching results.",
  "Kategori chat": "Chat category",
  "Sapaan": "Greeting",
  "Pet clinic & petshop terdekat": "Nearby pet clinics & pet shops",
  "Diurutkan dari titik lokasi yang kamu pilih": "Sorted from your selected location",
  "Belum ada pet clinic atau petshop di titik lokasi ini.": "No pet clinics or pet shops at this location yet.",
  "DOKTER TERBAIK": "TOP VETERINARIANS",
  "Teman konsultasi untuk": "A consultation partner for",
  "Dokter terverifikasi dengan rating dan konsultasi terbaik": "Verified veterinarians with top ratings and consultations",
  "Lihat dokter": "View veterinarians",
  "Dokter terbaik sedang disinkronkan.": "Syncing top veterinarians.",
  "REKOMENDASI SLIVADOC": "SLIVADOC RECOMMENDATIONS",
  "Lihat selengkapnya": "View more",
  "Ringkasan kesehatan dan jadwal": "Health and schedule summary",
  "Kondisi": "Condition",
  "Pilih pet aktif": "Choose active pet",
  "Ganti pet aktif": "Change active pet",
  "Ringkasan homepage akan langsung menyesuaikan.": "Your home summary updates immediately.",
  "Kelola semua profil pet": "Manage all pet profiles",
  "Tanya Dokter Hewan 24/7": "Ask a Veterinarian 24/7",
  "Konsultasi online cepat dan ramah": "Quick, friendly online consultations",
  "Belum ada pet di akunmu": "No pets in your account yet",
  "Tambahkan profil pertama untuk mulai menyimpan identitas dan kesehatan.": "Add your first pet profile to save their identity and health information.",
  "· Dibagikan": "· Shared",
  "Tambah hewan": "Add animal",
  "Buat profil untuk anggota keluarga baru": "Create a profile for a new family member",
  "Identitas terverifikasi": "Verified identity",
  "Tampilkan Pet ID": "Show Pet ID",
  "Usia": "Age",
  "Berat terakhir": "Latest weight",
  "Golongan darah": "Blood type",
  "Ringkasan perawatan": "Care summary",
  "Profil kesehatan": "Health profile",
  "Vaksin wajib": "Required vaccines",
  "Buka pusat kesehatan": "Open health center",
  "Akses keluarga": "Family access",
  "Undang co-parent, caregiver, dokter, atau viewer dengan izin terperinci.": "Invite a co-parent, caregiver, veterinarian, or viewer with detailed permissions.",
  "Kelola akses keluarga": "Manage family access",
  "Aktifkan peringatan dan bagikan profil": "Enable alerts and share the profile",
  "ke komunitas sekitar.": "with the nearby community.",
  "Kelola Lost Pet Mode": "Manage Lost Pet Mode",
  "Pindai untuk membuka identitas darurat terverifikasi Slivadoc.": "Scan to open the verified Slivadoc emergency identity.",
  "Nama": "Name",
  "Ras": "Breed",
  "Berat (kg)": "Weight (kg)",
  "Nomor microchip": "Microchip number",
  "Kebutuhan penting": "Essential needs",
  "Contoh: protein ayam": "Example: chicken protein",
  "Perilaku, preferensi, dan catatan medis": "Behavior, preferences, and medical notes",
  "Tuliskan hal yang perlu diketahui dokter, groomer, atau caregiver": "Write what the veterinarian, groomer, or caregiver needs to know",
  "AKSES KELUARGA ·": "FAMILY ACCESS ·",
  "Orang yang dipercaya": "Trusted people",
  "Memuat akses…": "Loading access…",
  "Cabut": "Revoke",
  "Undang anggota": "Invite member",
  "Komunitas radius": "Community within",
  "km sudah menerima laporan dari": "km has received a report from",
  "Terakhir terlihat": "Last seen",
  "Lokasi terakhir": "Last location",
  "Nama tempat / alamat lengkap": "Place name / full address",
  "Kronologi & ciri khusus": "Timeline & distinctive features",
  "Nomor kontak": "Contact number",
  "Imbalan (opsional)": "Reward (optional)",
  "JELAJAHI LAYANAN": "EXPLORE SERVICES",
  "Bandingkan detail layanan, status izin mitra, dan slot aktual di dekatmu.": "Compare nearby service details, partner license status, and available slots.",
  "dari seluruh area layanan Slivadoc": "across Slivadoc service areas",
  "Urutkan layanan": "Sort services",
  "Favorit": "Favorites",
  "Layanan belum ditemukan": "No services found",
  "FILTER JELAJAHI": "EXPLORE FILTERS",
  "Temukan layanan yang pas": "Find the right service",
  "Jenis layanan": "Service type",
  "Tampilkan": "Show",
  "Booking, pesanan, kelas, tiket, reservasi, dan dokumen pet-mu.": "Your pet's bookings, orders, classes, tickets, reservations, and documents.",
  "Status aktivitas": "Activity status",
  "Jenis aktivitas": "Activity type",
  "Buat booking": "Create booking",
  "Arah": "Directions",
  "Butuh layanan lain?": "Need another service?",
  "Booking dokter, grooming, home care, atau hotel dalam beberapa langkah.": "Book a veterinarian, grooming, home care, or boarding in a few steps.",
  "Jelajahi layanan": "Explore services",
  "Invoice klinik & toko": "Clinic & store invoices",
  "Detail invoice": "Invoice details",
  "Rincian item": "Item breakdown",
  "Tidak ada rincian item.": "No item details.",
  "Kembali ke daftar": "Back to list",
  "PUSAT KESEHATAN": "HEALTH CENTER",
  "Dokter terakhir": "Latest veterinarian",
  "Update terakhir": "Last updated",
  "Halaman kesehatan": "Health page",
  "Data medis": "Medical data",
  "Pengingat": "Reminders",
  "Berat terbaru": "Latest weight",
  "Jadwal penting": "Important dates",
  "Tunda": "Snooze",
  "Belum ada pengingat. Tambahkan jadwal vaksin, obat, grooming, atau kontrol berikutnya.": "No reminders yet. Add the next vaccination, medication, grooming, or check-up.",
  "Jenis rekam medis": "Medical record type",
  "Unduh": "Download",
  "Memuat rekam medis": "Loading medical records",
  "Record akan muncul setelah pemeriksaan atau konsultasi untuk": "Records appear after an examination or consultation for",
  "Jadwalkan untuk": "Schedule for",
  "Notifikasi disiapkan 7 hari, 1 hari, dan 2 jam sebelum jadwal.": "Notifications are scheduled 7 days, 1 day, and 2 hours before the appointment.",
  "Vaksinasi": "Vaccination",
  "Obat": "Medication",
  "Obat cacing": "Deworming",
  "Kutu & caplak": "Fleas & ticks",
  "Kontrol dokter": "Veterinary check-up",
  "Judul": "Title",
  "Contoh: Booster rabies": "Example: rabies booster",
  "Tanggal & waktu": "Date & time",
  "Satu kali": "Once",
  "Harian": "Daily",
  "Mingguan": "Weekly",
  "Bulanan": "Monthly",
  "Tiga bulanan": "Every three months",
  "Tahunan": "Yearly",
  "Jarak khusus": "Custom interval",
  "Jarak khusus (hari)": "Custom interval (days)",
  "Dosis, klinik, atau persiapan khusus": "Dosage, clinic, or special preparation",
  "Belum ada balasan.": "No replies yet.",
  "Tulis balasan…": "Write a reply…",
  "Balasan ticket": "Ticket reply",
  "BANTUAN YANG DAPAT DILACAK": "TRACKABLE SUPPORT",
  "Sampaikan kendala tanpa mengulang kronologi.": "Report an issue without repeating the story.",
  "Kaitkan pengaduan ke pesanan atau booking. Nomor ticket, tenggat respons, status, dan penyelesaian tersimpan di akunmu.": "Link your issue to an order or booking. Ticket numbers, response deadlines, status, and resolution are saved in your account.",
  "1 hari kerja": "1 business day",
  "Untuk tanggapan pertama tim Slivadoc.": "For the Slivadoc team's first response.",
  "BUAT PENGADUAN": "CREATE SUPPORT TICKET",
  "Ceritakan kendalanya": "Tell us about the issue",
  "Pesanan": "Orders",
  "Pesanan atau booking terkait": "Related order or booking",
  "Pesanan atau booking terkait (opsional)": "Related order or booking (optional)",
  "Tidak ada referensi": "No reference",
  "Subjek": "Subject",
  "Contoh: Status pengiriman belum berubah": "Example: delivery status has not changed",
  "Kronologi dan hasil yang diharapkan": "Timeline and expected outcome",
  "Jelaskan waktu kejadian, kondisi terakhir, dan bantuan yang kamu butuhkan.": "Describe when it happened, the latest situation, and the help you need.",
  "RIWAYAT BANTUAN": "SUPPORT HISTORY",
  "Status pengaduanmu": "Your ticket status",
  "Memuat ticket…": "Loading tickets…",
  "Penyelesaian": "Resolution",
  "Ditanggapi": "Responded",
  "Belum ada pengaduan. Ticket yang kamu buat akan tampil di sini.": "No support tickets yet. Tickets you create will appear here.",
  "Akun Pet Owner": "Pet Owner account",
  "Sinkron": "Synced",
  "Alamat tersimpan": "Saved addresses",
  "UTAMA": "PRIMARY",
  "Jadikan utama": "Set as primary",
  "Ubah": "Edit",
  "Hapus": "Delete",
  "Belum ada alamat tersimpan. Tambahkan alamat untuk checkout lebih cepat.": "No saved addresses yet. Add an address for faster checkout.",
  "Tambah alamat": "Add address",
  "Buka daftar dan detail update": "Open update list and details",
  "Tinjau notifikasi keamanan akun": "Review account security notifications",
  "Kelola orang tepercaya untuk pet": "Manage trusted people for your pet",
  "Sesi Slivadoc di perangkat ini akan diakhiri. Data dan profil pet tetap aman.": "Your Slivadoc session on this device will end. Your data and pet profiles remain safe.",
  "Tutup edit profil": "Close profile editor",
  "dari lokasi kamu": "from your location",
  "Siap dipesan": "Ready to book",
  "Jadwal dipilih saat booking": "Choose a schedule when booking",
  "INFORMASI LAYANAN": "SERVICE INFORMATION",
  "Yang tersedia untuk pet-mu": "What's available for your pet",
  "Menyinkronkan rincian layanan dari mitra…": "Syncing service details from the partner…",
  "PERSIAPAN & KEBIJAKAN": "PREPARATION & POLICIES",
  "Yang perlu diketahui sebelum booking": "What to know before booking",
  "Pet yang didukung": "Supported pets",
  "Persiapan": "Preparation",
  "Perawatan setelah layanan": "Aftercare",
  "Pembatalan & perubahan jadwal": "Cancellation & rescheduling",
  "Booking lebih tenang bersama Slivadoc": "Book with peace of mind on Slivadoc",
  "Informasi mitra, jadwal, aktivitas, dan status layanan tersimpan dalam satu alur yang mudah dipantau.": "Partner information, schedules, activities, and service status are saved in one easy-to-follow journey.",
  "Pilih jadwal & booking": "Choose schedule & book",
  "Link kelas online": "Online class link",
  "Unduh dokumen": "Download document",
  "· Estimasi:": "· Estimated:",
  "RINGKASAN AKTIVITAS": "ACTIVITY SUMMARY",
  "QR tiket event": "Event ticket QR",
  "jam sebelum jadwal.": "hours before the scheduled time.",
  "Batas pembatalan sudah lewat. Hubungi klinik untuk perubahan.": "The cancellation deadline has passed. Contact the clinic for changes.",
  "Pesanan dapat dibatalkan sebelum penjual memprosesnya.": "Orders can be cancelled before the seller processes them.",
  "Batalkan pesanan ini? Pesanan yang dibatalkan tidak dapat dipulihkan.": "Cancel this order? Cancelled orders cannot be restored.",
  "Retur": "Returns",
  "Alasan retur": "Return reason",
  "Jelaskan kendala pada barang yang diterima (minimal 10 karakter)": "Describe the issue with the received item (at least 10 characters)",
  "Koleksi favoritmu": "Your favorites",
  "Layanan dan produk favorit tersimpan pada akun di semua perangkat.": "Favorite services and products are saved to your account across devices.",
  "Favorit layanan": "Favorite services",
  "Favorit produk": "Favorite products",
  "Belum ada favorit": "No favorites yet",
  "Tekan ikon hati di Jelajahi atau Pet Shop untuk menyimpan pilihan.": "Tap the heart in Explore or Pet Shop to save your favorites.",
  "← Kembali ke semua update": "← Back to all updates",
  "Tandai semua dibaca": "Mark all as read",
  "Tidak ada notifikasi pada kategori ini.": "No notifications in this category.",
  "Tutup notifikasi": "Close notifications",
  "Filter notifikasi": "Filter notifications",
  "Tandai semua sudah dibaca": "Mark all as read",
  "Belum ada notifikasi pada kategori ini.": "No notifications in this category yet.",
  "Jeda video": "Pause video",
  "Putar video": "Play video",
  "Posisi video": "Video position",
  "Aktifkan suara": "Unmute video",
  "Bisukan video": "Mute video",
  "Video belum dapat diputar": "Video could not be played",
  "Beranda": "Home",
  "Komunitas": "Community",
  "Aktivitas": "Activity",
  "Katalog produk, stok, penjual, dan informasi kepatuhan dalam satu alur.": "Browse products, stock, sellers, and compliance details in one place.",
  "Atur profil, pembayaran, keamanan, dan benefit.": "Manage your profile, payments, security, and benefits.",
  "Katalog produk, stok, seller, dan informasi kepatuhan dalam satu alur.": "Browse products, stock, sellers, and compliance details in one place.",
  "Rekomendasi": "Recommended",
  "Terbaru": "Newest",
  "Terlaris": "Best sellers",
  "Harga termurah": "Lowest price",
  "Belanja lebih tenang untuk sahabat terbaikmu.": "Shop with confidence for your best friend.",
  "Bandingkan produk, cek stok asli, baca ulasan pembeli, lalu checkout dari banyak petshop dalam satu keranjang.": "Compare products, check live stock, read buyer reviews, and shop from multiple pet shops in one cart.",
  "MARKETPLACE PET TERINTEGRASI": "INTEGRATED PET MARKETPLACE",
  "produk aktif": "active products",
  "Kategori populer": "Popular categories",
  "PILIHAN UNTUK": "PICKS FOR",
  "Produk terbaik dari partner Slivadoc": "Top products from Slivadoc partners",
  "produk sesuai pilihanmu": "products matching your choices",
  "Status partner transparan": "Transparent partner status",
  "Produk hanya dari bisnis aktif; status izin ditampilkan apa adanya.": "Products come from active businesses, with their actual license status shown.",
  "Data stok langsung": "Live stock data",
  "Ketersediaan mengikuti cabang.": "Availability reflects each branch’s stock.",
  "Ulasan pembeli asli": "Verified buyer reviews",
  "Hanya dari transaksi terbayar.": "Reviews from paid orders only.",
  "Buka keranjang": "Open cart",
  "Last online belum tersedia": "Last online unavailable",
  "Merek": "Brand",
  "Terakhir online belum tersedia": "Last online unavailable",
  "Status izin belum tersedia": "License status unavailable",
  "Retur & garansi": "Returns & warranty",
  "Kebijakan retur belum dicantumkan oleh penjual.": "The seller has not provided a returns policy.",
  "Panduan penggunaan belum dicantumkan oleh penjual.": "The seller has not provided usage instructions.",
  "Belanja terlindungi": "Protected purchases",
  "Pembayaran jelas": "Clear payments",
  "Pengiriman jelas": "Clear delivery details",
  "Jumlah": "Quantity",
  "Dokter Hewan Online": "Online veterinarian",
  "Klinik Hewan": "Veterinary clinic",
  "Grooming Hewan": "Pet grooming",
  "Vaksinasi Hewan": "Pet vaccination",
  "Sliva Points": "Sliva Points",
  "Pembayaran aman": "Secure payments",
  "Stok langsung": "Live stock",
  "Dari sistem partner": "From the partner’s inventory",
  "Asal toko tertera": "Store origin shown",
  "Transaksi ini menghasilkan": "This purchase earns",
  "Petunjuk penggunaan belum dicantumkan oleh penjual.": "The seller has not provided usage instructions.",
  "DIJUAL OLEH": "SOLD BY",
  "Semua komentar berasal dari pembelian yang sudah dibayar.": "All reviews come from paid purchases.",
  "Masuk untuk memberi ulasan": "Sign in to write a review",
  "Tanda Anabul Perlu Segera Dibawa ke Dokter Hewan": "Signs your pet needs urgent veterinary care",
  "Panduan Vaksin Kucing untuk Pet Parent": "Cat vaccination guide for pet parents",
  "Panduan Vaksin Anjing dan Persiapannya": "Dog vaccination guide and preparation",
  "Temukan layanan, produk, panduan, dan area pet care yang relevan sebelum melanjutkan ke aplikasi.": "Find pet care services, products, guides, and areas before opening the app.",
  "Layanan populer": "Popular services",
  "Belanja & panduan": "Shop & guides",
  "Kenali manfaatnya": "Explore the benefits",
  "Untuk pet owner": "For pet owners",
  "Untuk pet clinic & bisnis hewan": "For veterinary clinics & pet businesses",
  "Dunia pet, satu destinasi": "Your pet's world, in one place",
  "Temukan tempat, pengalaman, dan teman baru untuk pet-mu.": "Find places, experiences, and new friends for your pet.",
  "Jelajahi Sliva World": "Explore Sliva World",
  "Fasilitas": "Amenities", "Indoor": "Indoor", "Outdoor": "Outdoor", "Semi outdoor": "Semi outdoor", "Pet menu": "Pet menu",
  "Mangkuk minum": "Water bowls", "Area kebersihan pet": "Pet waste station", "Area event pet": "Pet event area", "Pet lounge": "Pet lounge",
  "Zona pet kecil": "Small pet zone", "Jalur jalan pet": "Pet walking trail", "Area agility": "Agility area", "Area berpagar": "Fenced area",
  "Akses kursi roda": "Wheelchair access", "Area tanpa leash": "Off-leash area",
  "Cari tempat ramah pet": "Search pet-friendly places",
  "Cari cafe, kosan, apartemen, mall…": "Search cafes, coliving, apartments, malls…",
  "Cari dari posisi saya": "Search near me",
  "Mencari lokasi…": "Finding your location…",
  "Izinkan lokasi untuk mencari tempat di sekitarmu.": "Allow location access to find places nearby.",
  "Lokasi belum dapat digunakan. Coba lagi.": "Unable to use your location. Please try again.",
  "PetSpot diurutkan berdasarkan koordinat perangkat": "PetSpot sorted by your device location",

  "Area bermain pet": "Pet playground",
  "Area mandi pet": "Pet wash station",
  "Keamanan": "Security",
  "Ruang event": "Event hall",
  "Area tunggu pet": "Pet waiting area",
  "Pojok dokter hewan": "Veterinary corner",
  "Staf pendamping": "Attending staff",
  "Area makan taman": "Garden dining",
  "Taman pet": "Pet garden",
  "Ruang grooming": "Grooming room",
  "Area teduh": "Shaded area",
  "Spa pet": "Pet spa",
  "Penitipan harian": "Day care",
  "Layanan kamar": "Room service",
  "Kolam pet": "Pet pool",

  "Temukan kelas dan trainer untuk setiap tahap tumbuh pet-mu.": "Find classes and trainers for every stage of your pet's growth.",
  "Agenda seru untuk pet dan kamu.": "Great plans for you and your pet.",
  "Jelajahi kegiatan, cek lokasi dan jadwal, lalu pilih event favoritmu.": "Explore activities, check locations and dates, and find your next event.",
  "Pendamping tepat untuk pet-mu.": "The right expert for your pet.",
  "Pilih dokter atau pet trainer, lalu tentukan paket dan jadwal.": "Choose a veterinarian or pet trainer, then pick a package and time.",
  "Temukan keluarga. Mulai cerita baru.": "Find a family. Start a new story.",
  "Kenali karakter, kesehatan, dan kebutuhan pet sebelum mengajukan adopsi.": "Get to know a pet's personality, health, and needs before applying to adopt.",
  "Dokumen rapi. Perjalanan lebih tenang.": "Documents in order. Travel with peace of mind.",
  "Pilih dokumen, lengkapi checklist, dan pantau prosesnya.": "Choose a document, complete the checklist, and follow its progress.",
  "Jelajahi provider": "Explore providers",
  "EVENT PILIHAN": "FEATURED EVENT",
  "persyaratan": "requirements",
  "Buka detail": "View details",

  "Pemula": "Beginner",
  "Menengah": "Intermediate",
  "Lanjutan": "Advanced",
  "Semua level": "All levels",
  "hari kerja": "business days",

  "Sibuk": "Busy",
  "Tidak aktif": "Away",
  "Foto": "Photo",

  "Belum ada dokumen tersedia": "No documents available yet",
  "Pilihan dokumen dari mitra akan muncul di sini.": "Documents from partners will appear here.",
  // Reviewed legal copy - /privacy, /delete-account, and the deletion request form.
  // These strings must never fall through to machine translation.
  "PRIVASI & DATA": "PRIVACY & DATA",
  "Kebijakan Privasi Slivadoc": "Slivadoc Privacy Policy",
  "Berlaku mulai 8 Oktober 2026": "Effective 8 October 2026",
  "Halaman ini menjelaskan data yang kami kumpulkan, cara kami menggunakannya, pihak yang menerimanya, masa simpannya, serta hak Anda, termasuk pada aplikasi Android Slivadoc Pet Owner.":
    "This page explains the data we collect, how we use it, who receives it, how long we keep it, and your rights, including in the Slivadoc Pet Owner Android app.",
  "Yang dikumpulkan": "What we collect",
  "Data yang diterima": "Data received",
  "Pengendali data dan kontak": "Data controller and contact",
  "Pengendali data pribadi Anda adalah PT Sliva Technology Indonesia. Pertanyaan, permintaan data, atau keluhan privasi dapat dikirim ke privacy@slivadoc.com atau melalui Pusat Bantuan setelah Anda masuk ke akun.":
    "The controller of your personal data is PT Sliva Technology Indonesia. Questions, data requests, or privacy complaints can be sent to privacy@slivadoc.com or via the Help Center after you sign in.",
  "Data yang kami kumpulkan": "Data we collect",
  "Kami hanya mengumpulkan data yang diperlukan untuk menjalankan layanan Slivadoc.":
    "We only collect the data needed to run the Slivadoc service.",
  "Akun dan kontak": "Account and contact",
  "Alamat email, nama lengkap, nomor telepon, dan kata sandi yang disimpan dalam bentuk ter-hash (Argon2id).":
    "Email address, full name, phone number, and your password stored as a hash (Argon2id).",
  "Profil hewan": "Pet profile",
  "Nama, spesies, tanggal lahir, berat badan, foto, nomor microchip, alergi, dan catatan kesehatan hewan.":
    "Name, species, date of birth, weight, photos, microchip number, allergies, and your pet's health notes.",
  "Nama penerima, nomor telepon, alamat lengkap, kode pos, dan koordinat untuk keperluan pengiriman.":
    "Recipient name, phone number, full address, postcode, and coordinates for deliveries.",
  "Transaksi dan pembayaran": "Transactions and payments",
  "Riwayat pemesanan, konsultasi, pesanan, pembayaran, dan pengiriman beserta nominal dan statusnya. Kami tidak menyimpan nomor kartu, nomor rekening, atau PIN pembayaran Anda; pembayaran QRIS diproses oleh penyedia pembayaran.":
    "History of bookings, consultations, orders, payments, and shipments with their amounts and status. We do not store your card numbers, bank account numbers, or payment PINs; QRIS payments are processed by our payment provider.",
  "Konten dan komunikasi": "Content and communications",
  "Pesan chat, postingan dan komentar komunitas, laporan hewan hilang (termasuk lokasi terakhir yang Anda cantumkan), ulasan, dan tiket bantuan.":
    "Chat messages, community posts and comments, lost pet reports (including the last known location you provide), reviews, and support tickets.",
  "Perangkat dan keamanan": "Device and security",
  "Alamat IP, user agent, catatan sesi login, kode OTP, dan log aktivitas penting untuk keamanan dan audit.":
    "IP address, user agent, login session records, OTP codes, and logs of significant activity for security and audit purposes.",
  "Izin perangkat": "Device permissions",
  "Dengan izin Anda, aplikasi Android meminta akses lokasi (kasar dan/atau presisi) untuk fitur sekitar dan pencarian lokasi, serta kamera untuk mengunggah foto. Izin dapat dikelola dari pengaturan perangkat.":
    "With your permission, the Android app requests location access (coarse and/or precise) for nearby features and location search, and camera access to upload photos. You can manage permissions in your device settings.",
  "Cara kami menggunakan data": "How we use your data",
  "Menyediakan layanan: autentikasi, profil hewan, pemesanan, konsultasi, pembayaran, pengiriman, komunitas, dan dukungan pengguna.":
    "Providing our services: authentication, pet profiles, bookings, consultations, payments, shipping, community, and user support.",
  "Keamanan dan pencegahan penyalahgunaan: perlindungan akun, deteksi aktivitas mencurigakan, dan audit aktivitas penting.":
    "Security and abuse prevention: account protection, detection of suspicious activity, and audit of significant activity.",
  "Komunikasi layanan: kode OTP, konfirmasi transaksi, pembaruan status pesanan, dan informasi layanan terkait.":
    "Service communications: OTP codes, transaction confirmations, order status updates, and related service information.",
  "Asisten AI (SlivaCare): pesan chat dan data profil hewan yang Anda kirimkan ke asisten diproses untuk menghasilkan jawaban; pengenal akun dikirim dalam bentuk tersandi (hash), bukan identitas langsung.":
    "AI assistant (SlivaCare): chat messages and pet profile data you send to the assistant are processed to generate answers; your account identifier is sent in hashed form, not your direct identity.",
  "Kepatuhan hukum: memenuhi kewajiban pembukuan, perpajakan, serta permintaan yang sah dari aparat berwenang.":
    "Legal compliance: meeting bookkeeping and tax obligations, and responding to lawful requests from authorities.",
  "Pihak yang menerima data": "Who receives your data",
  "Data dibagikan hanya sejauh yang diperlukan untuk menjalankan layanan berikut.":
    "Data is shared only as far as needed to run the following services.",
  "Resend": "Resend",
  "Email transaksional (kode OTP)": "Transactional email (OTP codes)",
  "Alamat email Anda": "Your email address",
  "Cloudinary": "Cloudinary",
  "Penyimpanan media": "Media storage",
  "Foto dan dokumen yang Anda unggah": "Photos and documents you upload",
  "OpenAI": "OpenAI",
  "Pemrosesan asisten AI SlivaCare": "SlivaCare AI assistant processing",
  "Isi pesan chat dan profil hewan yang Anda kirimkan ke asisten":
    "The contents of chat messages and pet profile data you send to the assistant",
  "Photon (OpenStreetMap)": "Photon (OpenStreetMap)",
  "Pencarian lokasi (geocoding)": "Location search (geocoding)",
  "Koordinat yang Anda masukkan": "The coordinates you enter",
  "Yokke": "Yokke",
  "Pemrosesan pembayaran QRIS": "QRIS payment processing",
  "Nominal dan referensi transaksi; data kartu atau rekening tidak diteruskan kepada kami":
    "Transaction amount and reference; card or bank account data is not passed on to us",
  "Lion Parcel": "Lion Parcel",
  "Pengiriman barang": "Parcel shipping",
  "Nama, nomor telepon, alamat, email, dan koordinat pengirim serta penerima":
    "Name, phone number, address, email, and coordinates of sender and recipient",
  "Penyedia infrastruktur cloud": "Cloud infrastructure provider",
  "Hosting aplikasi, basis data, dan penyimpanan": "Hosting of the application, database, and storage",
  "Pusat data regional di luar negeri": "Regional data centers abroad",
  "Fitur penerjemahan otomatis berjalan pada infrastruktur kami sendiri dan tidak mengirim data Anda ke pihak ketiga. Kami tidak menjual data pribadi Anda.":
    "The automatic translation feature runs on our own infrastructure and does not send your data to third parties. We do not sell your personal data.",
  "Data yang bersifat publik": "Public data",
  "Laporan hewan hilang dan konten komunitas (postingan, komentar, grup) dapat dilihat publik tanpa masuk ke akun, termasuk nama hewan, jenis, lokasi terakhir, dan koordinat yang Anda cantumkan. Nomor kontak hanya tampil jika Anda mencantumkannya sendiri pada laporan. Jangan membagikan data pribadi sensitif di area publik.":
    "Lost pet reports and community content (posts, comments, groups) can be viewed publicly without signing in, including pet name, species, last known location, and the coordinates you provide. A contact number only appears if you add it to the report yourself. Do not share sensitive personal data in public areas.",
  "Dasar hukum pemrosesan": "Legal basis for processing",
  "Kami memproses data berdasarkan persetujuan Anda saat mendaftar, pelaksanaan layanan yang Anda minta, kewajiban hukum (termasuk pembukuan dan perpajakan), serta kepentingan sah kami dalam menjaga keamanan layanan, sesuai Undang-Undang Nomor 27 Tahun 2022 tentang Pelindungan Data Pribadi.":
    "We process data based on your consent when you register, performance of the services you request, legal obligations (including bookkeeping and tax), and our legitimate interest in keeping the service secure, in accordance with Law No. 27 of 2022 on Personal Data Protection.",
  "Hak Anda sebagai pemilik data": "Your rights as a data subject",
  "Anda dapat menggunakan hak berikut melalui privacy@slivadoc.com, Pusat Bantuan, atau menu pengaturan akun.":
    "You can exercise the following rights via privacy@slivadoc.com, the Help Center, or your account settings.",
  "Mendapatkan akses dan salinan data pribadi Anda.": "Access and obtain a copy of your personal data.",
  "Memperbaiki atau memperbarui data yang tidak akurat.": "Correct or update inaccurate data.",
  "Menghapus data pribadi Anda melalui fitur Hapus Akun.": "Delete your personal data through the Delete Account feature.",
  "Menarik persetujuan pemrosesan data.": "Withdraw your consent to data processing.",
  "Membatasi pemrosesan dan mengajukan keberatan atas keputusan yang diambil secara otomatis.":
    "Restrict processing and object to decisions taken automatically.",
  "Mengajukan pengaduan kepada lembaga pengawas pelindungan data pribadi.":
    "Lodge a complaint with the personal data protection supervisory authority.",
  "Masa simpan data": "Data retention",
  "Akun dan data profil: disimpan selama akun aktif, lalu dihapus atau dianonimkan setelah Anda menggunakan Hapus Akun.":
    "Account and profile data: kept while your account is active, then deleted or anonymized once you use Delete Account.",
  "Transaksi, pembayaran, dan pemesanan: dipertahankan dalam bentuk teranonim selama kurang lebih 5 tahun untuk kewajiban pembukuan dan perpajakan.":
    "Transactions, payments, and bookings: kept in anonymized form for approximately 5 years for bookkeeping and tax obligations.",
  "Log teknis dan keamanan: sekitar 90 hari. Kode OTP: dihapus 7 hari setelah kedaluwarsa. Sesi login: dihapus 30 hari setelah kedaluwarsa.":
    "Technical and security logs: about 90 days. OTP codes: deleted 7 days after expiry. Login sessions: deleted 30 days after expiry.",
  "Backup: salinan backup terenkripsi dihapus otomatis dalam rotasi hingga 12 bulan, sehingga data yang telah Anda hapus dapat bertahan pada salinan tersebut hingga rotasi selesai.":
    "Backups: encrypted backup copies are deleted automatically on a rotation of up to 12 months, so data you have deleted may persist on those copies until the rotation completes.",
  "Penghapusan akun": "Account deletion",
  "Anda dapat menghapus akun melalui menu pengaturan akun di aplikasi, atau melalui halaman Hapus Akun jika Anda sudah tidak menggunakan aplikasi. Setelah konfirmasi dengan kode OTP, tersedia masa tenggang 14 hari untuk membatalkan. Setelah masa tenggang berakhir, data pribadi Anda dihapus permanen atau dianonimkan; catatan transaksi dipertahankan secara teranonim sesuai kewajiban hukum; dan salinan backup terenkripsi terhapus dalam rotasi hingga 12 bulan.":
    "You can delete your account via account settings in the app, or through the Delete Account page if you no longer use the app. After OTP confirmation there is a 14-day grace period during which you can cancel. Once the grace period ends, your personal data is permanently deleted or anonymized; transaction records are kept in anonymized form as required by law; and encrypted backup copies are deleted on a rotation of up to 12 months.",
  "Buka halaman Hapus Akun": "Open the Delete Account page",
  "Keamanan data": "Data security",
  "Kata sandi disimpan dalam bentuk ter-hash (Argon2id) dan akses data dibatasi berdasarkan peran.":
    "Passwords are stored as a hash (Argon2id) and data access is restricted by role.",
  "Komunikasi dilindungi enkripsi saat transit, dan aktivitas penting dicatat untuk audit serta investigasi.":
    "Communications are encrypted in transit, and significant activity is logged for audit and investigation.",
  "Tidak ada sistem yang sepenuhnya aman. Segera hubungi kami jika mencurigai penyalahgunaan akun, dan jangan pernah membagikan kode OTP atau kata sandi Anda.":
    "No system is completely secure. Contact us immediately if you suspect misuse of your account, and never share your OTP code or password.",
  "Anak di bawah 13 tahun": "Children under 13",
  "Layanan Slivadoc tidak ditujukan untuk anak di bawah 13 tahun dan kami tidak dengan sengaja mengumpulkan data pribadi mereka. Jika Anda mengetahui seorang anak memberikan data pribadi kepada kami, hubungi privacy@slivadoc.com agar data tersebut kami hapus.":
    "Slivadoc is not directed at children under 13 and we do not knowingly collect their personal data. If you learn that a child has provided personal data to us, contact privacy@slivadoc.com so we can delete it.",
  "Perubahan kebijakan": "Changes to this policy",
  "Kami dapat memperbarui kebijakan ini dari waktu ke waktu. Perubahan material akan diberitahukan melalui aplikasi atau email, dan tanggal berlaku tercantum di bagian atas halaman ini.":
    "We may update this policy from time to time. Material changes will be announced through the app or email, and the effective date appears at the top of this page.",
  "Kontak privasi": "Privacy contact",
  "Kirim permintaan akses, koreksi, atau penghapusan data ke":
    "Send access, correction, or deletion requests to",
  "atau melalui": "or via",
  "setelah masuk agar identitas akun dapat diverifikasi.":
    "after signing in so your account identity can be verified.",
  "Hapus Akun": "Delete Account",
  "HAPUS AKUN": "DELETE ACCOUNT",
  "Hapus akun Slivadoc Anda": "Delete your Slivadoc account",
  "Anda berhak menghapus akun dan data pribadi Anda kapan saja. Halaman ini menjelaskan cara melakukannya dan apa yang terjadi setelahnya.":
    "You have the right to delete your account and personal data at any time. This page explains how, and what happens afterwards.",
  "Cara menghapus akun": "How to delete your account",
  "Di aplikasi: buka Profil, lalu Pengaturan akun, pilih Hapus akun, dan ikuti konfirmasi dengan kode OTP.":
    "In the app: open Profile, then Account settings, choose Delete account, and confirm with the OTP code.",
  "Tanpa aplikasi: gunakan formulir di halaman ini. Masukkan email akun Anda, verifikasi dengan kode OTP, lalu konfirmasi permintaan penghapusan.":
    "Without the app: use the form on this page. Enter your account email, verify with the OTP code, then confirm the deletion request.",
  "Apa yang terjadi setelahnya": "What happens afterwards",
  "Setelah konfirmasi, akun Anda memasuki masa tenggang 14 hari. Selama masa itu Anda dapat membatalkan kapan saja, dan akun tetap dapat digunakan.":
    "After confirmation your account enters a 14-day grace period. During that time you can cancel at any time, and the account remains usable.",
  "Setelah masa tenggang berakhir, data pribadi Anda (profil, alamat, profil dan foto hewan, pesan chat, laporan hewan hilang, serta konten komunitas) dihapus permanen atau dianonimkan, termasuk media yang tersimpan di penyedia penyimpanan kami.":
    "Once the grace period ends, your personal data (profile, addresses, pet profiles and photos, chat messages, lost pet reports, and community content) is permanently deleted or anonymized, including media stored with our storage provider.",
  "Catatan transaksi, pembayaran, dan pemesanan dipertahankan secara teranonim selama kurang lebih 5 tahun untuk kewajiban pembukuan dan perpajakan.":
    "Transaction, payment, and booking records are kept in anonymized form for approximately 5 years for bookkeeping and tax obligations.",
  "Salinan backup terenkripsi terhapus otomatis dalam rotasi hingga 12 bulan, sehingga salinan data Anda mungkin masih ada pada backup selama periode tersebut.":
    "Encrypted backup copies are deleted automatically on a rotation of up to 12 months, so copies of your data may still exist in backups during that period.",
  "Pesan chat Anda ikut dihapus dari sistem kami.":
    "Your chat messages are also deleted from our systems.",
  "Formulir permintaan": "Request form",
  "Untuk mengajukan penghapusan atau membatalkan permintaan penghapusan tanpa aplikasi, gunakan formulir berikut.":
    "To request deletion or cancel a deletion request without the app, use the form below.",
  "Pertanyaan lain": "Other questions",
  "Pelajari data apa yang kami proses pada": "Learn what data we process in",
  "Kebijakan Privasi": "Privacy Policy",
  "atau hubungi privacy@slivadoc.com.": "or contact privacy@slivadoc.com.",
  "Ajukan penghapusan": "Request deletion",
  "Batalkan penghapusan": "Cancel deletion",
  "Masukkan email akun Anda. Kami akan mengirim kode OTP untuk memverifikasi kepemilikan akun sebelum permintaan penghapusan dicatat.":
    "Enter your account email. We will send an OTP code to verify account ownership before the deletion request is recorded.",
  "Masukkan email akun Anda. Kami akan mengirim kode OTP untuk memverifikasi bahwa Anda pemilik akun sebelum permintaan penghapusan dibatalkan.":
    "Enter your account email. We will send an OTP code to verify that you own the account before the deletion request is canceled.",
  "Email akun": "Account email",
  "Kirim kode OTP": "Send OTP code",
  "Memproses…": "Processing…",
  "Konfirmasi penghapusan": "Confirm deletion",
  "Konfirmasi pembatalan": "Confirm cancellation",
  "Kode OTP telah dikirim ke email Anda. Periksa kotak masuk dan folder spam.":
    "The OTP code has been sent to your email. Check your inbox and spam folder.",
  "Permintaan penghapusan akun telah tercatat.":
    "Your account deletion request has been recorded.",
  "Data pribadi Anda akan dihapus permanen setelah masa tenggang 14 hari, yaitu setelah":
    "Your personal data will be permanently deleted after the 14-day grace period, that is, after",
  ". Selama masa tenggang, Anda dapat membatalkan melalui tombol Batalkan penghapusan di halaman ini, di aplikasi, atau melalui Pusat Bantuan.":
    ". During the grace period you can cancel using the Cancel deletion button on this page, in the app, or via the Help Center.",
  "Permintaan penghapusan akun Anda telah dibatalkan. Akun Anda kembali aktif seperti sediakala.":
    "Your account deletion request has been canceled. Your account is active again as before.",
  "Permintaan gagal. Periksa data Anda dan coba lagi.":
    "Request failed. Check your details and try again.",
  "Tidak dapat terhubung ke server. Periksa koneksi Anda dan coba lagi.":
    "Could not reach the server. Check your connection and try again.",
  "Bahasa halaman": "Page language",
  "privacy@slivadoc.com": "privacy@slivadoc.com",
  // Klinik & Petshop directory
  "Klinik & Petshop": "Clinics & Pet Shops",
  "Ganti lokasi": "Change location",
  "Klinik hewan dan petshop terdekat dari lokasimu.": "Veterinary clinics and pet shops nearest to your location.",
  "LOKASIMU": "YOUR LOCATION",
  "Belum dipilih": "Not selected",
  "Peta": "Map",
  "Sedang tutup": "Closed now",
  "Buka sekarang": "Open now",
  "Jam belum diatur": "Hours not set",
  "Petshop": "Pet shop",
  "Posisimu": "Your position",
  "Rating toko": "Store rating",
  "Rata-rata dari semua cabang": "Average across all branches",
  "Rata-rata semua cabang": "Average of all branches",
  "Belum ada rating": "No ratings yet",
  "Tampilan hasil": "Result view",
  "Jenis tempat": "Place type",
  "Cari nama klinik atau petshop": "Search clinic or pet shop name",
  "Semua jarak": "Any distance",
  "Radius (pilih lokasi)": "Radius (choose a location first)",
  "Memuat klinik dan petshop": "Loading clinics and pet shops",
  "Klinik dan petshop belum dapat dimuat": "Clinics and pet shops could not be loaded",
  "Periksa koneksimu, lalu coba lagi.": "Check your connection, then try again.",
  "Tidak ada yang cocok dengan filtermu": "Nothing matches your filters",
  "Belum ada klinik atau petshop": "No clinics or pet shops yet",
  "Coba ubah jenis, radius, atau kata kunci pencarian.": "Try changing the type, radius, or search keywords.",
  "Klinik dan petshop yang sudah terverifikasi akan muncul di sini.": "Verified clinics and pet shops will appear here.",
  "Daftar berikutnya belum dapat dimuat.": "The next page could not be loaded.",
  "Muat lagi": "Load more",
  "Pilih lokasi untuk melihat yang terdekat": "Choose a location to see what is nearest",
  "Tanpa lokasi, daftar diurutkan berdasarkan kota dan nama.": "Without a location, the list is sorted by city and name.",
  "CABANG YANG KAMU PILIH": "THE BRANCH YOU CHOSE",
  "Cabang yang dipilih": "Selected branch",
  "Stok dikirim dari cabang terdekat yang tersedia": "Stock ships from the nearest branch that has it",
  "Pilih lokasi agar urutannya dari yang terdekat": "Choose a location to sort from the nearest",
  "Pet clinic dan petshop belum dapat dimuat.": "Pet clinics and pet shops could not be loaded.",
  "Belum ada pet clinic atau petshop yang terdaftar.": "No pet clinics or pet shops registered yet.",
  "Masuk untuk mencari alamat. Lokasi perangkat dan pin di peta tetap bisa dipakai tanpa akun.": "Sign in to search for an address. Device location and map pin still work without an account.",
  "Ketuk penanda untuk melihat tempatnya.": "Tap a marker to see the place.",
  "Titik di peta": "Map point",
  "Lokasi perangkat": "Device location",
};
