export const englishExtra: Record<string, string> = {
  "AKUN & PERAWATAN": "ACCOUNT & CARE",
  "Akun & perawatan": "Account & care",
  "Yuk, bikin hari pet-mu makin sehat dan happy.": "Let's make your pet's day healthier and happier.",
  "Terdekat": "Nearby",
  "1 catatan": "1 record",
  "Tambah profil hewan": "Add pet profile",
  "Anggota keluarga baru": "New family member",
  "Nama pet": "Pet name",
  "Nama spesies": "Species name",
  "Nama ilmiah": "Scientific name",
  "Simpan profil hewan": "Save pet profile",
  "Berat badan (kg)": "Weight (kg)",
  "Belum diketahui": "Unknown",
  "Profil hewan berhasil disimpan": "Pet profile saved successfully",
  "Pet dalam keluargamu": "Pets in your family",
  "Belum ada profil pet. Tambahkan pet untuk mulai menggunakan layanan.": "No pet profile yet. Add a pet to start using services.",
  "Berat harus berupa angka nol atau lebih dalam kg.": "Weight must be a number of zero or more in kg.",
  "Tanggal lahir harus valid dan tidak boleh di masa depan.": "Date of birth must be valid and cannot be in the future.",
  "Katalog spesies belum tersedia. Coba lagi.": "The species catalogue is not available yet. Try again.",
  "Katalog spesies belum dapat dimuat. Coba lagi.": "Unable to load the species catalogue. Try again.",
  "Pet sudah tersimpan. Muat ulang profil untuk melanjutkan.": "Your pet has been saved. Refresh the profile to continue.",
  "Muat ulang profil": "Refresh profile",
  "Cari pilihan": "Search options",
  "Pilihan tidak ditemukan.": "No matching options found.",
  "Ras (opsional)": "Breed (optional)",
  "Nama ilmiah (opsional)": "Scientific name (optional)",
  "Tanggal lahir (opsional)": "Date of birth (optional)",
  "Berat badan (kg, opsional)": "Weight (kg, optional)",
  "Nama pet *": "Pet name *",
  "Jenis hewan *": "Species *",
  "Nama spesies *": "Species name *",
  "Memuat dokter…": "Loading vets…",
  "Dokter belum dapat dimuat.": "Unable to load vets.",
  "Belum ada dokter yang tersedia.": "No vets are available yet.",
  "Informasi belum dapat dimuat": "Unable to load information",
  "Periksa koneksi internet lalu coba lagi.": "Check your internet connection and try again.",
  "Belum ada program pada kategori ini": "No programs in this category yet",
  "Pilih kategori lain atau kembali lagi untuk melihat program terbaru.": "Choose another category or come back for new programs.",
  "Belum ada event mendatang": "No upcoming events yet",
  "Event yang tersedia akan muncul di sini. Cek kembali untuk kegiatan bersama pet-mu.": "Available events will appear here. Check back for activities with your pet.",
  "Muat ulang": "Refresh",
  "Tutup komentar": "Close comments",
  "Trainer sesuai jenis pet": "Trainers for your pet's species",
  "Pilih spesialis yang paling cocok sebelum menentukan kelas.": "Choose the right specialist before selecting a class.",
  "Kebutuhan pet, lengkap.": "Everything your pet needs.",
  "Mulai pet passport adopsi": "Create an adoption pet passport",
  "Mulai pet passport": "Create a pet passport",
  "Foto buku vaksin · wajib": "Vaccination record photo · required",
  "Foto buku vaksin": "Vaccination record photo",
  "Tanggal lahir / menetas (opsional)": "Birth / hatch date (optional)",
  "Belum ada slot dalam 14 hari. Pilih paket chat atau trainer lain.": "No slots are available in the next 14 days. Choose a chat package or another trainer.",
  "Belum ada slot untuk 14 hari ke depan. Pilih paket chat atau trainer lain.": "No slots are available in the next 14 days. Choose a chat package or another trainer.",
  "Belum ada slot dokter untuk 14 hari ke depan. Pilih paket chat atau dokter lain.": "No veterinarian slots are available in the next 14 days. Choose a chat package or another veterinarian.",
  "Semua kebutuhan anabul, lebih mudah ditemukan": "Find everything your pet needs more easily",
  "Temukan teman anabul di sekitarmu": "Find nearby pet friends",
  "Pet yang akan sekolah": "Pet attending the class",
  "Sudah": "Yes",
  "Pengajuan + biaya tetap. Tanpa lelang.": "Application + fixed fee. No bidding.",
  "Belajar bersama. Bertumbuh bersama.": "Learn together. Grow together.",
  "Semua kebutuhan anabul": "Everything your pet needs",
  "Pilih file": "Choose file",
  "Belum ada file dipilih": "No file selected",
  "Pilih file untuk melanjutkan.": "Choose a file to continue.",
  "Kolom ini wajib diisi.": "This field is required.",
  "Masukkan format data yang valid.": "Enter a valid value.",
  "Pilih tanggal/jam yang valid sesuai batas jadwal.": "Choose a valid date/time within the schedule limits.",
  "Pilih salah satu opsi untuk melanjutkan.": "Choose an option to continue.",
  "Cari pilihan…": "Search options…",
  "Pilihan tidak ditemukan. Coba kata lain.": "No options found. Try another search.",
  "Makanan kucing": "Cat food",
  "Makanan anjing": "Dog food",
  "Makanan hewan": "Pet food",
  "Kandang hewan": "Pet cages",
  "Aksesoris hewan": "Pet accessories",
  "Grooming Kucing": "Cat Grooming",
  "Grooming Anjing": "Dog Grooming",
  "Klinik hewan": "Veterinary clinic",
  "Dokter hewan": "Veterinarian",
  "Vaksin hewan": "Pet vaccination",
  "Mau manjain pet-mu dengan apa? ✨": "How would you like to treat your pet? ✨",
  "Cari di seluruh Slivadoc": "Search all of Slivadoc",
  "Kalender Slivadoc": "Slivadoc Calendar",
  "Pilih tanggal": "Choose a date",
  "Pilih jam": "Choose a time",
  "Pilih tahun": "Choose a year",
  "Bulan": "Month",
  "Tahun": "Year",
  "Jam": "Hour",
  "Menit": "Minute",
  "Bulan sebelumnya": "Previous month",
  "Bulan berikutnya": "Next month",
  "Kosongkan": "Clear",
  "Tutup galeri": "Close gallery",
  "Buka daftar chat": "Open chats",
  "Kota": "City",
  "Memuat percakapan…": "Loading conversation…",
  "ulasan": "reviews",
  "Jenis kelamin": "Sex",
  "sesi": "sessions",
  "Toko": "Shop",
  "Dokter Hewan": "Veterinarian",
  "Sterilisasi": "Spaying / neutering",
  "Jantan": "Male",
  "Betina": "Female",
  "Kirim": "Send",
  "Gambar sebelumnya": "Previous image",
  "Gambar berikutnya": "Next image",
  "Membalas": "Replying",
  "Foto sebelumnya": "Previous photo",
  "Foto berikutnya": "Next photo",
  "Chat toko": "Store chat",
  "produk": "products",
  "Memuat lamaran…": "Loading applications…",
  "konsultasi": "consultations",
  "Rating tertinggi": "Highest rated",
  "poin": "points",
  "Bisa dibatalkan hingga": "Can be cancelled up to",
  "Hemat": "Save",
  "jam sebelum jadwal": "hours before the scheduled time",
  "Nama penerima": "Recipient name",
  "Bagikan": "Share",
  "Memuat komentar…": "Loading comments…",
  "Tutup chat": "Close chat",
  "Valid sampai": "Valid until",
  "Tentang": "About",
  "Foto belum tersedia": "No photos available",
  "Spesialisasi": "Specialty",
  "tahun": "years",
  "Mulai": "Start",
  "Sudah vaksin": "Vaccinated",
  "Mulai segera": "Start now",
  "Pilih jadwal": "Choose a schedule",
  "menit": "minutes",
  "tamu": "guests",
  "terdaftar": "registered",
  "· otomatis": "· automatic",
  "Satu dunia untuk setiap langkah kecilnya.": "One world for every little step.",
  "Menyiapkan ruang pet-mu": "Preparing your pet's space",
  "Ditambahkan ke keranjang": "Added to cart",
  "Navigasi utama": "Main navigation",
  "Menyinkronkan pesan dan status toko terbaru.": "Syncing the latest messages and store status.",
  "Lihat profil": "View profile",
  "Profil": "Profile",
  "Tanggal lahir": "Date of birth",
  "Warna": "Color",
  "CATATAN KHUSUS": "SPECIAL NOTES",
  "Role akses": "Access role",
  "Radius notifikasi": "Notification radius",
  "Paling direkomendasikan": "Recommended",
  "Jarak terdekat": "Nearest",
  "Harga terendah": "Lowest price",
  "Urutkan berdasarkan": "Sort by",
  "hasil": "results",
  "PENGINGAT PERAWATAN": "CARE REMINDER",
  "Jenis perawatan": "Care type",
  "Pengulangan": "Repeat",
  "Target respons": "Response target",
  "Pengiriman": "Delivery",
  "Pembayaran": "Payment",
  "Privasi & data": "Privacy & data",
  "(opsional)": "(optional)",
  "ALAMAT PENGIRIMAN": "DELIVERY ADDRESSES",
  "Memuat alamat tersimpan…": "Loading saved addresses…",
  "DATA AKUN": "ACCOUNT DETAILS",
  "Edit profil pet parent": "Edit pet parent profile",
  "Tutup detail layanan": "Close service details",
  "Tidak jadi": "Cancel",
  "DOKUMEN TRANSAKSI": "TRANSACTION DOCUMENTS",
  "Tutup invoice": "Close invoice",
  "Untuk siapa booking ini?": "Who is this booking for?",
  "Menyinkronkan jadwal cabang…": "Syncing branch schedules…",
  "Sisa": "Remaining",
  "Periksa sekali lagi": "Review once more",
  "Catatan:": "Note:",
  "Alamat pengiriman": "Delivery address",
  "Jenis hewan": "Animal type",
  "Balas": "Reply",
  "Visibilitas": "Visibility",
  "dari 5": "out of 5",
  "Kunjungi toko": "Visit store",
  "TANYAKAN PRODUK INI": "ASK ABOUT THIS PRODUCT",
  "Mulai obrolan dengan toko": "Start a store conversation",
  "Buka pilihan chat": "Open chat options",
  "Tulis pesan ke toko…": "Write a message to the store…",
  "Pesan untuk toko": "Message to the store",
  "Menyiapkan etalase toko…": "Loading store listings…",
  "Etalase belum dapat dibuka": "Store listings are unavailable",
  "LAYANAN PARTNER": "PARTNER SERVICES",
  "Belum ada ulasan toko": "No store reviews yet",
  "Urutkan": "Sort",
  "Reset filter": "Reset filters",
  "Spesies": "Species",
  "Anjing": "Dog",
  "Kucing": "Cat",
  "Jarak": "Distance",
  "SUKA": "LIKE",
  "LEWATI": "PASS",
  "Lihat detail pet & owner": "View pet & owner details",
  "Bandingkan dengan": "Compare with",
  "Jarak maksimum": "Maximum distance",
  "Klinik / rumah sakit": "Clinic / hospital",
  "Nama dokter": "Veterinarian name",
  "PEMBAYARAN · QRIS": "PAYMENT · QRIS",
  "Belum ada lamaran masuk.": "No applications received yet.",
  "Catatan untuk pelamar (opsional)": "Note for the applicant (optional)",
  "Lihat paket": "View packages",
  "Pilih cara konsultasi": "Choose a consultation method",
  "hari": "days",
  "Rumah baru. Cerita bahagia berikutnya.": "A new home. The next happy chapter.",
  "Sudah steril": "Spayed / neutered",
  "PILIHAN": "OPTIONS",
  "HARI KERJA": "BUSINESS DAYS",
  "Slot jadwal ·": "Schedule slot ·",
  "Total paket": "Package total",
  "Kota domisili": "City of residence",
  "Karakter (pisahkan koma)": "Traits (separated by commas)",
  "Status vaksin": "Vaccination status",
  "Belum dikonfirmasi": "Unconfirmed",
  "Pengajuan terkirim": "Application submitted",
  "BIAYA ADOPSI TETAP": "FIXED ADOPTION FEE",
  "← Kembali ke pet passport": "← Back to pet passport",
  "Waktu story": "Story duration",
  "Hubungi tempat": "Contact venue",
  "Jam operasional": "Opening hours",
  "Pesan minimal": "Book at least",
  "Maksimal": "Maximum",
  "tamu per reservasi.": "guests per reservation.",
  "dari": "from",
  "PET TRAINER TERVERIFIKASI": "VERIFIED PET TRAINER",
  "Lihat jenis pet berikutnya": "View more pet types",
  "Lihat pet trainer berikutnya": "View more pet trainers",
  "foto": "photos",
  "minggu ·": "weeks ·",
  "slot tersisa": "slots remaining",
  "pet parent terdaftar": "registered pet parents",
  "Radius pencarian": "Search radius",
  "kursi": "seats",
  "Pet yang akan mengikuti kelas": "Pet attending the class",
  "Mulai ikut kelas": "Enroll in class",
  "tahun pengalaman": "years of experience",
  "Jumlah tiket": "Number of tickets",
  "Komentar PetHub": "PetHub comments",
  "Ongkir Lion Parcel": "Lion Parcel shipping",
  "Lihat produk": "View products",
  "Tutup profil trainer": "Close trainer profile",
  "Menyatukan kesehatan, care, aktivitas, dan marketplace pet-mu dalam satu pengalaman yang hangat.": "Bringing your pet's health, care, activity, and shopping together in one welcoming experience.",
  "Menyiapkan pengalaman terbaik…": "Preparing your experience…",
  "Katalog dan jadwal dimuat saat dibutuhkan.": "Catalogues and schedules load when needed.",
  "Buka chat SlivaCare": "Open SlivaCare chat",
  "Transaksi sudah tercatat dan pesanan sedang diproses.": "Your transaction is recorded and your order is being processed.",
  "AKUN PET FAMILY": "PET FAMILY ACCOUNT",
  "Profil pet, rekam medis, booking, komunitas, dan benefit tersinkron aman dalam satu akun.": "Pet profiles, medical records, bookings, community, and benefits are securely synced in one account.",
  "Nomor HP harus diawali 0 dan berisi 9–16 digit": "Phone number must start with 0 and contain 9–16 digits",
  "Wajib berisi huruf, angka, dan simbol": "Must contain letters, numbers, and symbols",
  "Berlaku sejak 26 Agustus 2026": "Effective August 26, 2026",
  "Pet Parent • Akun aktif": "Pet Parent • Active account",
  "Lokasi kamu": "Your location",
  "Cari dokter, layanan, produk...": "Search vets, services, products...",
  "Memuat hasil…": "Loading results…",
  "Ketik minimal 2 karakter untuk mulai mencari.": "Enter at least 2 characters to search.",
  "Tidak ada hasil yang cocok.": "No matching results.",
  "Kategori chat": "Chat category",
  "Sapaan": "Greeting",
  "Pet clinic & petshop terdekat": "Nearby pet clinics & pet shops",
  "Diurutkan dari titik lokasi yang kamu pilih": "Sorted from your selected location",
  "Belum ada pet clinic atau petshop di titik lokasi ini.": "No pet clinics or pet shops at this location yet.",
  "DOKTER TERBAIK": "TOP VETERINARIANS",
  "Teman konsultasi untuk": "A consultation partner for",
  "Dokter terverifikasi dengan rating dan konsultasi terbaik": "Verified veterinarians with top ratings and consultations",
  "Lihat dokter": "View veterinarians",
  "Dokter terbaik sedang disinkronkan.": "Syncing top veterinarians.",
  "REKOMENDASI SLIVADOC": "SLIVADOC RECOMMENDATIONS",
  "Lihat selengkapnya": "View more",
  "Ringkasan kesehatan dan jadwal": "Health and schedule summary",
  "Kondisi": "Condition",
  "Pilih pet aktif": "Choose active pet",
  "Ganti pet aktif": "Change active pet",
  "Ringkasan homepage akan langsung menyesuaikan.": "Your home summary updates immediately.",
  "Kelola semua profil pet": "Manage all pet profiles",
  "Tanya Dokter Hewan 24/7": "Ask a Veterinarian 24/7",
  "Konsultasi online cepat dan ramah": "Quick, friendly online consultations",
  "Belum ada pet di akunmu": "No pets in your account yet",
  "Tambahkan profil pertama untuk mulai menyimpan identitas dan kesehatan.": "Add your first pet profile to save their identity and health information.",
  "· Dibagikan": "· Shared",
  "Tambah hewan": "Add animal",
  "Buat profil untuk anggota keluarga baru": "Create a profile for a new family member",
  "Identitas terverifikasi": "Verified identity",
  "Tampilkan Pet ID": "Show Pet ID",
  "Usia": "Age",
  "Berat terakhir": "Latest weight",
  "Golongan darah": "Blood type",
  "Ringkasan perawatan": "Care summary",
  "Profil kesehatan": "Health profile",
  "Vaksin wajib": "Required vaccines",
  "Buka pusat kesehatan": "Open health center",
  "Akses keluarga": "Family access",
  "Undang co-parent, caregiver, dokter, atau viewer dengan izin terperinci.": "Invite a co-parent, caregiver, veterinarian, or viewer with detailed permissions.",
  "Kelola akses keluarga": "Manage family access",
  "Aktifkan peringatan dan bagikan profil": "Enable alerts and share the profile",
  "ke komunitas sekitar.": "with the nearby community.",
  "Kelola Lost Pet Mode": "Manage Lost Pet Mode",
  "Pindai untuk membuka identitas darurat terverifikasi Slivadoc.": "Scan to open the verified Slivadoc emergency identity.",
  "Nama": "Name",
  "Ras": "Breed",
  "Berat (kg)": "Weight (kg)",
  "Nomor microchip": "Microchip number",
  "Kebutuhan penting": "Essential needs",
  "Contoh: protein ayam": "Example: chicken protein",
  "Perilaku, preferensi, dan catatan medis": "Behavior, preferences, and medical notes",
  "Tuliskan hal yang perlu diketahui dokter, groomer, atau caregiver": "Write what the veterinarian, groomer, or caregiver needs to know",
  "AKSES KELUARGA ·": "FAMILY ACCESS ·",
  "Orang yang dipercaya": "Trusted people",
  "Memuat akses…": "Loading access…",
  "Cabut": "Revoke",
  "Undang anggota": "Invite member",
  "Komunitas radius": "Community within",
  "km sudah menerima laporan dari": "km has received a report from",
  "Terakhir terlihat": "Last seen",
  "Lokasi terakhir": "Last location",
  "Nama tempat / alamat lengkap": "Place name / full address",
  "Kronologi & ciri khusus": "Timeline & distinctive features",
  "Nomor kontak": "Contact number",
  "Imbalan (opsional)": "Reward (optional)",
  "JELAJAHI LAYANAN": "EXPLORE SERVICES",
  "Bandingkan detail layanan, status izin mitra, dan slot aktual di dekatmu.": "Compare nearby service details, partner license status, and available slots.",
  "dari seluruh area layanan Slivadoc": "across Slivadoc service areas",
  "Urutkan layanan": "Sort services",
  "Favorit": "Favorites",
  "Layanan belum ditemukan": "No services found",
  "FILTER JELAJAHI": "EXPLORE FILTERS",
  "Temukan layanan yang pas": "Find the right service",
  "Jenis layanan": "Service type",
  "Tampilkan": "Show",
  "Booking, pesanan, kelas, tiket, reservasi, dan dokumen pet-mu.": "Your pet's bookings, orders, classes, tickets, reservations, and documents.",
  "Status aktivitas": "Activity status",
  "Jenis aktivitas": "Activity type",
  "Buat booking": "Create booking",
  "Arah": "Directions",
  "Butuh layanan lain?": "Need another service?",
  "Booking dokter, grooming, home care, atau hotel dalam beberapa langkah.": "Book a veterinarian, grooming, home care, or boarding in a few steps.",
  "Jelajahi layanan": "Explore services",
  "Invoice klinik & toko": "Clinic & store invoices",
  "Detail invoice": "Invoice details",
  "Rincian item": "Item breakdown",
  "Tidak ada rincian item.": "No item details.",
  "Kembali ke daftar": "Back to list",
  "PUSAT KESEHATAN": "HEALTH CENTER",
  "Dokter terakhir": "Latest veterinarian",
  "Update terakhir": "Last updated",
  "Halaman kesehatan": "Health page",
  "Data medis": "Medical data",
  "Pengingat": "Reminders",
  "Berat terbaru": "Latest weight",
  "Jadwal penting": "Important dates",
  "Tunda": "Snooze",
  "Belum ada pengingat. Tambahkan jadwal vaksin, obat, grooming, atau kontrol berikutnya.": "No reminders yet. Add the next vaccination, medication, grooming, or check-up.",
  "Jenis rekam medis": "Medical record type",
  "Unduh": "Download",
  "Memuat rekam medis": "Loading medical records",
  "Record akan muncul setelah pemeriksaan atau konsultasi untuk": "Records appear after an examination or consultation for",
  "Jadwalkan untuk": "Schedule for",
  "Notifikasi disiapkan 7 hari, 1 hari, dan 2 jam sebelum jadwal.": "Notifications are scheduled 7 days, 1 day, and 2 hours before the appointment.",
  "Vaksinasi": "Vaccination",
  "Obat": "Medication",
  "Obat cacing": "Deworming",
  "Kutu & caplak": "Fleas & ticks",
  "Kontrol dokter": "Veterinary check-up",
  "Judul": "Title",
  "Contoh: Booster rabies": "Example: rabies booster",
  "Tanggal & waktu": "Date & time",
  "Satu kali": "Once",
  "Harian": "Daily",
  "Mingguan": "Weekly",
  "Bulanan": "Monthly",
  "Tiga bulanan": "Every three months",
  "Tahunan": "Yearly",
  "Jarak khusus": "Custom interval",
  "Jarak khusus (hari)": "Custom interval (days)",
  "Dosis, klinik, atau persiapan khusus": "Dosage, clinic, or special preparation",
  "Belum ada balasan.": "No replies yet.",
  "Tulis balasan…": "Write a reply…",
  "Balasan ticket": "Ticket reply",
  "BANTUAN YANG DAPAT DILACAK": "TRACKABLE SUPPORT",
  "Sampaikan kendala tanpa mengulang kronologi.": "Report an issue without repeating the story.",
  "Kaitkan pengaduan ke pesanan atau booking. Nomor ticket, tenggat respons, status, dan penyelesaian tersimpan di akunmu.": "Link your issue to an order or booking. Ticket numbers, response deadlines, status, and resolution are saved in your account.",
  "1 hari kerja": "1 business day",
  "Untuk tanggapan pertama tim Slivadoc.": "For the Slivadoc team's first response.",
  "BUAT PENGADUAN": "CREATE SUPPORT TICKET",
  "Ceritakan kendalanya": "Tell us about the issue",
  "Pesanan": "Orders",
  "Pesanan atau booking terkait": "Related order or booking",
  "Pesanan atau booking terkait (opsional)": "Related order or booking (optional)",
  "Tidak ada referensi": "No reference",
  "Subjek": "Subject",
  "Contoh: Status pengiriman belum berubah": "Example: delivery status has not changed",
  "Kronologi dan hasil yang diharapkan": "Timeline and expected outcome",
  "Jelaskan waktu kejadian, kondisi terakhir, dan bantuan yang kamu butuhkan.": "Describe when it happened, the latest situation, and the help you need.",
  "RIWAYAT BANTUAN": "SUPPORT HISTORY",
  "Status pengaduanmu": "Your ticket status",
  "Memuat ticket…": "Loading tickets…",
  "Penyelesaian": "Resolution",
  "Ditanggapi": "Responded",
  "Belum ada pengaduan. Ticket yang kamu buat akan tampil di sini.": "No support tickets yet. Tickets you create will appear here.",
  "Akun Pet Owner": "Pet Owner account",
  "Sinkron": "Synced",
  "Alamat tersimpan": "Saved addresses",
  "UTAMA": "PRIMARY",
  "Jadikan utama": "Set as primary",
  "Ubah": "Edit",
  "Hapus": "Delete",
  "Belum ada alamat tersimpan. Tambahkan alamat untuk checkout lebih cepat.": "No saved addresses yet. Add an address for faster checkout.",
  "Tambah alamat": "Add address",
  "Buka daftar dan detail update": "Open update list and details",
  "Tinjau notifikasi keamanan akun": "Review account security notifications",
  "Kelola orang tepercaya untuk pet": "Manage trusted people for your pet",
  "Sesi Slivadoc di perangkat ini akan diakhiri. Data dan profil pet tetap aman.": "Your Slivadoc session on this device will end. Your data and pet profiles remain safe.",
  "Tutup edit profil": "Close profile editor",
  "dari lokasi kamu": "from your location",
  "Siap dipesan": "Ready to book",
  "Jadwal dipilih saat booking": "Choose a schedule when booking",
  "INFORMASI LAYANAN": "SERVICE INFORMATION",
  "Yang tersedia untuk pet-mu": "What's available for your pet",
  "Menyinkronkan rincian layanan dari mitra…": "Syncing service details from the partner…",
  "PERSIAPAN & KEBIJAKAN": "PREPARATION & POLICIES",
  "Yang perlu diketahui sebelum booking": "What to know before booking",
  "Pet yang didukung": "Supported pets",
  "Persiapan": "Preparation",
  "Perawatan setelah layanan": "Aftercare",
  "Pembatalan & perubahan jadwal": "Cancellation & rescheduling",
  "Booking lebih tenang bersama Slivadoc": "Book with peace of mind on Slivadoc",
  "Informasi mitra, jadwal, aktivitas, dan status layanan tersimpan dalam satu alur yang mudah dipantau.": "Partner information, schedules, activities, and service status are saved in one easy-to-follow journey.",
  "Pilih jadwal & booking": "Choose schedule & book",
  "Link kelas online": "Online class link",
  "Unduh dokumen": "Download document",
  "· Estimasi:": "· Estimated:",
  "RINGKASAN AKTIVITAS": "ACTIVITY SUMMARY",
  "QR tiket event": "Event ticket QR",
  "jam sebelum jadwal.": "hours before the scheduled time.",
  "Batas pembatalan sudah lewat. Hubungi klinik untuk perubahan.": "The cancellation deadline has passed. Contact the clinic for changes.",
  "Pesanan dapat dibatalkan sebelum penjual memprosesnya.": "Orders can be cancelled before the seller processes them.",
  "Batalkan pesanan ini? Pesanan yang dibatalkan tidak dapat dipulihkan.": "Cancel this order? Cancelled orders cannot be restored.",
  "Retur": "Returns",
  "Alasan retur": "Return reason",
  "Jelaskan kendala pada barang yang diterima (minimal 10 karakter)": "Describe the issue with the received item (at least 10 characters)",
  "Koleksi favoritmu": "Your favorites",
  "Layanan dan produk favorit tersimpan pada akun di semua perangkat.": "Favorite services and products are saved to your account across devices.",
  "Favorit layanan": "Favorite services",
  "Favorit produk": "Favorite products",
  "Belum ada favorit": "No favorites yet",
  "Tekan ikon hati di Jelajahi atau Pet Shop untuk menyimpan pilihan.": "Tap the heart in Explore or Pet Shop to save your favorites.",
  "← Kembali ke semua update": "← Back to all updates",
  "Tandai semua dibaca": "Mark all as read",
  "Tidak ada notifikasi pada kategori ini.": "No notifications in this category.",
  "Tutup notifikasi": "Close notifications",
  "Filter notifikasi": "Filter notifications",
  "Tandai semua sudah dibaca": "Mark all as read",
  "Belum ada notifikasi pada kategori ini.": "No notifications in this category yet.",
  "Jeda video": "Pause video",
  "Putar video": "Play video",
  "Posisi video": "Video position",
  "Aktifkan suara": "Unmute video",
  "Bisukan video": "Mute video",
  "Video belum dapat diputar": "Video could not be played",
  "Beranda": "Home",
  "Komunitas": "Community",
  "Aktivitas": "Activity",
  "Katalog produk, stok, penjual, dan informasi kepatuhan dalam satu alur.": "Browse products, stock, sellers, and compliance details in one place.",
  "Atur profil, pembayaran, keamanan, dan benefit.": "Manage your profile, payments, security, and benefits.",
  "Katalog produk, stok, seller, dan informasi kepatuhan dalam satu alur.": "Browse products, stock, sellers, and compliance details in one place.",
  "Rekomendasi": "Recommended",
  "Terbaru": "Newest",
  "Terlaris": "Best sellers",
  "Harga termurah": "Lowest price",
  "Belanja lebih tenang untuk sahabat terbaikmu.": "Shop with confidence for your best friend.",
  "Bandingkan produk, cek stok asli, baca ulasan pembeli, lalu checkout dari banyak petshop dalam satu keranjang.": "Compare products, check live stock, read buyer reviews, and shop from multiple pet shops in one cart.",
  "MARKETPLACE PET TERINTEGRASI": "INTEGRATED PET MARKETPLACE",
  "produk aktif": "active products",
  "Kategori populer": "Popular categories",
  "PILIHAN UNTUK": "PICKS FOR",
  "Produk terbaik dari partner Slivadoc": "Top products from Slivadoc partners",
  "produk sesuai pilihanmu": "products matching your choices",
  "Status partner transparan": "Transparent partner status",
  "Produk hanya dari bisnis aktif; status izin ditampilkan apa adanya.": "Products come from active businesses, with their actual license status shown.",
  "Data stok langsung": "Live stock data",
  "Ketersediaan mengikuti cabang.": "Availability reflects each branch’s stock.",
  "Ulasan pembeli asli": "Verified buyer reviews",
  "Hanya dari transaksi terbayar.": "Reviews from paid orders only.",
  "Buka keranjang": "Open cart",
  "Last online belum tersedia": "Last online unavailable",
  "Merek": "Brand",
  "Terakhir online belum tersedia": "Last online unavailable",
  "Status izin belum tersedia": "License status unavailable",
  "Retur & garansi": "Returns & warranty",
  "Kebijakan retur belum dicantumkan oleh penjual.": "The seller has not provided a returns policy.",
  "Panduan penggunaan belum dicantumkan oleh penjual.": "The seller has not provided usage instructions.",
  "Belanja terlindungi": "Protected purchases",
  "Pembayaran jelas": "Clear payments",
  "Pengiriman jelas": "Clear delivery details",
  "Jumlah": "Quantity",
  "Dokter Hewan Online": "Online veterinarian",
  "Klinik Hewan": "Veterinary clinic",
  "Grooming Hewan": "Pet grooming",
  "Vaksinasi Hewan": "Pet vaccination",
  "Sliva Points": "Sliva Points",
  "Pembayaran aman": "Secure payments",
  "Stok langsung": "Live stock",
  "Dari sistem partner": "From the partner’s inventory",
  "Asal toko tertera": "Store origin shown",
  "Transaksi ini menghasilkan": "This purchase earns",
  "Petunjuk penggunaan belum dicantumkan oleh penjual.": "The seller has not provided usage instructions.",
  "DIJUAL OLEH": "SOLD BY",
  "Semua komentar berasal dari pembelian yang sudah dibayar.": "All reviews come from paid purchases.",
  "Masuk untuk memberi ulasan": "Sign in to write a review",
  "Tanda Anabul Perlu Segera Dibawa ke Dokter Hewan": "Signs your pet needs urgent veterinary care",
  "Panduan Vaksin Kucing untuk Pet Parent": "Cat vaccination guide for pet parents",
  "Panduan Vaksin Anjing dan Persiapannya": "Dog vaccination guide and preparation",
  "Temukan layanan, produk, panduan, dan area pet care yang relevan sebelum melanjutkan ke aplikasi.": "Find pet care services, products, guides, and areas before opening the app.",
  "Layanan populer": "Popular services",
  "Belanja & panduan": "Shop & guides",
  "Kenali manfaatnya": "Explore the benefits",
  "Untuk pet owner": "For pet owners",
  "Untuk pet clinic & bisnis hewan": "For veterinary clinics & pet businesses"
};
