// Shared, versioned legal copy for the website and native registration flow.
// Preserve earlier accepted texts in legal-history before changing LEGAL_VERSION.
export const LEGAL_VERSION = "2026-10-09";
export const LEGAL_EFFECTIVE_DATE = "9 Oktober 2026";
export type LegalPolicy = "terms" | "privacy";
export type LegalConsent = { terms_accepted: boolean; privacy_accepted: boolean; legal_version: string };
export type LegalSection = { heading: string; body: string };
export type LegalDocument = { title: string; introduction: string; sections: LegalSection[] };

export const legalSources = [
  { title: "UU 11/2008 tentang Informasi dan Transaksi Elektronik (UU ITE)", url: "https://peraturan.bpk.go.id/Details/37589/uu-no-11-tahun2008" },
  { title: "UU 19/2016: Perubahan Pertama UU ITE", url: "https://jdih.komdigi.go.id/produk_hukum/view/id/555/t/undangundang%2Bnomor%2B19%2Btahun%2B2016" },
  { title: "UU 1/2024: Perubahan Kedua UU ITE", url: "https://jdih.komdigi.go.id/produk_hukum/view/id/884/t/undangundang%20nomor%201%20tahun%202024" },
  { title: "UU 27/2022 tentang Pelindungan Data Pribadi (UU PDP)", url: "https://jdih.komdigi.go.id/produk_hukum/view/id/832/t/undangundang%2Bnomor%2B27%2Btahun%2B2022" },
  { title: "PP 71/2019 tentang Penyelenggaraan Sistem dan Transaksi Elektronik", url: "https://jdih.komdigi.go.id/produk_hukum/view/id/695/t/peraturan%2Bpemerintah%2Bnomor%2B71%2Btahun%2B2019" },
  { title: "PP 80/2019 tentang Perdagangan Melalui Sistem Elektronik", url: "https://jdih.kemendag.go.id/peraturan/peraturan-pemerintah-nomor-80-tahun-2019-tentang-perdagangan-melalui-sistem-elektronik" },
  { title: "UU 8/1999 tentang Perlindungan Konsumen", url: "https://peraturan.bpk.go.id/Read/33784/UU%20Nomor%208%20Tahun%201999.pdf" },
  { title: "UU 28/2014 tentang Hak Cipta", url: "https://peraturan.go.id/id/uu-no-28-tahun-2014" },
  { title: "UU 18/2009 tentang Peternakan dan Kesehatan Hewan beserta perubahannya", url: "https://peraturan.go.id/id/uu-no-18-tahun-2009" },
  { title: "UU 21/2019 tentang Karantina Hewan, Ikan, dan Tumbuhan", url: "https://peraturan.go.id/files/uu-no-21-tahun-2019.pdf" },
  { title: "PP 29/2023: Pelaksanaan UU Karantina Hewan, Ikan, dan Tumbuhan", url: "https://peraturan.go.id/id/pp-no-29-tahun-2023" },
  { title: "PP 17/2025 tentang Tata Kelola Penyelenggaraan Sistem Elektronik dalam Pelindungan Anak", url: "https://peraturan.go.id/files/pp-no-17-tahun-2025.pdf" },
  { title: "Permenkomdigi 9/2026: Pelaksanaan PP 17/2025 tentang Pelindungan Anak", url: "https://jdih.komdigi.go.id/produk_hukum/view/id/1007/t/peraturan%2Bmenteri%2Bkomunikasi%2Bdan%2Bdigital%2Bnomor%2B9%2Btahun%2B2026" },
] as const;

function section(heading: string, ...paragraphs: string[]): LegalSection {
  return { heading, body: paragraphs.join("\n\n") };
}
export const legalParagraphs = (value: LegalSection) => value.body.split("\n\n");

const terms: LegalDocument = {
  title: "Syarat dan Ketentuan Slivadoc",
  introduction: "Dokumen ini mengatur hubungan antara pengguna dan PT Sliva Technology Indonesia dalam penggunaan Slivadoc. Baca seluruh bagian, termasuk ketentuan setiap layanan yang Anda pilih. Nomor subbagian digunakan agar hak, kewajiban, transaksi, dan prosedur pengaduan dapat dirujuk secara jelas. Kebijakan Privasi merupakan dokumen terpisah yang juga wajib dibaca pada pendaftaran.",
  sections: [
    section("Penyelenggara, cakupan, dan cara menghubungi kami",
      "Slivadoc diselenggarakan oleh PT Sliva Technology Indonesia, yang dalam dokumen ini disebut Slivadoc atau kami. Pengguna disebut Anda. Ketentuan berlaku untuk situs, aplikasi Pet Owner, akun, fasilitas transaksi, fitur komunitas, dan layanan pendukung yang disediakan melalui Slivadoc, sepanjang dapat diakses di wilayah layanan yang tersedia.",
      "Cakupan layanan meliputi profil pet, keluarga pet, marketplace, booking perawatan, konsultasi, Pet Sitter, Pet Academy, Pet Event, PetSpot, PetHub, adopsi, PAW Dating, Pet Documents, Petship, penggalangan bantuan yang tersedia, serta SlivaCare. Penyebutan fitur tidak menjamin semua fitur tersedia di setiap wilayah, perangkat, atau waktu.",
      "Pertanyaan operasional dan transaksi diajukan melalui Chat Customer Support dalam aplikasi. Permintaan tentang data pribadi dapat dikirim ke privacy@slivadoc.com. Sertakan identitas akun dan nomor aktivitas terkait secara secukupnya; jangan pernah mengirim password, OTP, PIN pembayaran, atau akses ke rekening kepada petugas dukungan."
    ),
    section("Istilah yang digunakan",
      "Akun adalah identitas elektronik untuk mengakses layanan. Pet Parent atau Pet Owner adalah pengguna yang memiliki atau secara sah diberi wewenang merawat hewan. Pet adalah hewan yang profilnya dikelola melalui Slivadoc. Akses keluarga adalah izin terbatas kepada pengguna lain untuk menjalankan fungsi tertentu atas profil pet.",
      "Mitra mencakup toko, klinik, dokter hewan, trainer, groomer, penyedia penitipan, sitter, penyelenggara kegiatan, pengelola tempat, atau pihak penyedia layanan yang ditampilkan. Pesanan, booking, permohonan, dan pendaftaran merupakan jenis transaksi atau aktivitas yang berbeda; masing-masing memiliki status, persyaratan, biaya, dan waktu penyelesaian sendiri.",
      "Konten pengguna mencakup teks, ulasan, foto, video, pesan, lampiran, dan informasi yang dikirim pengguna. Informasi transaksi mencakup rincian barang atau jasa, harga, biaya, waktu, kebijakan pembatalan, dan konfirmasi yang ditampilkan. Hari kalender berbeda dari hari kerja; apabila suatu batas waktu menggunakan hari kerja, penjelasannya mengikuti ketentuan layanan atau aturan yang berlaku."
    ),
    section("Hubungan antar-dokumen dan perlindungan hak pengguna",
      "Ketentuan ini dibaca bersama Kebijakan Privasi, rincian transaksi, dan ketentuan khusus yang disampaikan sebelum Anda menyetujui layanan. Ketentuan khusus dapat menjelaskan jadwal, kebutuhan pet, pembatalan, atau pengiriman, tetapi tidak boleh mengurangi hak yang dilindungi peraturan perundang-undangan.",
      "Apabila terdapat perbedaan, ketentuan hukum yang bersifat wajib didahulukan. Setelah itu, rincian transaksi yang secara khusus Anda setujui berlaku untuk transaksi tersebut sepanjang sah. Kebijakan Privasi mengatur pemrosesan data, sedangkan dokumen ini mengatur penggunaan dan hubungan layanan; keduanya tidak saling menggantikan.",
      "Tidak ada ketentuan yang dimaksudkan untuk mengalihkan seluruh tanggung jawab pelaku usaha, menolak pengembalian atau ganti rugi yang diwajibkan hukum, memaksakan pembuktian yang dilarang, atau mewajibkan Anda menerima perubahan sepihak yang bertentangan dengan Pasal 18 UU Perlindungan Konsumen. Klausula yang tidak sah tidak diberlakukan hanya karena checkbox telah dicentang."
    ),
    section("Kerangka hukum Indonesia",
      "Penggunaan layanan tunduk pada hukum Indonesia, termasuk UU 11 Tahun 2008 tentang Informasi dan Transaksi Elektronik sebagaimana diubah dengan UU 19 Tahun 2016 dan UU 1 Tahun 2024, UU 27 Tahun 2022 tentang Pelindungan Data Pribadi, PP 71 Tahun 2019, PP 80 Tahun 2019, serta UU 8 Tahun 1999 tentang Perlindungan Konsumen.",
      "Ketentuan kekayaan intelektual mengacu antara lain pada UU 28 Tahun 2014 tentang Hak Cipta. Layanan yang melibatkan hewan juga mengikuti aturan peternakan, kesehatan dan kesejahteraan hewan, karantina, konservasi, serta aturan daerah atau tempat tujuan yang relevan. Untuk akses anak, berlaku pula aturan pelindungan anak dalam sistem elektronik sepanjang terkait dengan layanan.",
      "Rujukan UU ITE dalam dokumen ini berkaitan dengan penyelenggaraan sistem, transaksi, bukti elektronik, keamanan, serta penggunaan yang sah. Pencantuman peraturan tidak berarti Slivadoc telah memperoleh seluruh izin, sertifikat, atau persetujuan regulator tertentu. Penilaian izin suatu mitra atau layanan harus merujuk pada dokumen yang memang berlaku untuk kegiatan tersebut."
    ),
    section("Kecakapan, perwakilan, dan penggunaan oleh anak",
      "Pembuatan akun dan transaksi dilakukan oleh orang yang cakap membuat perjanjian menurut hukum yang berlaku. Apabila Anda bertindak untuk badan usaha, organisasi, keluarga, atau pemilik hewan lain, Anda harus memiliki kewenangan yang dapat dipertanggungjawabkan dan tidak boleh mengikat pihak yang tidak memberikan kuasa.",
      "Alur pendaftaran Pet Owner ditujukan kepada pengguna yang dapat mengelola akun dan memberikan persetujuan secara sah. Anak atau pihak yang memerlukan pendampingan tidak boleh menghindari pembatasan dengan mengisi identitas palsu. Orang tua, wali, atau pendamping yang berwenang mengelola pemesanan dan informasi yang diperlukan melalui akun yang sesuai.",
      "Slivadoc dapat meminta klarifikasi kecakapan atau kewenangan bila diperlukan untuk transaksi tertentu, dengan memperhatikan minimalisasi data. Persetujuan wali tidak secara otomatis membolehkan semua fitur untuk anak; pembatasan usia, jenis layanan, dan penilaian risiko menurut aturan pelindungan anak tetap berlaku."
    ),
    section("Persetujuan elektronik dan bukti penerimaan",
      "Sebelum registrasi, Anda wajib membuka Syarat dan Ketentuan serta Kebijakan Privasi secara terpisah, menelusuri masing-masing dokumen sampai akhir, kemudian menekan tombol Saya sudah membaca dan menyetujui. Checkbox terkait baru ditandai setelah tindakan tersebut. Menutup dokumen, mengunjungi halaman, atau tidak memberikan tanggapan bukan persetujuan.",
      "Slivadoc mencatat versi dokumen dan waktu penerimaan yang terhubung dengan akun. Catatan tersebut mendukung pembuktian persetujuan, tetapi tidak menghapus persyaratan keabsahan perjanjian atau hak untuk mempersoalkan kekeliruan dan penyalahgunaan akun. Kontrak elektronik mengikuti prinsip kesepakatan, kecakapan, objek tertentu, dan tujuan yang sah sebagaimana diatur dalam PP 71 Tahun 2019.",
      "Persetujuan ketentuan penggunaan tidak memberikan kuasa tanpa batas untuk seluruh transaksi berikutnya. Pembayaran, penyerahan hewan, akses rumah, publikasi konten, tindakan medis, atau pemrosesan tambahan yang memerlukan persetujuan khusus tetap harus mengikuti konfirmasi pada layanan masing-masing. Persetujuan kebijakan privasi juga bukan persetujuan pemasaran secara otomatis."
    ),
    section("Pendaftaran, verifikasi, dan kebenaran data akun",
      "Nama lengkap, alamat email yang Anda kuasai, nomor telepon yang valid, password, dan kedua persetujuan dokumen merupakan data wajib pada registrasi. Nomor telepon diisi dalam format angka yang diminta. Verifikasi email menggunakan OTP harus diselesaikan untuk aktivasi sesuai alur yang ditampilkan aplikasi.",
      "Anda wajib menggunakan identitas dan kontak yang benar, memperbarui data yang berubah, serta tidak mendaftarkan kontak orang lain tanpa kewenangan. Slivadoc dapat menolak format yang tidak valid, email yang telah terdaftar, permintaan berulang yang berlebihan, atau pendaftaran yang terindikasi menyalahgunakan sistem.",
      "Verifikasi email membuktikan penguasaan akses email pada saat verifikasi; hal tersebut bukan pengesahan seluruh identitas, kepemilikan hewan, kemampuan membayar, maupun kualifikasi profesional. Apabila kehilangan akses kontak, gunakan dukungan resmi dan ikuti pemeriksaan yang proporsional untuk pemulihan."
    ),
    section("Password, OTP, perangkat, dan keamanan akun",
      "Gunakan password yang memenuhi aturan keamanan pada formulir, tidak mudah ditebak, dan tidak dibagikan kepada orang lain. Password disimpan dalam bentuk hash. Penggantian password melalui akun mengharuskan pemeriksaan password lama, pengisian password baru, dan konfirmasi yang sesuai.",
      "Jangan memberikan OTP, token sesi, tautan pemulihan, atau informasi pembayaran rahasia kepada pihak yang mengaku sebagai Slivadoc. Logout dari perangkat bersama, periksa aktivitas yang tidak dikenal, dan laporkan dugaan pengambilalihan akun. Anda dapat diminta login ulang bila sesi kedaluwarsa, dicabut, atau diperlukan pemeriksaan keamanan.",
      "Aktivitas menggunakan akun dapat menjadi petunjuk adanya tindakan pengguna, tetapi bukan bukti mutlak bahwa semua aktivitas dilakukan pemiliknya. Slivadoc akan menilai laporan akses tanpa izin beserta catatan yang relevan. Kewajiban Anda menjaga akun tidak menghapus tanggung jawab Slivadoc atas keamanan sistem yang berada dalam pengendaliannya."
    ),
    section("Profil hewan, kepemilikan, dan akses keluarga",
      "Profil pet harus memuat informasi yang benar sejauh diketahui, termasuk spesies, identitas, kebutuhan khusus, kondisi kesehatan, dan informasi lain yang relevan dengan layanan. Anda harus merupakan pemilik atau pihak yang berwenang mengelola pet. Profil digital tidak dengan sendirinya menjadi sertifikat kepemilikan yang mengikat pihak ketiga.",
      "Ketika mengundang co-parent, caregiver, dokter, atau anggota keluarga lain, pilih peran dan izin sesuai kebutuhan. Penerima akses hanya boleh menggunakan informasi untuk kewenangan yang diberikan. Anda bertanggung jawab memeriksa penerima sebelum mengundang serta mencabut izin jika hubungan atau kewenangannya berakhir.",
      "Pencabutan akses mencegah penggunaan berikutnya sesuai fungsi sistem, tetapi tidak menarik kembali salinan yang telah diperoleh secara sah oleh penerima. Perselisihan kepemilikan, pengasuhan, atau kuasa harus diselesaikan dengan bukti yang tepat. Slivadoc dapat membatasi perubahan yang diperselisihkan untuk mencegah penyalahgunaan selama pemeriksaan."
    ),
    section("Peran Slivadoc dan tanggung jawab mitra",
      "Slivadoc menyediakan sarana penemuan layanan, komunikasi, pengelolaan aktivitas, dan pencatatan transaksi sesuai fitur. Pihak yang menjual barang atau memberikan jasa diidentifikasi pada halaman layanan atau transaksi. Mitra bertanggung jawab atas informasi penawaran, kompetensi, izin yang dipersyaratkan, serta pelaksanaan kewajibannya.",
      "Label terverifikasi, status online, rating, foto, dan riwayat aktivitas menjelaskan informasi tertentu yang tersedia dalam sistem; semuanya bukan jaminan tanpa batas atas karakter, hasil perawatan, keselamatan, atau ketersediaan mitra. Periksa cakupan layanan dan kebutuhan pet sebelum memilih penyedia.",
      "Slivadoc tetap bertanggung jawab atas kewajibannya sendiri sebagai penyelenggara layanan dan tidak menggunakan hubungan dengan mitra untuk meniadakan hak konsumen. Apabila muncul kendala lintas pihak, pengguna dapat meminta bantuan koordinasi melalui dukungan, sementara penilaian tanggung jawab mengikuti peran, bukti, perjanjian, dan hukum."
    ),
    section("Informasi penawaran, harga, dan ketersediaan",
      "Sebelum menyetujui transaksi, periksa nama penyedia, barang atau jasa, spesifikasi, pet yang dipilih, wilayah layanan, jadwal, jumlah, harga, pajak, biaya administrasi, pengiriman, diskon, serta total. Foto dan ilustrasi harus dibaca bersama keterangan tertulis, terutama ukuran, varian, isi paket, dan batasan layanan.",
      "Stok, slot, kuota, dan status online dapat berubah. Barang di keranjang, pesan kepada mitra, atau tampilan jadwal belum selalu berarti stok atau slot telah dipesan. Kepastian pemesanan mengikuti status konfirmasi pada aktivitas terkait, bukan hanya tampilan awal atau notifikasi yang belum diperbarui.",
      "Jika terdapat kesalahan harga atau deskripsi yang material, Slivadoc atau mitra harus memberi penjelasan sebelum meminta Anda menyetujui perubahan. Biaya tambahan tidak boleh dibebankan diam-diam. Apabila transaksi tidak dapat dilaksanakan sesuai kesepakatan, penyelesaian dapat berupa penawaran yang disetujui ulang, pembatalan, atau pengembalian dana sesuai hak yang berlaku."
    ),
    section("Pembuatan pesanan dan status aktivitas",
      "Anda harus memeriksa ringkasan sebelum menekan tombol pemesanan atau pembayaran. Pastikan alamat, kontak penerima, pet, jadwal, kebutuhan khusus, lampiran, dan metode pembayaran sudah benar. Koreksi setelah konfirmasi bergantung pada tahap pemrosesan dan kemampuan penyedia, tanpa menghapus hak atas pembetulan kesalahan sistem.",
      "Status seperti menunggu pembayaran, dikonfirmasi, diproses, perlu revisi, selesai, dibatalkan, dan ditolak memiliki makna sesuai layanan. Tanda bahwa formulir berhasil dikirim tidak otomatis berarti pembayaran berhasil, mitra menerima booking, dokumen terbit, atau layanan telah selesai.",
      "Gunakan nomor pesanan atau aktivitas yang tampil sebagai referensi komunikasi. Hindari mengirim pesanan berulang ketika koneksi lambat; periksa riwayat terlebih dahulu. Jika terjadi duplikasi atau status tidak konsisten, laporkan nomor terkait agar pencocokan dapat dilakukan berdasarkan catatan server dan penyedia pembayaran."
    ),
    section("Pembayaran, konfirmasi, invoice, dan pengembalian dana",
      "Pembayaran hanya dilakukan melalui metode dan tujuan pembayaran yang ditampilkan resmi pada transaksi. Nilai dan masa berlaku instruksi harus diperiksa sebelum membayar. Bukti transfer atau tangkapan layar membantu penelusuran, tetapi konfirmasi pembayaran mengikuti pencocokan dengan penyedia pembayaran dan catatan transaksi.",
      "Invoice dapat mencakup produk toko, layanan klinik, atau gabungan sesuai transaksi yang tercatat. Invoice dan bukti pembayaran memiliki fungsi berbeda. Kesalahan nama, rincian biaya, pelunasan, pengembalian, atau duplikasi invoice dapat diajukan untuk pemeriksaan; perubahan dokumen mengikuti kewenangan penerbit dan kewajiban pencatatan.",
      "Pengembalian dana yang disetujui diproses melalui metode yang sesuai, dengan informasi jumlah, alasan, dan perkembangan yang tersedia. Waktu masuk ke rekening dapat dipengaruhi penyedia pembayaran. Pengguna tidak boleh diminta memberikan PIN atau OTP bank untuk menerima refund; verifikasi rekening hanya boleh menggunakan informasi yang diperlukan.",
      "Pembayaran yang diperselisihkan atau dugaan transaksi tanpa izin harus ditangani melalui dukungan dan penyedia pembayaran dengan bukti yang relevan. Penahanan atau penyesuaian dana harus memiliki dasar yang jelas dan tidak boleh dijadikan alasan untuk menolak seluruh hak konsumen secara otomatis."
    ),
    section("Promosi, voucher, poin, dan keanggotaan",
      "Promosi mengikuti syarat yang ditampilkan sebelum digunakan, seperti periode, kuota, minimum transaksi, produk yang memenuhi syarat, wilayah, batas pemakaian, dan aturan penggabungan. Periksa perubahan total setelah voucher diterapkan. Istilah gratis tidak menghapus biaya lain yang secara jelas diinformasikan dan Anda setujui.",
      "Poin dan tingkat keanggotaan merupakan manfaat program sesuai aturan yang diumumkan, bukan simpanan, uang elektronik, atau investasi kecuali secara tegas dinyatakan dalam produk yang memiliki dasar hukum terkait. Poin tidak otomatis dapat diuangkan atau dipindahtangankan, dan perolehan dari transaksi yang dibatalkan dapat disesuaikan secara wajar.",
      "Pembuatan akun palsu, transaksi rekayasa, pemakaian identitas pihak lain, atau manipulasi referral dapat menyebabkan manfaat terkait dibekukan selama pemeriksaan. Koreksi harus memperhatikan bukti dan hak pengguna untuk meminta penjelasan. Perubahan program tidak boleh membatalkan hak transaksi yang sudah diperoleh secara sah secara sewenang-wenang."
    ),
    section("Marketplace, barang, dan produk yang dibatasi",
      "Penjual wajib menyediakan informasi yang benar mengenai nama, kondisi, ukuran, komposisi atau bahan, masa kedaluwarsa bila relevan, cara penggunaan, dan batasan produk. Pembeli harus memilih produk yang sesuai dengan spesies, umur, ukuran, alergi, dan kebutuhan hewan, serta mengikuti petunjuk penggunaan yang dapat dipertanggungjawabkan.",
      "Barang palsu, hasil kejahatan, produk kedaluwarsa yang dipasarkan seolah layak, bahan berbahaya tanpa izin, dan barang yang dilarang hukum tidak boleh ditawarkan. Produk obat atau layanan yang memerlukan resep, pemeriksaan, atau kewenangan profesional tidak boleh diperlakukan sebagai produk bebas hanya karena tampil di marketplace.",
      "Slivadoc dapat meminta informasi tambahan atau membatasi penawaran yang berisiko. Apabila Anda mencurigai produk tidak aman, hentikan penggunaan bila diperlukan, simpan kemasan serta bukti transaksi, dan laporkan kepada dukungan atau mitra. Untuk reaksi kesehatan pada hewan, hubungi dokter hewan tanpa menunggu penyelesaian pengaduan komersial."
    ),
    section("Pengiriman, penerimaan, dan kegagalan serah terima",
      "Alamat, kode pos, kontak penerima, titik lokasi, dan petunjuk akses harus cukup jelas bagi pengirim. Estimasi waktu pengiriman bukan janji tanggal mutlak kecuali secara khusus dijamin dalam penawaran. Pembatasan wilayah, jenis barang, cuaca, akses lokasi, dan proses penyedia pengiriman dapat memengaruhi pelaksanaan.",
      "Saat menerima barang, periksa jumlah, kondisi luar, dan kesesuaian pesanan secara wajar. Foto atau video dapat membantu pembuktian, tetapi tidak boleh dijadikan satu-satunya syarat yang menghapus hak konsumen atas barang cacat atau tidak sesuai. Laporkan masalah dengan nomor pesanan dan uraian yang dapat diverifikasi.",
      "Untuk alamat keliru, penerima tidak dapat dihubungi, penolakan tanpa penjelasan, kehilangan, atau kerusakan dalam perjalanan, tanggung jawab dan biaya diperiksa berdasarkan penyebab serta aturan yang telah diinformasikan. Biaya pengiriman ulang yang sah harus dijelaskan sebelum dikenakan. Jangan mengirim hewan hidup melalui layanan pengiriman barang yang tidak mengizinkannya."
    ),
    section("Keluhan barang, retur, garansi, dan ketidaksesuaian",
      "Barang salah kirim, rusak, cacat tersembunyi, tidak sesuai deskripsi, atau layanan yang tidak memenuhi kesepakatan dapat diajukan untuk pemeriksaan. Sertakan rincian transaksi, deskripsi masalah, waktu diketahui, dan bukti yang tersedia. Jangan membuang barang atau kemasan yang masih diperlukan untuk pemeriksaan, sepanjang aman untuk disimpan.",
      "Pilihan penyelesaian dapat berupa perbaikan, penggantian, pemenuhan kekurangan, pengurangan harga yang disepakati, pengembalian dana, atau bentuk ganti rugi yang sesuai hukum. Ketentuan garansi produsen dan alasan kebersihan untuk produk tertentu tidak boleh dipakai untuk menghapus hak atas cacat atau kesalahan penjual.",
      "Batas pengajuan, kondisi pengembalian, alamat retur, dan pembebanan ongkos harus diinformasikan secara jelas dan mematuhi UU Perlindungan Konsumen serta ketentuan PMSE yang berlaku. Apabila tombol pengaduan sudah tidak tersedia, Anda tetap dapat menghubungi dukungan; batas pada antarmuka tidak dengan sendirinya menghapus hak hukum."
    ),
    section("Booking, penjadwalan, keterlambatan, dan pembatalan",
      "Booking mengikuti ketersediaan mitra, lokasi, durasi, pet, persyaratan kesehatan, dan kebutuhan khusus yang disampaikan. Permintaan perubahan jadwal harus diajukan sedini mungkin. Jadwal baru berlaku setelah dikonfirmasi; mengirim pesan atau memilih tanggal alternatif belum selalu mengubah booking yang sedang berjalan.",
      "Ketentuan pembatalan, biaya pembatalan, ketidakhadiran, keterlambatan, dan uang muka harus ditampilkan sebelum konfirmasi. Biaya hanya dapat dikenakan sejauh sah, wajar, dan sesuai informasi yang disetujui. Keadaan darurat, kesalahan sistem, atau ketidakmampuan mitra memenuhi layanan perlu diperiksa berdasarkan fakta masing-masing.",
      "Apabila mitra membatalkan atau gagal hadir, pengguna berhak memperoleh penjelasan dan pilihan penyelesaian yang sesuai, termasuk penjadwalan ulang atau pengembalian atas layanan yang tidak diterima. Perubahan penyedia, paket, lokasi, atau total biaya yang material memerlukan persetujuan Anda, bukan dianggap diterima karena Anda tidak segera menanggapi."
    ),
    section("Klinik, dokter hewan, konsultasi, dan keputusan medis",
      "Informasi profil dokter dan klinik membantu pemilihan penyedia, tetapi pengguna perlu memperhatikan jenis layanan dan kewenangan yang diperlukan. Diagnosis, resep, tindakan, pemeriksaan, serta keputusan klinis hanya dapat diberikan oleh pihak yang berwenang sesuai ketentuan profesi dan peraturan kesehatan hewan.",
      "Konsultasi melalui teks, suara, atau video memiliki keterbatasan karena dokter mungkin tidak dapat memeriksa hewan secara langsung. Sampaikan gejala, riwayat, obat, alergi, dan perubahan kondisi dengan jujur. Dokter dapat menyarankan pemeriksaan langsung, pemeriksaan penunjang, atau rujukan; keberhasilan pengobatan tidak dapat dijamin hanya melalui percakapan aplikasi.",
      "Persetujuan atas aplikasi bukan persetujuan untuk seluruh tindakan medis. Tindakan, risiko, biaya, serta penggunaan obat memerlukan penjelasan dan persetujuan sesuai layanan. Untuk hewan sulit bernapas, kejang, cedera berat, keracunan, atau kondisi gawat lain, segera hubungi fasilitas veteriner; jangan menunggu balasan chat atau proses administrasi Slivadoc."
    ),
    section("SlivaCare, asisten AI, dan informasi edukasi",
      "SlivaCare dapat menggunakan model kecerdasan buatan untuk menjawab pertanyaan dan membantu memahami informasi umum. Jawaban dapat tidak lengkap, keliru, tidak mutakhir, atau tidak sesuai keadaan pet tertentu. Informasi tersebut tidak merupakan pemeriksaan, diagnosis pasti, resep, atau jaminan hasil kesehatan.",
      "Periksa informasi penting dengan dokter hewan atau sumber yang dapat dipercaya sebelum melakukan tindakan yang berdampak pada keselamatan, pemberian obat, dosis, atau perubahan perawatan. Jangan memasukkan password, OTP, nomor kartu, data identitas manusia, atau dokumen pihak lain yang tidak diperlukan ke dalam percakapan AI.",
      "Pengiriman pesan ke fitur AI melibatkan pemrosesan konteks yang relevan sebagaimana dijelaskan dalam Kebijakan Privasi. Anda tetap bertanggung jawab menilai kesesuaian penggunaan jawaban, sementara Slivadoc tetap memiliki kewajiban atas desain layanan, penjelasan keterbatasan, dan pemrosesan data yang berada dalam pengendaliannya."
    ),
    section("Grooming, penitipan, pelatihan, dan perawatan nonmedis",
      "Sebelum layanan dimulai, sampaikan kondisi kulit, luka, parasit, alergi, ketakutan, perilaku agresif, status vaksinasi yang relevan, obat, serta kebiasaan makan pet. Persyaratan penerimaan dan fasilitas harus dijelaskan oleh mitra. Pet dengan risiko penularan atau kebutuhan di luar kemampuan fasilitas dapat memerlukan penilaian atau rujukan lebih dahulu.",
      "Ruang lingkup grooming, penitipan, atau training mengikuti paket yang disepakati. Pemotongan sangat pendek, perubahan metode, penambahan waktu, penggunaan produk khusus, atau biaya ekstra yang material harus dijelaskan. Tindakan medis dan penggunaan sedasi tidak dianggap termasuk dalam persetujuan umum untuk grooming atau penitipan.",
      "Waktu antar-jemput, barang bawaan, makanan, instruksi obat, dan kontak darurat perlu dicatat. Apabila timbul cedera, hewan hilang, dugaan kekerasan, atau kondisi kesehatan memburuk, prioritaskan keselamatan, hubungi pihak terkait, dan simpan kronologi. Penilaian tanggung jawab dilakukan berdasarkan kejadian dan kewajiban masing-masing pihak."
    ),
    section("Pet Sitter, akses rumah, dan instruksi perawatan",
      "Pemesanan Pet Sitter harus menjelaskan jenis layanan harian atau mingguan, tanggal, waktu kunjungan, pet yang dirawat, lokasi, kebutuhan makan, pembersihan, aktivitas, serta kontak darurat. Perubahan jumlah pet, durasi, atau pekerjaan di luar kesepakatan memerlukan pembahasan dan konfirmasi biaya terlebih dahulu.",
      "Untuk kunjungan ke rumah, pemilik hanya memberikan akses yang diperlukan dan menjelaskan area yang boleh dimasuki. Atur penyerahan dan pengembalian kunci secara aman. Kode pintu atau alarm sebaiknya diberikan terbatas dan diganti bila diperlukan. Sitter tidak boleh membawa pihak lain, menggunakan barang pribadi, atau merekam ruang rumah di luar izin yang relevan.",
      "Instruksi obat harus berasal dari pihak yang berwenang dan cukup jelas mengenai nama, dosis, waktu, serta kondisi pemberian. Sitter dapat menolak tindakan yang memerlukan kompetensi medis atau membahayakan. Persetujuan terhadap sitter bukan izin melakukan tindakan veteriner invasif atau mengganti pengobatan atas inisiatif sendiri.",
      "Laporan kunjungan, foto, pembaruan kondisi, dan penilaian penyelesaian digunakan untuk komunikasi perawatan. Foto tidak boleh mengungkap identitas penghuni, alamat lengkap, atau barang pribadi yang tidak relevan. Dalam keadaan darurat, ikuti rencana yang disepakati dan hubungi pemilik atau kontak pengganti; keputusan biaya dan tindakan tetap memperhatikan keselamatan serta kewenangan masing-masing pihak."
    ),
    section("Pet Academy dan materi pembelajaran",
      "Kelas atau program mengikuti deskripsi materi, penyelenggara, tingkat kemampuan, metode, jadwal, bahasa, dan masa akses yang ditampilkan. Informasi edukasi tidak menggantikan evaluasi individual oleh dokter hewan atau trainer yang kompeten. Kebutuhan dan kecepatan belajar setiap hewan berbeda.",
      "Akses materi berbayar diberikan untuk penggunaan pribadi sesuai paket. Jangan membagikan kredensial, merekam atau menjual ulang materi tanpa izin, menghapus pemberitahuan hak cipta, atau mengaku sebagai pemilik materi. Materi yang memang disediakan untuk diunduh tetap tunduk pada batas lisensi yang disampaikan.",
      "Ketentuan kehadiran, pergantian jadwal, tugas, sertifikat partisipasi, dan pembatalan harus dibaca sebelum mendaftar. Sertifikat keikutsertaan bukan otomatis izin praktik, pengakuan profesi, atau jaminan kompetensi. Apabila kelas tidak tersedia sesuai kesepakatan, pengguna dapat mengajukan pemenuhan, penggantian, atau penyelesaian pembayaran yang sesuai."
    ),
    section("Pet Event, tiket, dan keselamatan kegiatan",
      "Tiket mengikuti kategori peserta, jumlah orang dan pet, kuota, lokasi, waktu, serta aturan penyelenggara. Nama peserta, identitas pet, dan persyaratan kesehatan harus diisi dengan benar. Tiket untuk pemilik saja tidak otomatis memberikan hak membawa pet apabila kegiatan memiliki kategori atau pembatasan yang berbeda.",
      "Ikuti aturan leash, carrier, kebersihan, pengawasan, vaksinasi bila diwajibkan, serta pemisahan hewan berisiko. Penyelenggara dapat membatasi keikutsertaan berdasarkan alasan keselamatan yang objektif dan diinformasikan. Pengguna wajib menjaga pet dan menghormati peserta lain; penyelenggara tetap bertanggung jawab atas kewajiban keselamatan acaranya.",
      "Ketentuan transfer tiket, keterlambatan, pembatalan, perubahan tempat, pengembalian, dan dokumentasi harus disampaikan. Kehadiran tidak otomatis memberikan izin tanpa batas untuk penggunaan foto wajah atau identitas dalam iklan. Dokumentasi yang memerlukan persetujuan khusus harus diatur terpisah dari penerimaan syarat pendaftaran."
    ),
    section("PetSpot, Petship, lokasi, dan fasilitas publik",
      "Informasi tempat ramah pet, fasilitas, reservasi, titik bantuan, atau laporan lokasi bersifat membantu perencanaan. Jam operasional, akses, tarif, peraturan membawa hewan, dan kondisi tempat dapat berubah. Konfirmasikan kebutuhan penting kepada pengelola, terutama untuk pet dengan kebutuhan khusus.",
      "Reservasi mengikuti kapasitas, area, rentang waktu, jumlah tamu dan pet, uang muka, serta aturan tempat yang ditampilkan. Jangan memasuki properti privat, mengganggu satwa, merusak fasilitas, atau meninggalkan sampah. Peta dan rute tidak menjamin seluruh jalur aman atau dapat dilalui.",
      "Ketika membuat laporan atau memperbarui titik lokasi, hindari mengungkap alamat rumah, kontak penghuni, atau lokasi hewan yang dapat disalahgunakan. Jangan membuat laporan palsu. Informasi pengguna dapat dimoderasi atau dikoreksi, dan bantuan atau klaim kepemilikan hewan tetap memerlukan pemeriksaan yang layak."
    ),
    section("PetHub, video, siaran, dan akses media",
      "PetHub dan media terkait dapat menyediakan konten rekaman, tayangan langsung, atau informasi visual sesuai layanan yang tersedia. Akses tergantung hak pengguna, izin penyedia, jadwal, jaringan, serta fungsi perangkat. Gangguan tayangan tidak dengan sendirinya membuktikan kondisi fisik hewan atau lokasi tertentu.",
      "Pengguna tidak boleh menyebarkan tayangan terbatas, merekam pihak lain secara melawan hukum, menyiarkan ruang privat tanpa izin, atau menggunakan konten untuk pelecehan. Pemilik fasilitas harus menjelaskan adanya kamera dan batas penggunaannya kepada pihak yang relevan sebelum layanan dilaksanakan.",
      "Fitur panggilan atau siaran yang aktif tidak berarti seluruh komunikasi direkam oleh Slivadoc. Jika suatu layanan menyediakan perekaman, tujuan, pihak yang dapat mengakses, dan ketentuan penyimpanannya harus dijelaskan pada konteks layanan. Izin kamera atau mikrofon perangkat dapat dicabut, dengan konsekuensi fitur terkait mungkin tidak berfungsi."
    ),
    section("Adopsi, pemeriksaan calon adopter, dan serah terima",
      "Pengajuan adopsi merupakan permohonan untuk dinilai oleh pemilik, shelter, atau penyelenggara terkait, bukan hak otomatis memperoleh hewan. Berikan informasi tempat tinggal, pengalaman, kapasitas perawatan, dan alasan adopsi secara jujur. Pihak yang menawarkan hewan harus memiliki kewenangan dan menjelaskan kondisi yang diketahui.",
      "Sebelum serah terima, sepakati identitas hewan, riwayat kesehatan, biaya yang sah bila ada, dokumen, transportasi, tanggung jawab, serta mekanisme tindak lanjut. Biaya tidak boleh digunakan untuk menyamarkan perdagangan hewan yang dilarang. Persetujuan aplikasi tidak menggantikan dokumen pemindahan penguasaan atau kepemilikan yang diperlukan.",
      "Dilarang melakukan kekerasan, penelantaran, penipuan status adopsi, eksploitasi, atau penjualan ulang yang melanggar hukum dan kesepakatan. Bila terdapat masalah kesejahteraan hewan, laporkan dengan bukti yang aman dan relevan. Slivadoc tidak dapat menjamin seluruh pernyataan pihak ketiga, tetapi tetap dapat membantu penanganan laporan sesuai kewenangannya."
    ),
    section("PAW Dating dan pertemuan antar-pet",
      "PAW Dating membantu menemukan profil atau interaksi antar-pet sesuai fitur. Kecocokan dalam aplikasi tidak menjamin kompatibilitas perilaku, kesehatan, genetika, atau keberhasilan pembiakan. Pengguna harus memiliki kewenangan atas pet dan tidak menggunakan fitur untuk kegiatan yang membahayakan hewan.",
      "Sebelum bertemu, bicarakan kondisi kesehatan, vaksinasi, perilaku, ukuran, serta pengawasan yang diperlukan. Pilih lokasi yang aman, gunakan alat pengendali yang sesuai, dan hentikan interaksi jika hewan menunjukkan stres atau agresi. Jangan memberikan alamat privat, data identitas, atau pembayaran kepada pihak yang belum dapat dipercaya.",
      "Setiap keputusan pembiakan memerlukan pertimbangan kesejahteraan, kelayakan medis, serta aturan yang berlaku. Slivadoc tidak menyediakan jaminan kesuburan, keturunan, atau hasil ekonomi. Kesepakatan antarpemilik harus sah dan tidak dapat mengesampingkan kewajiban melindungi hewan."
    ),
    section("Pet Documents, keaslian berkas, dan kewenangan penerbit",
      "Pet Documents memfasilitasi permohonan serta pengiriman persyaratan sesuai produk layanan. Lengkapi identitas pet, pemilik, perjalanan bila diperlukan, dan seluruh lampiran yang diminta. Berkas harus terbaca, benar, relevan, tidak dimanipulasi, dan Anda memiliki hak untuk menyerahkannya.",
      "Unggahan PDF, JPG, atau PNG mengikuti batas ukuran pada aplikasi. Berkas yang berhasil diunggah belum berarti permohonan telah diterima atau dokumen resmi telah diterbitkan. Revisi dapat diminta bila informasi tidak lengkap, tidak sesuai, kedaluwarsa, atau perlu pemeriksaan tambahan; pantau status dan catatan petugas.",
      "Penerbitan sertifikat atau dokumen veteriner dan karantina tetap menjadi kewenangan pihak yang sah menurut jenis dokumen. Bukti permohonan atau dokumen profil buatan platform tidak menggantikan izin pemerintah. Biaya layanan tidak menjamin persetujuan, hasil pemeriksaan, waktu proses otoritas, atau penerimaan di wilayah tujuan.",
      "Untuk perpindahan hewan, pengguna wajib memeriksa persyaratan karantina, kesehatan, maskapai, pelabuhan, dan negara atau daerah tujuan. Jangan mengunggah dokumen palsu, mengubah hasil pemeriksaan, atau menggunakan identitas pet lain. Permohonan yang tidak dapat dilanjutkan diselesaikan menurut tahap layanan, biaya yang telah sah timbul, dan hak konsumen yang berlaku."
    ),
    section("Komunitas, ulasan, pesan, dan laporan pengguna",
      "Berkomunikasilah secara jujur dan menghormati orang lain. Ulasan sebaiknya didasarkan pada pengalaman relevan, tidak dibeli atau direkayasa, dan tidak memuat data pribadi pihak lain. Pendapat negatif, kritik, dan keluhan yang disampaikan secara sah tidak otomatis dianggap pelanggaran hanya karena merugikan citra penyedia.",
      "Dilarang melakukan spam, penipuan, impersonasi, doxing, ancaman, pemerasan, pelecehan, diskriminasi yang melanggar hukum, atau penyebaran konten eksploitasi dan kekerasan. Jangan meminta pengguna mengirim OTP, kredensial, atau pembayaran ke tujuan tidak resmi melalui chat toko maupun pesan komunitas.",
      "Gunakan mekanisme laporan atau dukungan untuk meminta peninjauan. Sertakan tautan, identitas konten, waktu kejadian, dan alasan yang relevan. Slivadoc dapat membatasi akses konten selama pemeriksaan sesuai risiko, menjaga bukti secara proporsional, dan menindaklanjuti permintaan sah dari otoritas tanpa menganggap setiap laporan pasti benar."
    ),
    section("Penggalangan bantuan, donasi, dan informasi penerima",
      "Apabila fitur bantuan atau penggalangan tersedia, penyelenggara kampanye wajib menjelaskan tujuan, penerima manfaat, target, rencana penggunaan, biaya terkait, serta bentuk pelaporan. Pengguna perlu membaca informasi kampanye sebelum memberikan dana dan tidak boleh menganggap semua kampanye diselenggarakan langsung oleh Slivadoc.",
      "Kampanye harus memiliki kewenangan dan memenuhi izin atau persyaratan hukum yang berlaku. Dilarang memakai cerita, foto, diagnosis, atau identitas hewan dan pemilik secara palsu. Informasi penerima manfaat harus dibagikan secukupnya dengan memperhatikan martabat, privasi, dan hak pihak yang bersangkutan.",
      "Ketentuan penyaluran, perubahan tujuan, kampanye yang dihentikan, dugaan penyalahgunaan, dan pengembalian mengikuti informasi yang sah serta hasil pemeriksaan. Kontribusi bukan investasi dan tidak menjanjikan keuntungan. Pernyataan pengurangan pajak atau perlakuan khusus hanya berlaku jika didukung ketentuan serta bukti yang sesuai."
    ),
    section("Hak atas konten dan kekayaan intelektual",
      "Merek, desain, perangkat lunak, teks, materi edukasi, dan aset Slivadoc atau pihak pemberi lisensi dilindungi sesuai hukum. Anda memperoleh hak penggunaan terbatas untuk mengakses layanan secara sah. Hak tersebut tidak mencakup penjualan ulang, peniruan identitas, penghapusan atribusi, atau distribusi materi berbayar tanpa izin.",
      "Anda tetap memiliki hak atas konten milik Anda. Dengan mengunggahnya, Anda memberi izin non-eksklusif sebatas yang diperlukan untuk menyimpan, memproses, menampilkan, mengirimkan, dan menyesuaikan format teknis dalam menjalankan fitur yang dipilih. Izin ini mengikuti pilihan visibilitas dan tidak otomatis mengizinkan penggunaan wajah, merek, atau dokumen pribadi untuk iklan di luar konteks layanan.",
      "Pastikan Anda memiliki izin atas foto, musik, video, dokumen, dan informasi pihak lain. Laporan dugaan pelanggaran hak harus menjelaskan karya atau hak yang dilindungi, konten yang dipermasalahkan, dasar kewenangan pelapor, dan kontak. Penurunan konten serta tanggapan pihak yang diadukan ditangani berdasarkan bukti dan hukum yang berlaku."
    ),
    section("Keamanan sistem dan penggunaan yang dilarang menurut UU ITE",
      "Dilarang mengakses akun atau sistem tanpa hak, mencuri atau memperjualbelikan kredensial, mengubah data orang lain, mengintersepsi komunikasi secara melawan hukum, mengirim malware, mengganggu layanan, atau mengeksploitasi celah untuk memperoleh keuntungan. Pengujian keamanan di luar penggunaan normal harus memiliki izin yang jelas.",
      "Dilarang memanipulasi identitas, dokumen elektronik, status pembayaran, stok, booking, referral, atau hasil layanan untuk menipu. Pengambilan data massal dan penggunaan otomatis yang melanggar kontrol akses, membebani sistem, atau mengungkap data pribadi juga tidak diperbolehkan. Integrasi melalui sarana resmi tetap mengikuti izin dan batas yang ditetapkan.",
      "Pelaporan dugaan celah dapat disampaikan melalui dukungan tanpa menyebarkan data pribadi yang ditemukan. Hentikan akses setelah memperoleh bukti minimum, jangan menyalin basis data, dan jangan mengancam publikasi untuk memaksa imbalan. Penilaian perbuatan melawan hukum dan sanksi merupakan kewenangan pihak yang berwenang, bukan keputusan sepihak platform berdasarkan label UU ITE."
    ),
    section("Pemrosesan data dalam pelaksanaan layanan",
      "Data diproses sesuai Kebijakan Privasi untuk pembuatan akun, penyediaan layanan, transaksi, keamanan, dan kewajiban hukum. Mitra memperoleh data yang relevan dengan layanan yang Anda pilih. Persetujuan dokumen ini tidak mengizinkan Slivadoc atau mitra memanfaatkan semua data untuk tujuan yang tidak berkaitan.",
      "Jika Anda memasukkan data anggota keluarga, penerima barang, kontak darurat, sitter, atau orang lain, Anda harus memiliki dasar yang sah untuk membagikannya dan memberi informasi yang diperlukan kepada pihak tersebut. Jangan mengunggah identitas manusia atau data sensitif yang tidak diminta oleh layanan.",
      "Perubahan profil, akses keluarga, pencabutan izin perangkat, permintaan salinan, pembatasan pemrosesan, dan penghapusan memiliki akibat yang berbeda. Pengguna dapat meminta penjelasan melalui kontak privasi. Penyelesaian hak data tidak boleh dipersulit dengan kewajiban membeli layanan atau menyetujui pemasaran tambahan."
    ),
    section("Pencegahan penipuan, moderasi, dan kesempatan keberatan",
      "Untuk melindungi pengguna dan hewan, Slivadoc dapat memeriksa indikasi akun palsu, transaksi rekayasa, lampiran tidak sah, spam, ancaman keselamatan, atau penyalahgunaan promosi. Pemeriksaan dapat menggunakan catatan aktivitas, laporan, verifikasi tambahan, dan komunikasi dengan pihak terkait sesuai dasar pemrosesan yang sah.",
      "Tindakan dapat berupa permintaan klarifikasi, pembatasan fitur tertentu, penundaan proses, penurunan konten, pembatalan aktivitas yang tidak sah, atau penghentian akses. Tindakan harus proporsional terhadap risiko dan bukti. Dalam keadaan mendesak atau adanya larangan hukum, pembatasan dapat dilakukan sebelum penjelasan lengkap diberikan.",
      "Anda dapat mengajukan keberatan melalui dukungan dengan nomor aktivitas, kronologi, dan bukti yang relevan. Peninjauan harus mempertimbangkan kesalahan identifikasi dan konteks. Pengajuan laporan atau kritik yang sah tidak boleh menjadi alasan pembalasan, dan proses internal tidak menutup hak menghubungi otoritas atau forum penyelesaian sengketa."
    ),
    section("Penghentian akun, transaksi berjalan, dan kewajiban yang tersisa",
      "Anda dapat berhenti menggunakan layanan dan mengajukan penghapusan akun melalui Privasi & keamanan. Alur penghapusan menggunakan verifikasi OTP serta masa tenggang 14 hari untuk membatalkan permintaan sebelum proses penghapusan akun dijalankan. Hak lain atas data pribadi tetap mengikuti Kebijakan Privasi dan tenggat hukum yang berlaku.",
      "Sebelum menutup akun, periksa booking, saldo kewajiban, pengiriman, permohonan dokumen, pengembalian dana, dan akses keluarga. Penutupan tidak dengan sendirinya membatalkan kontrak yang telah sah, menghapus piutang, atau membebaskan mitra dari kewajiban memenuhi layanan dan refund yang masih harus diselesaikan.",
      "Jika akses dihentikan oleh Slivadoc, penyelesaian aktivitas yang sah, pengembalian yang menjadi hak pengguna, dan permintaan data tetap harus tersedia melalui jalur yang sesuai. Catatan tertentu dapat disimpan terbatas untuk kewajiban hukum atau sengketa. Ketentuan mengenai tanggung jawab, bukti transaksi, kerahasiaan, dan penyelesaian sengketa tetap berlaku sejauh diperlukan."
    ),
    section("Ketersediaan layanan, pemeliharaan, dan kesalahan teknis",
      "Layanan bergantung pada perangkat, koneksi, sistem Slivadoc, dan penyedia pendukung. Pemeliharaan, pembaruan aplikasi, batas kapasitas, serta gangguan pihak ketiga dapat memengaruhi akses. Pengguna dianjurkan memakai versi aplikasi yang didukung dan menyimpan referensi transaksi penting yang dapat diakses kembali.",
      "Jika tombol atau status tidak merespons, jangan langsung mengulangi pembayaran berkali-kali. Periksa aktivitas, koneksi, dan notifikasi; hubungi dukungan bila status tetap tidak jelas. Waktu pada perangkat dapat berbeda dari waktu pencatatan server, sehingga penelusuran menggunakan catatan transaksi yang relevan.",
      "Slivadoc berkewajiban menangani gangguan dalam kendalinya sesuai standar dan kewajiban hukum yang berlaku. Pernyataan bahwa sistem dapat mengalami gangguan tidak menghapus hak atas koreksi, informasi, atau penyelesaian kerugian yang menjadi tanggung jawab penyelenggara. Layanan digital ini bukan saluran darurat dengan jaminan respons seketika."
    ),
    section("Tanggung jawab, risiko, dan batas yang diperbolehkan hukum",
      "Setiap pihak bertanggung jawab atas kewajiban, perbuatan, atau kelalaiannya sesuai perjanjian dan hukum. Pengguna wajib memberikan informasi yang benar dan mengikuti instruksi keselamatan yang wajar; mitra wajib memberikan layanan sesuai kewenangan dan penawarannya; Slivadoc wajib menjalankan kewajibannya sebagai penyelenggara.",
      "Hasil perawatan, kesehatan, pelatihan, adopsi, interaksi hewan, atau kinerja pihak ketiga tidak dapat dijamin secara mutlak. Namun, tidak adanya jaminan hasil bukan pembebasan atas penipuan, kesengajaan, kelalaian, pelanggaran data, atau ketidaksesuaian layanan yang menimbulkan tanggung jawab menurut hukum.",
      "Dokumen ini tidak menetapkan penghapusan seluruh tanggung jawab, pembatasan nominal ganti rugi secara sepihak, atau pelepasan hak konsumen yang bersifat wajib. Klaim dinilai berdasarkan hubungan sebab akibat, kerugian yang dapat dibuktikan, pembagian peran, serta putusan atau kesepakatan yang sah. Upaya mengurangi kerugian secara wajar tetap diharapkan dari semua pihak."
    ),
    section("Keadaan kahar dan penanganan hambatan luar biasa",
      "Bencana alam, kebakaran besar, wabah yang berdampak langsung, pembatasan resmi, gangguan infrastruktur luas, atau kejadian lain di luar kendali yang secara wajar tidak dapat dicegah dapat memengaruhi pelaksanaan kewajiban. Suatu kejadian tidak otomatis menjadi keadaan kahar hanya karena meningkatkan biaya atau menyulitkan salah satu pihak.",
      "Pihak terdampak perlu memberi informasi yang layak, menjelaskan kewajiban yang terhambat, dan mengupayakan pemulihan atau alternatif yang masuk akal. Keselamatan pet, penyimpanan barang, komunikasi kepada pengguna, dan penanganan pembayaran harus tetap diperhatikan sesuai keadaan.",
      "Penjadwalan ulang, penghentian, atau pengembalian atas bagian layanan yang belum dipenuhi dibicarakan berdasarkan dampak nyata dan hukum. Keadaan kahar tidak otomatis menghapus kewajiban pembayaran yang telah timbul secara sah, tanggung jawab atas kelalaian sebelumnya, maupun seluruh hak atas dana yang belum digunakan untuk layanan."
    ),
    section("Pengaduan, bukti, dan penyelesaian sengketa",
      "Ajukan pengaduan melalui Chat Customer Support dengan nama atau email akun, nomor transaksi, kronologi singkat, waktu kejadian, dan penyelesaian yang diharapkan. Sertakan bukti yang relevan serta aman dibagikan. Pengaduan data pribadi dapat disampaikan langsung ke privacy@slivadoc.com tanpa harus membuka detailnya kepada pihak yang tidak berkepentingan.",
      "Slivadoc dapat meminta klarifikasi, menghubungi mitra, memeriksa log dan bukti pembayaran, serta memberi pembaruan sesuai hasil pemeriksaan. Anda dapat memperbaiki informasi atau mengirim bukti tambahan. Informasi elektronik dapat digunakan sebagai bukti sesuai UU ITE, tetapi autentisitas, integritas, relevansi, dan hak para pihak untuk membantah tetap diperhatikan.",
      "Penyelesaian secara musyawarah diupayakan tanpa memaksa pengguna melepaskan hak hukum. Apabila tidak tercapai penyelesaian, konsumen tetap dapat menggunakan BPSK, pengadilan yang berwenang, instansi pengawas, atau mekanisme lain yang tersedia menurut hukum. Tidak ada kewajiban arbitrase eksklusif atau forum luar negeri yang dipaksakan melalui dokumen ini."
    ),
    section("Pemberitahuan, perubahan, dan versi ketentuan",
      "Pemberitahuan layanan dapat disampaikan melalui aplikasi atau kontak terdaftar yang relevan. Pastikan kontak tetap dapat diakses. Informasi promosi dibedakan dari pemberitahuan transaksi, keamanan, atau perubahan kontrak yang diperlukan. Penolakan pemasaran tidak otomatis menghentikan pesan penting mengenai layanan yang sedang Anda gunakan.",
      "Perubahan material diberitahukan dengan penjelasan yang memadai dan tanggal berlaku. Apabila perubahan memerlukan persetujuan baru, persetujuan diminta melalui tindakan yang jelas. Kelanjutan penggunaan atau diamnya pengguna tidak dipakai untuk menganggap setuju terhadap pemrosesan data baru yang menurut hukum memerlukan persetujuan terpisah.",
      "Versi yang disetujui dan rincian transaksi menjadi rujukan untuk aktivitas yang telah dibuat, sepanjang tidak bertentangan dengan hukum wajib. Perubahan tidak diterapkan surut untuk mengurangi hak yang telah timbul secara sah. Versi dokumen dicantumkan agar pengguna dapat meminta penelusuran ketentuan yang terkait dengan akunnya."
    ),
    section("Bahasa, keterpisahan klausul, dan pernyataan akhir",
      "Dokumen disediakan dalam Bahasa Indonesia untuk pengguna layanan di Indonesia. Terjemahan, ringkasan, ikon, atau penjelasan singkat membantu pemahaman dan tidak boleh digunakan untuk menyembunyikan ketentuan penting. Apabila ada perbedaan makna, penafsiran memperhatikan teks Indonesia, maksud kesepakatan yang sah, dan hak konsumen.",
      "Jika suatu klausul tidak dapat diberlakukan, klausul lainnya tetap berlaku sejauh dapat dipisahkan secara sah. Tidak dilaksanakannya suatu hak pada satu kesempatan bukan pelepasan otomatis atas hak tersebut. Pengalihan hubungan layanan kepada pihak lain harus memperhatikan hak pengguna, kewajiban transaksi, dan pelindungan data pribadi.",
      "Dengan menekan Saya sudah membaca dan menyetujui setelah mencapai akhir dokumen, Anda menyatakan telah memperoleh kesempatan membaca, memahami pokok hak dan kewajiban, serta menerima ketentuan yang sah pada versi ini. Anda tetap dapat meminta penjelasan dan menggunakan hak yang dilindungi hukum. Rujukan peraturan di bawah disediakan untuk membantu pemeriksaan lebih lanjut."
    ),
  ],
};

const privacy: LegalDocument = {
  title: "Kebijakan Privasi Slivadoc",
  introduction: "Kebijakan ini menjelaskan data pribadi apa yang diproses, dari mana data diperoleh, untuk apa digunakan, kepada siapa diberikan, bagaimana disimpan, serta bagaimana Anda menjalankan hak. Setiap fitur hanya memerlukan data sesuai konteksnya. Membaca dan menyetujui kebijakan ini bukan pemberian izin tanpa batas atas seluruh data, pemasaran, atau pengungkapan kepada pihak mana pun.",
  sections: [
    section("Pengendali data, ruang lingkup, dan kontak privasi",
      "PT Sliva Technology Indonesia bertindak sebagai pengendali data pribadi untuk pemrosesan yang tujuan dan caranya ditentukan oleh Slivadoc. Kebijakan mencakup situs, aplikasi Pet Owner, pendaftaran, dukungan, serta fitur yang dioperasikan Slivadoc. Kebijakan juga menjelaskan pertukaran data yang diperlukan dengan mitra dan penyedia teknologi.",
      "Kirim pertanyaan, permintaan hak, atau keluhan privasi ke privacy@slivadoc.com atau Chat Customer Support dalam aplikasi. Jelaskan jenis permintaan, akun terkait, serta kontak balasan yang aman. Jangan menyertakan password, OTP, PIN bank, atau seluruh salinan identitas pada pengaduan awal jika tidak diperlukan.",
      "Klinik, dokter, toko, sitter, penyelenggara acara, penyedia pembayaran, dan pihak lain dapat memiliki tanggung jawab pemrosesan tersendiri. Peran mereka ditentukan oleh kegiatan yang dilakukan, bukan semata-mata sebutan mitra. Kebijakan pihak tersebut perlu dibaca ketika Anda memakai layanannya; Slivadoc tetap bertanggung jawab atas pemrosesan yang berada dalam pengendaliannya."
    ),
    section("Pengertian data pribadi dan kegiatan pemrosesan",
      "Data pribadi adalah informasi tentang orang perseorangan yang teridentifikasi atau dapat diidentifikasi, baik sendiri maupun ketika digabungkan dengan informasi lain. Pemrosesan mencakup perolehan, pengumpulan, pengolahan, analisis, penyimpanan, perbaikan, penampilan, pengiriman, pengungkapan, penghapusan, dan pemusnahan sesuai konteks layanan.",
      "Informasi pet tidak selalu merupakan data pribadi manusia jika berdiri sendiri. Namun, profil pet, riwayat kunjungan, foto, lokasi, atau dokumen dapat mengidentifikasi pemilik ketika terhubung dengan akun dan kontaknya. Dalam keadaan demikian, hubungan data tersebut diperlakukan sebagai bagian dari pemrosesan data pribadi.",
      "Data yang benar-benar dianonimkan sehingga tidak lagi dapat dikaitkan secara wajar dengan seseorang berbeda dari data yang hanya disamarkan atau diberi kode. Menghapus nama saja belum tentu membuat data anonim. Informasi yang masih dapat dikaitkan kembali dengan akun tetap memerlukan pelindungan dan dasar pemrosesan yang sesuai."
    ),
    section("Landasan hukum dan prinsip pemrosesan",
      "Kebijakan mengacu terutama pada UU 27 Tahun 2022 tentang Pelindungan Data Pribadi, UU ITE beserta perubahan melalui UU 19 Tahun 2016 dan UU 1 Tahun 2024, PP 71 Tahun 2019, serta aturan perdagangan elektronik dan perlindungan konsumen yang relevan. Rujukan pasal menjelaskan hak dan kewajiban, bukan membatasi hak hanya pada pasal yang disebutkan.",
      "Pemrosesan harus memiliki dasar yang sah sesuai Pasal 20 UU PDP, tujuan yang jelas, cakupan yang relevan, serta ukuran yang seimbang. Data perlu akurat, digunakan secara transparan, dilindungi dari akses tanpa hak, dan tidak disimpan lebih lama daripada tujuan atau kewajiban hukumnya.",
      "Dasar yang digunakan dapat berupa pelaksanaan perjanjian atau permintaan sebelum perjanjian, kewajiban hukum, kepentingan sah setelah memperhatikan keseimbangan hak, atau persetujuan spesifik. Dasar kepentingan vital berkaitan dengan keselamatan subjek data manusia dan tidak dipakai secara otomatis hanya karena ada kebutuhan perawatan hewan."
    ),
    section("Kategori data akun dan identitas pengguna",
      "Data akun meliputi nama lengkap, email, nomor telepon, identitas internal akun, status verifikasi, waktu pendaftaran, preferensi bahasa, serta perubahan profil yang diperlukan. Data autentikasi mencakup hash password, catatan verifikasi, sesi, dan informasi yang diperlukan untuk mencegah akses tanpa hak.",
      "Nama penerima, alamat pengiriman, kontak darurat, atau informasi penagihan dapat diminta untuk layanan tertentu. Nomor identitas pemerintah, dokumen kewenangan, atau informasi perwakilan tidak merupakan kolom wajib dalam pendaftaran Pet Owner biasa; jika diperlukan untuk kasus tertentu, tujuan dan batas kebutuhannya harus dijelaskan.",
      "Slivadoc tidak meminta agama, pandangan politik, riwayat kesehatan manusia, atau data biometrik sebagai persyaratan umum membuat akun Pet Owner. Jangan menambahkan informasi tersebut pada nama, bio, chat, atau lampiran jika tidak relevan. Data yang Anda kirim tanpa diminta tetap dapat menimbulkan risiko sehingga pengumpulan harus dibatasi sejak awal."
    ),
    section("Kategori data yang bersifat spesifik dan informasi sensitif",
      "Menurut UU PDP, data pribadi yang bersifat spesifik mencakup antara lain data kesehatan manusia, biometrik, genetika, catatan kejahatan, data anak, dan data keuangan pribadi. Slivadoc membedakan kategori ini dari informasi kesehatan hewan, walaupun keduanya dapat muncul bersama dalam satu berkas atau transaksi.",
      "Riwayat pembayaran, identitas rekening untuk pengembalian, atau informasi anak yang disampaikan melalui dukungan perlu ditangani sesuai kebutuhan dan risikonya. Lampiran foto identitas, isi rumah, kunci, kode akses, dan lokasi kunjungan juga dapat memiliki risiko tinggi meskipun klasifikasi hukumnya berbeda.",
      "Hindari mengunggah data manusia yang tidak diminta, termasuk diagnosis pribadi, foto kartu bank, NIK, atau informasi pihak ketiga yang tidak terkait. Jika dokumen mengandung bagian yang tidak diperlukan, gunakan salinan dengan bagian tersebut disamarkan sepanjang tidak merusak keabsahan atau persyaratan layanan yang sah."
    ),
    section("Sumber perolehan data",
      "Data diperoleh langsung ketika Anda mendaftar, mengisi profil, menambah pet, mengunggah dokumen, memesan layanan, membayar, mengirim pesan, atau meminta bantuan. Data juga dapat berasal dari pilihan izin perangkat, seperti lokasi atau media yang secara aktif Anda pilih untuk dikirim.",
      "Mitra dapat mengirim pembaruan yang berkaitan dengan transaksi Anda, misalnya status booking, invoice, pelaksanaan kunjungan, catatan layanan, atau hasil verifikasi dokumen. Penyedia pembayaran dan pengiriman dapat mengirim referensi, status, serta informasi rekonsiliasi yang diperlukan untuk menyelesaikan layanan.",
      "Anggota keluarga atau pihak yang berwenang dapat memasukkan data Anda sebagai penerima, caregiver, atau kontak darurat. Sistem juga menghasilkan catatan teknis seperti waktu akses dan hasil autentikasi. Jika Anda merasa data diberikan pihak lain tanpa hak, hubungi kami agar asal, tujuan, dan kewenangannya dapat diperiksa."
    ),
    section("Data wajib, data pilihan, dan akibat jika tidak diberikan",
      "Registrasi memerlukan nama lengkap, email, nomor telepon yang valid, password, verifikasi email, serta penerimaan Syarat dan Ketentuan dan Kebijakan Privasi. Tanpa data yang diperlukan dan penerimaan dokumen, akun tidak dapat diaktifkan melalui alur pendaftaran tersebut. Informasi publik tetap dapat dibaca sesuai ketersediaan fitur tamu.",
      "Data tambahan mengikuti kebutuhan layanan: alamat untuk pengiriman, identitas pet untuk perawatan, jadwal untuk booking, serta dokumen persyaratan untuk permohonan. Tidak memberikan data yang benar-benar diperlukan dapat menyebabkan layanan tertentu tidak dapat diproses; hal itu tidak berarti Anda wajib memberikan seluruh data untuk semua fitur.",
      "Foto profil, konten komunitas, izin lokasi perangkat, dan penggunaan asisten AI bergantung pada pilihan fitur. Persetujuan pemasaran, bila diminta, harus terpisah dan tidak menjadi syarat untuk layanan inti yang tidak memerlukannya. Label wajib pada formulir tidak boleh digunakan untuk membenarkan pengumpulan yang berlebihan."
    ),
    section("Pendaftaran, autentikasi, dan pengelolaan sesi",
      "Nama dan kontak digunakan untuk membuat akun, mengirim verifikasi, memberi pemberitahuan layanan, serta membantu pemulihan. Password diproses untuk pemeriksaan autentikasi dan disimpan sebagai hash. OTP merupakan kredensial sementara; kerahasiaannya tetap perlu dijaga meskipun masa berlakunya terbatas.",
      "Aplikasi menyimpan informasi sesi dan preferensi tertentu agar Anda dapat tetap masuk dan melanjutkan navigasi. Catatan login, pembaruan password, kegagalan autentikasi, atau pencabutan sesi digunakan untuk keamanan dan penelusuran insiden. Akses pada perangkat bersama harus diakhiri dengan logout.",
      "Dasar pemrosesan utama adalah penyediaan akun yang Anda minta dan kepentingan sah dalam pengamanan layanan. Permintaan pembaruan data atau pemulihan dapat memerlukan verifikasi tambahan yang proporsional. Kami tidak meminta Anda mengungkapkan password melalui chat atau email untuk membuktikan kepemilikan akun."
    ),
    section("Profil pet dan akses keluarga",
      "Nama pet, spesies, ras, tanggal lahir atau perkiraan usia, jenis kelamin, foto, identitas, serta atribut terkait digunakan untuk menyesuaikan layanan. Ketika profil terhubung dengan pemilik, data tersebut dapat mengungkap kebiasaan, hubungan keluarga, dan riwayat aktivitas pemilik.",
      "Fitur keluarga memproses identitas atau kontak penerima undangan, peran, izin, dan status akses. Anggota yang Anda beri kewenangan dapat melihat atau menggunakan bagian profil, kesehatan, maupun booking sesuai izinnya. Pilih akses minimum yang diperlukan dan periksa kembali bila hubungan pendampingan berubah.",
      "Pencabutan akses berlaku terhadap akses melalui sistem selanjutnya. Salinan yang sudah diterima tidak selalu dapat ditarik kembali, terutama jika penerima memiliki kewajiban pencatatan tersendiri. Jika terdapat sengketa atau akses tidak sah, laporkan pengguna, pet, dan jenis informasi terkait untuk peninjauan."
    ),
    section("Riwayat kesehatan hewan dan konsultasi",
      "Keluhan pet, riwayat perawatan, vaksinasi, alergi, penggunaan obat, hasil pemeriksaan, jadwal, serta catatan konsultasi dapat diproses untuk layanan kesehatan hewan yang Anda pilih. Dokter atau klinik dapat menambahkan informasi layanan sesuai kewenangan dan hubungan perawatan.",
      "Rekam kesehatan hewan yang terhubung dengan akun tetap dapat mengungkap identitas dan aktivitas pemilik. Kami membatasi penggunaannya pada layanan, dukungan, pencatatan yang sah, dan kebutuhan terkait yang dijelaskan. Informasi medis manusia yang tidak relevan sebaiknya tidak dimasukkan ke dalam kolom keluhan hewan.",
      "Klinik atau dokter dapat menjadi pengendali tersendiri untuk pencatatan profesional dan kewajiban hukumnya. Permintaan koreksi catatan medis perlu dibedakan dari perubahan profil biasa agar riwayat layanan tetap akurat. Hubungi penyedia atau dukungan jika diperlukan penjelasan mengenai catatan yang tidak dapat langsung Anda edit."
    ),
    section("Pesanan, booking, pembayaran, invoice, dan pengiriman",
      "Kami memproses barang atau jasa yang dipilih, jumlah, harga, pet, jadwal, alamat, penerima, referensi pembayaran, status transaksi, invoice, pembatalan, serta refund. Data digunakan untuk menyediakan layanan, mencocokkan pembayaran, memenuhi pencatatan, menangani keluhan, dan mencegah transaksi tidak sah.",
      "Penyedia pembayaran menerima informasi yang diperlukan untuk memproses metode yang Anda pilih, sedangkan penyedia pengiriman menerima data penerima dan pengiriman sesuai kebutuhan. Anda tidak boleh diminta menyampaikan PIN atau OTP bank kepada Slivadoc melalui percakapan dukungan. Jangan mengunggah foto kartu pembayaran yang menampilkan informasi rahasia.",
      "Invoice dan data transaksi dapat tetap disimpan setelah akun tidak aktif apabila diwajibkan aturan perdagangan, perpajakan, pembuktian, atau penyelesaian sengketa. Penyimpanan tersebut dibatasi untuk tujuan yang sah dan tidak secara otomatis membolehkan data dipakai kembali untuk pemasaran."
    ),
    section("Pet Sitter, alamat kunjungan, dan informasi rumah",
      "Layanan kunjungan dapat memerlukan alamat, petunjuk akses, waktu, kontak pemilik, kontak darurat, kebiasaan pet, serta instruksi perawatan. Data dibagikan kepada pihak yang melaksanakan layanan sejauh diperlukan untuk memenuhi booking, bukan kepada seluruh sitter hanya karena Anda membuat akun.",
      "Kode pintu, kunci, letak barang, jadwal rumah kosong, atau foto interior dapat menimbulkan risiko keamanan. Bagikan secara terbatas melalui jalur yang disepakati, hindari memasukkannya pada profil publik, dan ubah akses sementara setelah layanan selesai bila memungkinkan. Jangan memberi akses ke ruangan atau perangkat yang tidak diperlukan.",
      "Foto laporan seharusnya berfokus pada pet dan pekerjaan yang relevan. Minta agar wajah penghuni, dokumen di rumah, alamat, dan barang pribadi tidak ikut ditampilkan tanpa alasan yang sah. Penyimpanan laporan mengikuti kebutuhan pelaksanaan, pengaduan, dan retensi terkait; pengguna dapat meminta pemeriksaan atas foto atau informasi yang berlebihan."
    ),
    section("Pet Documents dan lampiran berkas",
      "Unggahan dapat memuat identitas pet, pemilik, riwayat vaksinasi, surat pemeriksaan, perjalanan, tanda tangan, atau informasi penerbit sesuai persyaratan. Berkas digunakan untuk menelaah kelengkapan, memproses permohonan, meminta revisi, dan meneruskan informasi kepada pihak yang berwenang atas layanan tersebut.",
      "Slivadoc menggunakan Cloudinary untuk penyimpanan dan pengiriman media atau dokumen sesuai konfigurasi layanan. Tautan unggahan dapat diakses oleh pihak yang memperoleh tautannya; perlakukan tautan dokumen sebagai informasi rahasia, bukan sebagai konten yang aman dibagikan ke forum publik. Hindari menyertakan data manusia yang tidak dibutuhkan.",
      "Berkas pengganti saat revisi harus tetap berkaitan dengan persyaratan. Riwayat atau lampiran lain dapat diperlukan untuk melanjutkan permohonan dan pembuktian. Jika salah mengunggah dokumen, hubungi dukungan dengan identitas permohonan serta nama berkas tanpa menyebarkan ulang isinya kepada banyak pihak. Penghapusan akun dan penanganan salinan di penyedia layanan perlu ditinjau sesuai cakupan permintaan serta kewajiban yang masih berlaku."
    ),
    section("Lokasi, peta, pencarian, dan laporan tempat",
      "Lokasi dapat berupa kota yang Anda ketik, alamat pengiriman atau kunjungan, titik peta, maupun koordinat perangkat apabila Anda memberikan izin untuk fitur terkait. Lokasi digunakan untuk pencarian tempat, penyesuaian hasil, layanan berbasis wilayah, navigasi, atau laporan yang Anda pilih.",
      "Izin lokasi pada perangkat dapat ditolak atau dicabut. Jika fitur menyediakan pengisian kota atau alamat manual, Anda dapat menggunakannya sebagai alternatif. Penolakan dapat mengurangi ketepatan jarak atau rekomendasi tanpa otomatis membatalkan seluruh akun. Kebijakan ini tidak memberikan izin umum untuk pelacakan lokasi terus-menerus di latar belakang.",
      "Pencarian dan tampilan peta dapat melibatkan Photon, OpenStreetMap, atau penyedia peta yang digunakan layanan. Permintaan dapat menyampaikan kata pencarian, koordinat, atau informasi teknis yang relevan. Periksa kembali visibilitas laporan PetSpot, Petship, atau hewan hilang sebelum mencantumkan alamat pribadi."
    ),
    section("Foto, video, kamera, mikrofon, dan media perangkat",
      "Akses kamera, galeri, berkas, atau mikrofon digunakan ketika Anda memilih fitur yang membutuhkannya, misalnya unggah foto pet, lampiran, laporan layanan, atau konsultasi. Memberikan izin perangkat tidak berarti seluruh isi galeri diunggah; file yang dikirim mengikuti tindakan pemilihan dan fungsi fitur.",
      "Media dapat memuat wajah, suara, latar rumah, papan alamat, metadata, atau orang lain. Tinjau isi sebelum mengunggah dan pastikan Anda berwenang membagikannya. Jangan mengandalkan aplikasi untuk selalu menghapus seluruh metadata atau mengenali semua informasi sensitif dalam foto dan PDF.",
      "Anda dapat mengubah izin pada pengaturan perangkat. Panggilan dan siaran tidak boleh diasumsikan direkam secara otomatis. Apabila fungsi perekaman ditawarkan, informasi mengenai tujuan, penerima, serta penyimpanan perlu diberikan pada konteks tersebut; kebijakan umum ini bukan persetujuan tanpa batas untuk merekam setiap percakapan."
    ),
    section("Komunitas, ulasan, adopsi, PAW Dating, dan hewan hilang",
      "Konten yang Anda pilih untuk dipublikasikan dapat memperlihatkan nama tampilan, foto, informasi pet, cerita, ulasan, lokasi, atau cara menghubungi sesuai fitur. Pengguna lain dapat membaca, menyalin, atau meneruskan konten publik di luar kendali langsung Slivadoc.",
      "Formulir adopsi dan interaksi antar-pet dapat menyampaikan pengalaman merawat, kondisi tempat tinggal, alasan permohonan, dan informasi lain kepada pihak tujuan yang relevan. Bedakan informasi untuk pemeriksaan privat dari bagian yang akan ditampilkan kepada komunitas. Jangan menggunakan fitur untuk mengumpulkan data orang lain secara massal.",
      "Laporan hewan hilang dapat memerlukan titik dan kontak yang membantu pencarian, tetapi hindari detail rutinitas rumah, dokumen kepemilikan lengkap, atau nomor identitas. Penghapusan konten pada Slivadoc tidak menjamin seluruh salinan di perangkat pihak lain atau cache mesin pencari langsung hilang; kami dapat membantu pemeriksaan sesuai kewenangan."
    ),
    section("SlivaCare dan pemrosesan oleh penyedia AI",
      "Ketika Anda menggunakan SlivaCare, pertanyaan, percakapan, dan konteks pet yang diperlukan dapat dikirim kepada penyedia model AI seperti OpenAI untuk menghasilkan jawaban. Informasi yang relevan dapat mencakup spesies, umur, gejala, atau riwayat yang Anda berikan melalui fitur tersebut.",
      "Pemrosesan oleh penyedia dipengaruhi oleh kontrak layanan dan konfigurasi yang digunakan. Kebijakan ini tidak menjanjikan bahwa seluruh penyedia menyimpan data selama nol hari atau bahwa setiap bentuk penggunaan data oleh penyedia telah ditiadakan. Untuk rincian konfigurasi yang berlaku pada layanan Anda, ajukan permintaan informasi melalui kontak privasi.",
      "Jangan mengirim password, OTP, data kartu, dokumen identitas manusia, informasi anak, atau rahasia pihak lain yang tidak diperlukan. Penggunaan percakapan untuk tujuan baru di luar penyediaan layanan harus memiliki dasar pemrosesan dan pemberitahuan yang sesuai. Persetujuan akun tidak menjadi izin otomatis untuk menjual percakapan atau menggunakannya bagi pemasaran yang tidak terkait."
    ),
    section("Chat toko, pesan layanan, pengaduan, dan dukungan",
      "Pesan, pengirim, penerima, waktu, identitas percakapan, dan lampiran yang Anda kirim diproses untuk menyampaikan komunikasi, menjaga riwayat layanan, serta menangani pengaduan. Pihak penerima dapat membaca isi yang Anda tujukan kepadanya dan memiliki salinan yang diperlukan dalam hubungan layanan.",
      "Petugas berwenang dapat mengakses informasi yang relevan untuk menjawab keluhan, memeriksa dugaan penipuan, atau memenuhi kewajiban hukum. Akses tersebut harus dibatasi menurut kebutuhan tugas. Kebijakan ini tidak menyatakan bahwa semua chat menggunakan enkripsi ujung-ke-ujung atau bahwa penyelenggara secara teknis tidak dapat mengaksesnya.",
      "Apabila mengirim bukti percakapan, samarkan informasi pihak lain yang tidak terkait. Jangan memberikan akses rekening, kode keamanan, atau salinan dokumen berlebihan kepada toko maupun dukungan. Laporan penyalahgunaan dapat memerlukan penyimpanan bukti meskipun konten biasa telah dihapus, dengan pembatasan tujuan dan akses yang sesuai."
    ),
    section("Data teknis, penyimpanan lokal, dan teknologi serupa cookie",
      "Situs dan aplikasi dapat memproses alamat IP, jenis perangkat, sistem operasi, versi aplikasi, waktu permintaan, hasil respons, dan log kesalahan yang berkaitan dengan penggunaan layanan. Informasi ini membantu menjalankan sistem, mengenali gangguan, mencegah penyalahgunaan, dan menelusuri kegagalan transaksi.",
      "Penyimpanan lokal dan penyimpanan sesi digunakan antara lain untuk autentikasi, pilihan bahasa, pet aktif, serta halaman atau fitur terakhir yang dibuka. Data ini dapat berada pada browser atau penyimpanan aplikasi di perangkat. Menghapus penyimpanan atau melakukan logout dapat menghilangkan preferensi dan mengharuskan Anda masuk kembali.",
      "Teknologi yang diperlukan untuk fungsi akun dibedakan dari analitik tambahan, pelacakan lintas layanan, atau iklan berbasis perilaku. Apabila pemrosesan tambahan semacam itu diterapkan dan memerlukan persetujuan, pilihan serta penjelasannya harus diberikan secara terpisah. Penerimaan kebijakan ini tidak dengan sendirinya mengaktifkan izin pelacakan iklan tanpa batas."
    ),
    section("Pemetaan tujuan dan dasar pemrosesan",
      "Pembuatan akun, verifikasi kontak, pencarian yang diminta, pemesanan, pembayaran, pengiriman, pelaksanaan perawatan, dan dukungan terkait dilakukan terutama untuk memenuhi perjanjian atau permintaan Anda sebelum perjanjian. Data yang digunakan harus berkaitan langsung dengan kebutuhan layanan tersebut.",
      "Pencatatan transaksi, pemenuhan permintaan otoritas yang sah, dan penyimpanan yang diwajibkan peraturan menggunakan dasar kewajiban hukum. Deteksi penipuan, keamanan sistem, penelusuran gangguan, dan pembelaan klaim dapat menggunakan kepentingan sah setelah mempertimbangkan kebutuhan, dampak, serta hak pengguna; dasar ini bukan izin mengambil semua data yang tersedia.",
      "Pemrosesan pilihan yang memerlukan persetujuan, seperti penggunaan tertentu di luar layanan inti, harus menyebutkan tujuan, jenis data, dan akibat penarikan. Tujuan baru yang tidak sesuai dengan tujuan awal perlu ditinjau dan diberitahukan dengan dasar yang tepat. Kami tidak mengganti alasan pemrosesan secara diam-diam hanya untuk menghindari permintaan penghentian yang sah."
    ),
    section("Mitra penerima data dan pembatasan tujuan",
      "Toko menerima data pesanan, komunikasi, serta penerima yang diperlukan untuk memenuhi pembelian. Klinik, dokter, trainer, atau penyedia perawatan menerima informasi pet, jadwal, keluhan, dan kontak sesuai layanan. Sitter menerima data kunjungan serta instruksi yang diperlukan untuk booking terkait.",
      "Penyelenggara kelas dan event dapat menerima daftar peserta serta pet sesuai pendaftaran; pengelola tempat menerima rincian reservasi; pengelola adopsi menerima permohonan yang Anda tujukan kepadanya; pihak berwenang atas dokumen menerima persyaratan yang diperlukan. Data tidak semestinya dibagikan kepada semua mitra hanya karena mereka terdaftar di platform.",
      "Mitra tidak boleh menggunakan data yang diterima untuk spam, perdagangan data, penyebaran publik, atau kegiatan lain yang tidak memiliki dasar. Apabila mitra menentukan tujuan pemrosesan tersendiri, misalnya pencatatan klinis wajib, tanggung jawabnya sebagai pengendali perlu dipenuhi. Anda dapat meminta penjelasan pihak penerima pada transaksi tertentu."
    ),
    section("Penyedia teknologi, pembayaran, komunikasi, dan logistik",
      "Cloudinary digunakan untuk media dan dokumen. Infrastruktur hosting, basis data, jaringan, dan pengiriman konten memproses data sesuai fungsi teknisnya. Layanan email, termasuk Resend bila digunakan pada lingkungan layanan, memproses alamat tujuan dan isi pesan layanan seperti verifikasi atau pemberitahuan.",
      "Yokke dan penyedia pembayaran yang ditampilkan memproses data yang diperlukan untuk pembayaran dan rekonsiliasi. Lion Parcel dan penyedia pengiriman terkait memproses alamat, kontak penerima, rincian kiriman, dan pelacakan. OpenAI dapat memproses konteks fitur AI, sedangkan layanan Photon/OpenStreetMap mendukung pencarian atau informasi peta sesuai implementasi fitur.",
      "Daftar ini menjelaskan penyedia yang digunakan atau terintegrasi pada layanan dan tidak berarti semua data selalu dikirim ke semua penyedia. Keterlibatan bergantung pada fitur dan konfigurasi yang aktif. Perubahan penyedia yang berdampak material pada tujuan, penerima, atau transfer data perlu diinformasikan dan memperoleh dasar yang sesuai sebelum diterapkan."
    ),
    section("Hubungan pengendali, prosesor, dan permintaan pihak berwenang",
      "Penyedia yang memproses data atas instruksi Slivadoc bertindak sesuai fungsi prosesor dan batas instruksi yang sah. Pengaturan akses, kerahasiaan, keamanan, penerusan kepada subprosesor, serta pengakhiran layanan harus mempertimbangkan pelindungan data. Pihak yang menentukan tujuan sendiri dapat memiliki kewajiban pengendali tersendiri.",
      "Permintaan data dari penegak hukum, regulator, atau pengadilan ditelaah berdasarkan kewenangan, dasar hukum, cakupan, dan bentuk permintaannya. Pengungkapan harus dibatasi pada informasi yang diperlukan. Pemberitahuan kepada pengguna dilakukan sejauh diwajibkan atau dimungkinkan tanpa melanggar larangan yang sah atau mengganggu proses yang dilindungi hukum.",
      "Penggabungan, pengalihan usaha, atau restrukturisasi yang melibatkan data perlu memperhatikan kewajiban pemberitahuan, tujuan pemrosesan, dan hak pengguna. Data tidak boleh dianggap bebas diperdagangkan hanya karena merupakan bagian dari aset usaha. Pihak penerima tetap harus memiliki dasar dan pelindungan yang sesuai."
    ),
    section("Visibilitas publik, tautan, dan salinan di luar platform",
      "Profil atau konten yang ditandai publik dapat diakses oleh pengguna lain dan, bergantung pada cara publikasinya, mesin pencari. Periksa pengaturan serta tujuan publikasi sebelum mengirim informasi. Formulir privat, pesan kepada mitra, dan postingan komunitas memiliki penerima yang berbeda.",
      "Tautan gambar atau dokumen dapat diteruskan oleh penerimanya. Jangan menganggap tautan yang sulit ditebak sama dengan akses yang dilindungi login. Hindari menaruh dokumen identitas, nomor rekening lengkap, atau informasi keamanan rumah pada media yang mungkin dibagikan melalui tautan.",
      "Penghapusan dari tampilan aplikasi tidak selalu menghapus salinan yang disimpan secara mandiri oleh penerima atau pihak lain. Kami dapat menelaah permintaan penghapusan dan menghubungi penyedia sesuai kewenangan, tetapi tidak menjanjikan kendali penuh atas seluruh salinan di internet. Penggunaan ulang oleh pihak lain tetap harus memiliki dasar yang sah."
    ),
    section("Transfer data di luar Indonesia",
      "Penyedia cloud, komunikasi, AI, dan dukungan teknologi dapat memproses atau menyimpan data di luar Indonesia sesuai lokasi infrastrukturnya. Karena itu, penggunaan fitur tertentu dapat melibatkan transfer lintas negara. Kebijakan ini tidak menyatakan bahwa seluruh data pasti berada hanya di wilayah Indonesia.",
      "Pasal 56 UU PDP mensyaratkan pelindungan untuk transfer ke luar wilayah hukum Indonesia. Penilaiannya memperhatikan tingkat pelindungan negara penerima yang setara atau lebih tinggi; jika tidak terpenuhi, pelindungan yang memadai dan bersifat mengikat; dan apabila kedua dasar tersebut tidak terpenuhi, persetujuan subjek data sesuai ketentuan yang berlaku.",
      "Penerimaan kebijakan umum tidak dianggap persetujuan otomatis untuk setiap transfer tanpa informasi. Jika suatu transfer memerlukan persetujuan khusus, informasi penerima, tujuan, jenis data, dan konsekuensi yang relevan perlu dijelaskan. Anda dapat meminta informasi mengenai pemrosesan lintas negara yang terkait dengan layanan yang digunakan."
    ),
    section("Prinsip retensi dan batas penyimpanan menurut kategori",
      "Data akun dan profil dipertahankan selama diperlukan untuk layanan yang aktif, pemulihan yang sah, atau penyelesaian kewajiban terkait. Informasi akses keluarga, booking, dan lampiran ditinjau menurut hubungan layanan, status aktivitas, kebutuhan pembuktian, serta kewajiban khusus yang berlaku.",
      "Untuk data dan informasi PMSE yang masuk cakupan Pasal 25 PP 80 Tahun 2019, berlaku penyimpanan minimum 10 tahun sejak diperoleh untuk yang berkaitan dengan transaksi keuangan dan minimum 5 tahun untuk yang tidak berkaitan dengan transaksi keuangan. Ketentuan ini diterapkan sesuai kategori dan cakupan hukumnya; bukan alasan menyimpan semua foto, isi chat, atau lokasi pet tanpa penilaian selama periode yang sama.",
      "Log keamanan, bukti persetujuan, dan catatan pengaduan disimpan sejauh diperlukan untuk akuntabilitas, pemeriksaan kejadian, dan pembelaan hak yang sah. Apabila ada sengketa atau perintah penyimpanan yang sah, data relevan dapat ditahan sampai kebutuhan tersebut berakhir. Akses dan penggunaan untuk tujuan lain tetap dibatasi.",
      "Data yang tidak lagi memiliki tujuan atau dasar penyimpanan harus dihapus, dimusnahkan, atau dianonimkan secara memadai. Salinan cadangan mengikuti siklus penyimpanan dan pemulihan; penghapusan dari sistem aktif tidak selalu terjadi serentak di setiap cadangan. Anda dapat meminta rincian masa retensi yang berlaku pada jenis data dan aktivitas tertentu melalui kontak privasi."
    ),
    section("Penghapusan akun dan penyelesaian salinan data",
      "Fitur Hapus Akun berada pada Privasi & keamanan dan menggunakan verifikasi OTP. Setelah konfirmasi, permintaan penghapusan akun dijadwalkan dengan masa tenggang 14 hari sesuai alur aplikasi, sehingga Anda dapat membatalkan bila permintaan keliru. Penghapusan akun berbeda dari logout atau menghapus aplikasi dari perangkat.",
      "Masa tenggang akun tidak menunda secara otomatis hak koreksi, akses, penarikan persetujuan, atau pembatasan pemrosesan yang memiliki tenggat menurut UU PDP. Permintaan hak tersebut dapat diajukan terpisah melalui kontak privasi. Penyelesaian pesanan atau retensi wajib hanya menjadi alasan mempertahankan data yang memang diperlukan, bukan seluruh akun untuk semua tujuan.",
      "Data terkait transaksi, sengketa, atau kewajiban hukum dapat dipertahankan secara terbatas setelah profil ditutup. Salinan pada mitra pengendali mandiri dapat tunduk pada kewajibannya sendiri. Permintaan penghapusan lampiran, media, atau data pada penyedia pendukung perlu ditelaah dan ditindaklanjuti sesuai cakupan permintaan serta kewenangan masing-masing pihak.",
      "Anda dapat meminta penjelasan kategori yang dihapus, dianonimkan, atau masih disimpan beserta alasannya. Pemberitahuan penghapusan atau pemusnahan dilakukan sesuai kewajiban hukum, termasuk Pasal 45 UU PDP. Data yang dipertahankan karena kewajiban hukum tidak boleh digunakan sebagai alasan untuk terus mengirim promosi yang telah ditolak."
    ),
    section("Keamanan, pembatasan akses, dan tanggung jawab perangkat",
      "Pelindungan pada sistem mencakup hash password, autentikasi dan pengelolaan sesi, pembatasan akses menurut peran, pemeriksaan kewenangan atas data, serta pencatatan aktivitas keamanan yang relevan. Langkah teknis dan organisasi perlu disesuaikan dengan jenis data, tingkat risiko, dan konteks pemrosesan.",
      "Tidak ada sistem yang dapat menjamin keamanan mutlak. Kebijakan ini tidak menyatakan bahwa Slivadoc memiliki sertifikasi ISO, SOC, audit tertentu, enkripsi ujung-ke-ujung, atau pemindaian malware atas setiap berkas apabila hal tersebut tidak secara terpisah dinyatakan dan dibuktikan. Keterbatasan tidak mengurangi kewajiban mengambil langkah pelindungan yang layak.",
      "Anda membantu menjaga keamanan dengan memperbarui aplikasi, merahasiakan kredensial, mengunci perangkat, menghindari jaringan atau tautan mencurigakan, dan mencabut akses yang tidak diperlukan. Laporkan dugaan kebocoran dengan bukti minimum; jangan menyebarkan ulang data pihak lain atau mencoba mengunduh data tambahan untuk membuktikan adanya celah."
    ),
    section("Insiden pelindungan data pribadi",
      "Dugaan akses tanpa hak, pengiriman ke penerima keliru, kehilangan perangkat yang memuat data, atau kebocoran lampiran ditangani melalui penilaian insiden. Langkah dapat meliputi pembatasan akses, pencabutan sesi, pengamanan bukti, penelusuran cakupan, koordinasi penyedia, serta pemulihan yang relevan.",
      "Pasal 46 UU PDP mewajibkan pemberitahuan tertulis paling lambat 3 × 24 jam kepada subjek data dan lembaga yang berwenang dalam hal terjadi kegagalan pelindungan data pribadi. Pemberitahuan setidaknya menjelaskan data yang terungkap, kapan dan bagaimana kejadian, serta upaya penanganan dan pemulihan. Pemberitahuan kepada masyarakat dilakukan dalam keadaan yang diwajibkan hukum.",
      "Pengguna dapat menerima arahan yang relevan, misalnya mengganti password, mencabut sesi, atau berhati-hati terhadap penipuan lanjutan. Kami tidak meminta transfer uang atau OTP untuk menangani insiden. Informasi dapat diperbarui ketika hasil pemeriksaan bertambah, tanpa menjadikan pemeriksaan internal sebagai alasan mengabaikan kewajiban pemberitahuan."
    ),
    section("Hak atas informasi, akses, salinan, dan perbaikan",
      "Sesuai UU PDP, Anda berhak memperoleh informasi mengenai identitas pengendali, dasar pemrosesan, tujuan, serta akuntabilitas pihak yang menggunakan data. Anda juga dapat meminta akses dan salinan data serta informasi jejak pemrosesan sesuai ketentuan, dengan memperhatikan perlindungan data orang lain.",
      "Anda dapat melengkapi, memperbarui, atau memperbaiki informasi yang keliru melalui pengaturan yang tersedia atau permintaan kepada kami. Kesalahan data profil berbeda dari sengketa isi rekam layanan; catatan transaksi atau medis dapat memerlukan koreksi yang menjaga riwayat dan kewajiban pencatatan.",
      "Permintaan tidak boleh ditolak semata-mata karena Anda tidak lagi menjadi pelanggan aktif. Apabila sebagian data tidak dapat diberikan atau diubah karena dasar hukum, hak pihak lain, atau alasan sah lainnya, penjelasan mengenai cakupan dan alasan perlu disampaikan sejauh diperbolehkan. Pembatasan harus digunakan secara khusus, bukan sebagai pengecualian umum."
    ),
    section("Hak penghapusan, portabilitas, keberatan, dan ganti rugi",
      "Anda dapat meminta pengakhiran pemrosesan, penghapusan atau pemusnahan data, penarikan persetujuan, serta penundaan atau pembatasan sesuai syarat hukum. Permintaan tersebut dinilai per kategori data dan tujuan, karena kewajiban penyimpanan tertentu dapat tetap berlaku meskipun pemrosesan lain dihentikan.",
      "Hak portabilitas mencakup perolehan dan penggunaan data dalam bentuk yang sesuai ketentuan serta pengiriman kepada pengendali lain bila persyaratan hukumnya terpenuhi. Anda juga dapat menyampaikan keberatan atas keputusan yang hanya didasarkan pada pemrosesan otomatis, termasuk pemrofilan, yang menimbulkan akibat hukum atau dampak signifikan.",
      "UU PDP juga mengatur hak mengajukan gugatan dan menerima ganti rugi atas pelanggaran pemrosesan data sesuai ketentuan. Penggunaan mekanisme bantuan Slivadoc tidak menghapus hak tersebut atau mengharuskan pengguna menyetujui pelepasan hak. Untuk penjelasan lengkap, rujuk antara lain Pasal 5 sampai dengan Pasal 13 UU PDP."
    ),
    section("Cara mengajukan permintaan dan verifikasi identitas",
      "Kirim permintaan dari kontak akun yang Anda kuasai, sebutkan hak yang ingin dijalankan, jenis data, dan aktivitas yang relevan. Jika bertindak sebagai wali atau kuasa, jelaskan kewenangan perwakilan. Kami dapat meminta informasi verifikasi minimum agar data tidak diberikan atau dihapus atas permintaan pihak yang tidak berhak.",
      "Verifikasi tidak boleh berubah menjadi pengumpulan dokumen berlebihan. Jika ada cara yang memadai menggunakan sesi, email, atau bukti transaksi, salinan identitas tambahan perlu dipertimbangkan secara proporsional. Permintaan perwakilan harus melindungi hak orang yang diwakili dan tidak otomatis membuka seluruh data keluarga.",
      "Anda akan memperoleh penjelasan tindak lanjut melalui jalur yang sesuai. Apabila permintaan luas atau menyangkut data pihak lain, cakupannya dapat diperjelas dan bagian tertentu disamarkan. Bila ditolak sebagian atau seluruhnya, alasan dan pilihan pengaduan disampaikan sejauh diperbolehkan hukum."
    ),
    section("Batas waktu hak data dan pembatasan yang sah",
      "Pasal 30 UU PDP mengatur perbaikan atau pembaruan paling lambat 3 × 24 jam sejak permintaan diterima; Pasal 32 mengatur akses paling lambat 3 × 24 jam sejak permintaan akses diterima. Penghentian pemrosesan akibat penarikan persetujuan dan penundaan atau pembatasan juga memiliki ketentuan 3 × 24 jam pada Pasal 40 dan Pasal 41, dengan syarat dan pengecualian yang diatur hukum.",
      "Verifikasi, klarifikasi, dan pengaturan operasional tidak boleh dipakai untuk memperpanjang tenggat hukum secara sepihak. Penghapusan, pemusnahan, portabilitas, serta permintaan lainnya mengikuti ketentuan yang berlaku untuk hak tersebut; kami tidak memberlakukan satu tenggat umum yang mengurangi hak yang memiliki batas lebih cepat.",
      "Pengecualian harus didasarkan pada ketentuan yang memang berlaku, misalnya pelindungan hak orang lain atau kewajiban hukum tertentu, dan diterapkan sebatas yang diperlukan. Alasan keamanan, kepentingan usaha, atau adanya sengketa tidak boleh digunakan secara umum untuk menolak semua permintaan tanpa penilaian."
    ),
    section("Penarikan persetujuan dan preferensi pemasaran",
      "Anda dapat menarik persetujuan untuk pemrosesan yang memang didasarkan pada persetujuan melalui kontak privasi atau pilihan yang tersedia pada fitur. Penarikan tidak membatalkan secara surut pemrosesan yang sebelumnya sah. Kami perlu menjelaskan data dan tujuan mana yang dihentikan serta akibatnya terhadap fitur terkait.",
      "Jika data diperlukan untuk memenuhi kontrak yang masih berjalan atau kewajiban hukum, pemrosesan terbatas dapat tetap berlangsung berdasarkan dasar tersebut, dengan penjelasan yang sesuai. Hal ini tidak membolehkan kami mengganti dasar secara semu hanya agar seluruh penggunaan data terus dilakukan setelah Anda menolak.",
      "Pesan pemasaran, bila Anda memilih menerimanya, harus dapat dibedakan dari pemberitahuan transaksi, OTP, keamanan, atau pemenuhan kewajiban. Menolak promosi tidak menghalangi akses ke layanan inti yang tidak memerlukan promosi. Data tidak dijual sebagai komoditas kepada pengiklan berdasarkan penerimaan kebijakan ini."
    ),
    section("Anak, wali, dan pengguna yang memerlukan pendampingan",
      "Data anak memerlukan pelindungan khusus serta persetujuan orang tua atau wali sesuai Pasal 25 UU PDP. Pendaftaran Pet Owner biasa ditujukan kepada pengguna yang cakap; akun tidak boleh dipakai untuk menghindari pembatasan usia. Jika data anak terlanjur dikirim tanpa kewenangan, wali dapat meminta peninjauan dan penanganan melalui kontak privasi.",
      "Penyelenggaraan fitur yang dapat digunakan anak harus memperhatikan UU ITE, PP 17 Tahun 2025, dan Permenkomdigi 9 Tahun 2026 sesuai cakupannya, termasuk penilaian risiko, mekanisme usia atau wali yang diperlukan, dan pelaporan. Persetujuan umum wali tidak menghapus kewajiban membatasi fitur yang tidak sesuai untuk anak.",
      "Pemrosesan bagi penyandang disabilitas mengikuti ketentuan khusus UU PDP dengan komunikasi yang dapat dipahami serta bantuan atau perwakilan yang sah bila diperlukan. Memerlukan pendampingan tidak berarti seseorang otomatis kehilangan kendali atas datanya. Informasi mengenai kondisi disabilitas tidak boleh diminta tanpa relevansi dan dasar yang tepat."
    ),
    section("Rekomendasi, pemrofilan, dan peninjauan manusia",
      "Urutan hasil pencarian atau rekomendasi dapat dipengaruhi jenis pet, lokasi pencarian, ketersediaan, kategori, harga, rating, atau pilihan filter. Informasi tersebut membantu menemukan layanan, tetapi tidak menjamin bahwa hasil pertama paling tepat bagi setiap kebutuhan atau bebas dari keterbatasan data.",
      "Pemeriksaan keamanan dapat menggunakan pola aktivitas untuk mengenali permintaan berlebihan atau indikasi penyalahgunaan. Apabila keputusan yang hanya didasarkan pada pemrosesan otomatis menimbulkan akibat hukum atau dampak signifikan, hak keberatan dan peninjauan sesuai UU PDP harus diperhatikan.",
      "Anda dapat meminta penjelasan mengenai keputusan atau pembatasan yang memengaruhi akun dan memberikan informasi koreksi. Penggunaan AI dalam menjawab pertanyaan tidak dengan sendirinya berarti sistem berwenang memutuskan tindakan medis, hak adopsi, kelayakan hukum, atau tanggung jawab pengguna secara final."
    ),
    section("Pengaduan privasi dan hubungan dengan pihak lain",
      "Jika merasa data digunakan tidak sesuai, ajukan pengaduan dengan jenis data, aktivitas, pihak yang diduga menerima, dan dampak yang diketahui. Kami dapat memeriksa catatan pemrosesan, menjelaskan peran, mengoordinasikan tindak lanjut dengan prosesor, atau mengarahkan bagian permintaan yang merupakan kewenangan pengendali mandiri.",
      "Pengarahan kepada mitra tidak menghapus kewajiban Slivadoc atas pemrosesannya sendiri. Anda tetap dapat mengajukan pengaduan kepada lembaga atau instansi yang berwenang dan menggunakan mekanisme penyelesaian hukum yang tersedia. Kebijakan ini tidak mewajibkan penyelesaian internal sebagai satu-satunya jalan atau melarang pengaduan yang sah.",
      "Saat menyampaikan bukti, batasi penyebaran data agar pengaduan tidak menimbulkan kebocoran tambahan. Jika Anda menerima dokumen orang lain secara keliru, jangan menyebarkannya, laporkan jalur penerimaan, dan ikuti instruksi penanganan yang sah tanpa menghilangkan bukti penting secara sembarangan."
    ),
    section("Perubahan kebijakan, versi, dan arti persetujuan",
      "Versi dan tanggal berlaku ditampilkan pada dokumen. Perubahan material terhadap tujuan, kategori data, penerima, transfer, atau hak pengguna diberitahukan melalui saluran yang sesuai sebelum diterapkan sejauh diwajibkan hukum. Persetujuan baru diminta apabila diperlukan; versi lama tidak digunakan untuk menutupi tujuan baru yang tidak pernah dijelaskan.",
      "Pada registrasi, Kebijakan Privasi dibuka dan dibaca sampai akhir secara terpisah dari Syarat dan Ketentuan, kemudian diterima melalui tombol Saya sudah membaca dan menyetujui. Slivadoc mencatat versi dan waktu penerimaan. Penutupan dokumen tanpa tombol tersebut tidak menandai checkbox persetujuan.",
      "Penerimaan menunjukkan bahwa Anda telah mendapat kesempatan memahami pemberitahuan ini dan menerima pemrosesan dalam batas tujuan serta dasar yang sah. Tindakan itu tidak menghapus hak data, tidak menyetujui semua izin perangkat sekaligus, dan bukan izin umum untuk pemasaran, publikasi dokumen pribadi, atau transfer yang memerlukan persetujuan khusus."
    ),
    section("Panduan praktis menjaga data dan penutup",
      "Tinjau profil, penerima akses keluarga, alamat, dan izin perangkat secara berkala. Gunakan foto pet yang tidak memperlihatkan dokumen atau keamanan rumah. Kirim hanya lampiran yang diminta, periksa pihak penerima, dan gunakan dukungan resmi ketika menerima permintaan data yang tidak wajar.",
      "Sebelum membagikan data orang lain, pastikan Anda berwenang dan menjelaskan tujuannya. Sebelum memakai layanan mitra, periksa informasi penerima serta kebijakannya. Jika tidak memahami suatu pemrosesan, mintalah penjelasan melalui privacy@slivadoc.com; pertanyaan mengenai privasi tidak mensyaratkan pembelian layanan baru.",
      "Kebijakan ini dibaca bersama informasi pada fitur dan peraturan yang berlaku. Jika ada ketentuan yang bertentangan dengan hukum wajib, hak dan kewajiban menurut hukum didahulukan. Rujukan resmi berikut membantu Anda memeriksa dasar pengaturan dan tidak membatasi seluruh aturan lain yang mungkin berlaku pada keadaan tertentu."
    ),
  ],
};

export const legalDocuments: Record<LegalPolicy, LegalDocument> = { terms, privacy };
