import { LocalizedCopy } from "../components/LocalizedCopy";
import { LocalizedLink as Link } from "../components/LocalizedCopy";
import { PublicPage, Breadcrumbs } from "../components/seo/PublicSite";
import { pageMetadata } from "../lib/seo-config";

export const metadata = pageMetadata({ title: "Program Slivadoc Gratis & Akses Seumur Hidup untuk Mitra", description: "Kenali akses aplikasi gratis Slivadoc dan program gratis seumur hidup untuk 1.000 mitra pertama. Lihat cakupan aplikasi dan biaya transaksi terpisah.", path: "/free" });
export default function FreeProgramPage() {
  return <PublicPage><section className="seo-hero"><Breadcrumbs items={[{ label: "Beranda", href: "/" }, { label: "Program gratis" }]} /><span className="seo-eyebrow"><LocalizedCopy>{"Tumbuh bersama Slivadoc"}</LocalizedCopy></span><h1><LocalizedCopy>{"Akses aplikasi gratis untuk bisnis pet care"}</LocalizedCopy></h1><p><LocalizedCopy>{"Portal Slivadoc Partners menawarkan pendaftaran, aktivasi, onboarding, fitur aplikasi, dan pendampingan tanpa biaya pendaftaran, lisensi, atau langganan."}</LocalizedCopy></p><div className="seo-hero-actions"><a className="seo-primary" href="https://partners.slivadoc.com"><LocalizedCopy>{"Lihat program & daftar mitra"}</LocalizedCopy></a><Link className="seo-secondary" href="/for/pet-owner"><LocalizedCopy>{"Manfaat untuk pet owner"}</LocalizedCopy></Link></div></section><section className="seo-main-section"><div className="seo-info-grid"><article className="seo-info-box"><h2><LocalizedCopy>{"Program gratis seumur hidup"}</LocalizedCopy></h2><p><LocalizedCopy>{"Program undangan 1.000 mitra pertama Slivadoc menawarkan akses gratis seumur hidup. Tim onboarding mengonfirmasi kelayakan, kuota, dan ketentuan program pada saat pendaftaran."}</LocalizedCopy></p><p><LocalizedCopy>{"Informasi ini tidak menyatakan bahwa kuota masih tersedia. Simpan konfirmasi program yang diterima untuk mengetahui hak akses bisnis Anda."}</LocalizedCopy></p></article><article className="seo-info-box"><h2><LocalizedCopy>{"Biaya produk dan layanan"}</LocalizedCopy></h2><p><LocalizedCopy>{"Gratis menggunakan aplikasi tidak menghapus harga produk, grooming, konsultasi, vaksinasi, penitipan, ongkir, pajak, atau biaya pembayaran pihak ketiga. Periksa rincian biaya yang berlaku sebelum menyetujui transaksi."}</LocalizedCopy></p><Link href="/terms"><LocalizedCopy>{"Baca syarat & ketentuan"}</LocalizedCopy></Link></article></div></section><section className="seo-main-section"><h2><LocalizedCopy>{"Kenapa bergabung?"}</LocalizedCopy></h2><p><LocalizedCopy>{"Hubungkan profil bisnis, katalog, layanan, dan aktivitas pelanggan. Pet owner dapat menemukan produk serta layanan yang dipublikasikan, sementara tim bisnis mengelola operasional melalui aplikasi Slivadoc."}</LocalizedCopy></p><Link href="/partners"><LocalizedCopy>{"Kenali manfaat untuk petshop, klinik, dokter hewan, dan layanan pet"}</LocalizedCopy></Link></section></PublicPage>;
}
