import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import JsonLd from "../../components/seo/JsonLd";
import { Breadcrumbs, PublicPage } from "../../components/seo/PublicSite";
import { guideBySlug, guidePages } from "../../lib/seo-content";
import { SEO, absoluteUrl, breadcrumbSchema, pageMetadata } from "../../lib/seo-config";

export function generateStaticParams(){return guidePages.map(({slug})=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const guide=guideBySlug.get(slug);if(!guide)return pageMetadata({title:"Panduan tidak ditemukan",description:"Panduan Slivadoc tidak ditemukan.",path:`/panduan/${slug}`,noIndex:true});return pageMetadata({title:guide.title,description:guide.description,path:`/panduan/${guide.slug}`,type:"article",keywords:[guide.category,"panduan anabul","Slivadoc"]});}

export default async function GuideDetailPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const guide=guideBySlug.get(slug);if(!guide)notFound();const related=guidePages.filter((item)=>item.slug!==guide.slug).slice(0,5);const schema=[{"@context":"https://schema.org","@type":"Article",headline:guide.title,description:guide.description,datePublished:guide.updatedAt,dateModified:guide.updatedAt,inLanguage:SEO.language,mainEntityOfPage:absoluteUrl(`/panduan/${guide.slug}`),author:{"@type":"Organization",name:guide.reviewedBy,url:absoluteUrl("/tentang")},publisher:{"@type":"Organization","@id":absoluteUrl("/#organization"),name:SEO.brand,logo:{"@type":"ImageObject",url:absoluteUrl("/brand/slivadoc-logo.png")}},image:absoluteUrl("/slivadoc-pet-hero.png")},{"@context":"https://schema.org","@type":"FAQPage",mainEntity:guide.faq.map((item)=>({"@type":"Question",name:item.question,acceptedAnswer:{"@type":"Answer",text:item.answer}}))},breadcrumbSchema([{name:"Beranda",path:"/"},{name:"Panduan",path:"/panduan"},{name:guide.title,path:`/panduan/${guide.slug}`}])];return <PublicPage><JsonLd data={schema}/><section className="seo-hero"><Breadcrumbs items={[{label:"Beranda",href:"/"},{label:"Panduan",href:"/panduan"},{label:guide.title}]}/><div><span className="seo-eyebrow">{guide.category}</span><h1>{guide.title}</h1><p>{guide.description}</p></div></section><section className="seo-main-section seo-guide-layout"><article className="seo-article"><div className="seo-article-meta"><span>Diperbarui {new Date(`${guide.updatedAt}T00:00:00Z`).toLocaleDateString("id-ID",{dateStyle:"long",timeZone:"UTC"})}</span><span>Ditinjau {guide.reviewedBy}</span><span>{guide.readMinutes} menit baca</span></div><p>{guide.intro}</p>{guide.sections.map((section)=><section key={section.heading}><h2>{section.heading}</h2><p>{section.body}</p>{section.points&&<ul>{section.points.map((point)=><li key={point}>{point}</li>)}</ul>}</section>)}<div className="seo-notice"><strong>Catatan keselamatan:</strong> Informasi ini bersifat edukatif dan tidak menggantikan pemeriksaan, diagnosis, atau perawatan dokter hewan. Untuk kondisi darurat, segera cari fasilitas veteriner terdekat.</div>{guide.faq.length>0&&<section><h2>Pertanyaan umum</h2><div className="seo-faq">{guide.faq.map((item)=><details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</div></section>}</article><aside className="seo-aside"><strong>Panduan lainnya</strong>{related.map((item)=><Link key={item.slug} href={`/panduan/${item.slug}`}>{item.title}</Link>)}</aside></section></PublicPage>}
